import type { FrontendProductSurfaceDecision, FrontendProductSurfaceInput, FrozenFrontendSurfaceFixtureTruth, SurfaceStateContract } from "../../src/intelligence/frontend-product-surface/types.js";
import { ALL_POSITIVE_INPUTS } from "./fixtureInputs.js";

const unique = <T>(items: T[]): T[] => [...new Set(items)];
const stateKey = (state: SurfaceStateContract): string => `state:${state.surface_ref}:${state.state}:${state.upstream_variant_refs.join(",")}`;

/** Provider-blind frozen oracle. No provider, synthesizer, parser, gate or evaluator is imported or called. */
function projectOracle(input: FrontendProductSurfaceInput): FrontendProductSurfaceDecision {
  const entryIds = input.entry_intent_refs.map((ref, index) => `entry:${index + 1}:${ref}`); const goalRefs = unique(input.actors_goals.map((item) => item.goal_ref)); const goalIds = goalRefs.map((ref, index) => `goal:${index + 1}:${ref}`);
  const requiredSteps = [...input.form_intents.map((form, index) => ({ id: `form-step:${index + 1}:${form.form_ref}`, kind: "COMPONENT" as const, purpose: `Validate and submit ${form.form_ref}`, source_refs: unique([form.form_ref, ...form.source_refs]), terminal: false })), ...input.policy_refs.approval_refs.map((ref, index) => ({ id: `approval-step:${index + 1}:${ref}`, kind: "DIALOG" as const, purpose: `Await human/policy authority ${ref}`, source_refs: [ref], terminal: false }))];
  const nodes = [...entryIds.map((id, index) => ({ id, kind: "PAGE" as const, purpose: `Entry intent ${input.entry_intent_refs[index]}`, source_refs: [input.entry_intent_refs[index], ...input.spec_refs], terminal: false })), ...requiredSteps, ...goalIds.map((id, index) => ({ id, kind: "TERMINAL" as const, purpose: `Required outcome ${goalRefs[index]}`, source_refs: unique([...input.spec_refs, ...input.actors_goals.filter((item) => item.goal_ref === goalRefs[index]).flatMap((item) => item.source_refs)]), terminal: true }))];
  const edges = goalIds.flatMap((goal, goalIndex) => { const chain = [entryIds[goalIndex % Math.max(1, entryIds.length)] ?? "missing-entry", ...requiredSteps.map((step) => step.id), goal]; return chain.slice(0, -1).map((from, edgeIndex) => ({ id: `edge:${goalIndex + 1}:${edgeIndex + 1}`, from, to: chain[edgeIndex + 1], trigger: edgeIndex === chain.length - 2 ? `Complete ${goalRefs[goalIndex]}` : `Continue required step ${edgeIndex + 1}`, condition_source_refs: unique([...input.spec_refs, ...(requiredSteps[edgeIndex]?.source_refs ?? [])]), recovery: false })); });
  const surfaces = nodes.map((node) => ({ surface_ref: node.id, kind: node.kind, priority: node.terminal ? "PRIMARY" as const : "SECONDARY" as const, goal_refs: node.terminal ? [node.id.split(":").slice(2).join(":")] : unique(input.actors_goals.map((item) => item.goal_ref)), source_refs: [...node.source_refs] })); const primary = entryIds[0];
  const state_matrix: SurfaceStateContract[] = [{ surface_ref: primary, state: "INITIAL", applicable: true, upstream_variant_refs: [], copy_intent: "Orient the user to the task.", available_action_refs: [], recovery_action_refs: [], announcement_required: false, source_refs: [...input.spec_refs] }];
  if (input.upstream_variants.length) state_matrix.push({ surface_ref: primary, state: "LOADING", applicable: true, upstream_variant_refs: [], copy_intent: "Explain that current data is loading without presenting stale success.", available_action_refs: [], recovery_action_refs: [], announcement_required: true, source_refs: unique(input.upstream_variants.flatMap((item) => item.source_refs)) });
  for (const variant of input.upstream_variants) { const recoverable = (variant.semantic_kind === "ERROR" || variant.semantic_kind === "UNAVAILABLE") && variant.retryability !== "NOT_RETRYABLE"; state_matrix.push({ surface_ref: primary, state: variant.semantic_kind, applicable: true, upstream_variant_refs: [variant.variant_ref], copy_intent: `Explain the ${variant.semantic_kind.toLowerCase().replace("_", " ")} outcome and next safe action.`, available_action_refs: variant.semantic_kind === "SUCCESS" ? input.required_outcome_refs.map((ref) => `action:${ref}`) : [], recovery_action_refs: recoverable ? [`retry:${variant.variant_ref}`, "exit:safe"] : variant.semantic_kind === "VALIDATION_ERROR" ? ["return:form"] : ["ERROR", "UNAVAILABLE"].includes(variant.semantic_kind) ? ["exit:safe"] : [], announcement_required: !["SUCCESS", "EMPTY"].includes(variant.semantic_kind), source_refs: [...variant.source_refs] }); if (recoverable) state_matrix.push({ surface_ref: primary, state: "RETRY_AVAILABLE", applicable: true, upstream_variant_refs: [variant.variant_ref], copy_intent: "Offer a source-authorized retry or safe exit.", available_action_refs: [`retry:${variant.variant_ref}`], recovery_action_refs: ["exit:safe"], announcement_required: false, source_refs: [...variant.source_refs] }); }
  for (const approvalRef of input.policy_refs.approval_refs) for (const state of ["APPROVAL_PENDING", "APPROVED", "REJECTED"] as const) state_matrix.push({ surface_ref: primary, state, applicable: true, upstream_variant_refs: [], copy_intent: `Represent ${state.toLowerCase().replace("_", " ")} without changing authority.`, available_action_refs: state === "REJECTED" ? ["exit:safe"] : [], recovery_action_refs: state === "REJECTED" ? ["exit:safe"] : [], announcement_required: true, source_refs: [approvalRef] });
  const forms = input.form_intents.map((form) => ({ form_ref: form.form_ref, field_refs: form.field_intents.map((field) => field.field_ref), submit_lifecycle: ["IDLE", "SUBMITTING", "SUCCESS_OR_ERROR"] as const, duplicate_submit_disabled_while_pending: form.duplicate_submit_policy === "DISABLE_WHILE_PENDING", preserve_input_on_recoverable_error: form.field_intents.every((field) => field.preserve_on_recoverable_error), cancel_exit_policy: form.cancel_exit_policy, destructive_guardrail_ref: form.destructive_guardrail_ref }));
  const retries = input.upstream_variants.filter((item) => item.semantic_kind === "ERROR" || item.semantic_kind === "UNAVAILABLE").map((item) => ({ source_variant_ref: item.variant_ref, allowed: item.retryability === "SAFE_RETRY" || (item.retryability === "POLICY_REQUIRED" && input.policy_refs.retry_refs.length > 0), authorization_ref: item.retryability === "POLICY_REQUIRED" ? input.policy_refs.retry_refs[0] : undefined }));
  const approvals = input.policy_refs.approval_refs.map((ref) => ({ approval_ref: ref, pending_state_ref: `${primary}:APPROVAL_PENDING`, approved_state_ref: `${primary}:APPROVED`, rejected_state_ref: `${primary}:REJECTED`, frontend_can_self_approve: false as const })); const actions = input.required_outcome_refs.map((ref) => `action:${ref}`);
  const accessibility = { semantic_structure_required: true, keyboard_required_action_refs: actions, focus_order_refs: surfaces.map((item) => item.surface_ref), focus_restore_transition_refs: edges.map((edge) => edge.id), visible_focus_required: true, accessible_name_control_refs: input.form_intents.flatMap((form) => form.field_intents.map((field) => field.field_ref)), description_association_refs: input.form_intents.flatMap((form) => form.field_intents.filter((field) => field.description_intent).map((field) => field.field_ref)), error_association_refs: input.form_intents.flatMap((form) => form.field_intents.filter((field) => field.error_association_required).map((field) => field.field_ref)), announcement_state_refs: state_matrix.filter((state) => state.announcement_required).map(stateKey), contrast_policy_ref: input.policy_refs.accessibility_refs[0], reduced_motion_policy_ref: input.policy_refs.accessibility_refs[1], touch_target_policy_ref: input.policy_refs.accessibility_refs[2], exception_refs: [], browser_conformance_claimed: false as const };
  const responsive = surfaces.flatMap((surface) => (["NARROW", "MEDIUM", "WIDE"] as const).map((viewport) => ({ surface_ref: surface.surface_ref, viewport, primary_content_refs: [surface.surface_ref], primary_action_refs: actions, overflow_strategy: input.spec_refs.some((ref) => ref.includes("collection:dense")) ? "Reflow each dense item into a labelled stacked record with bounded horizontal overflow as fallback." : "Reflow without losing essential content.", semantic_order_preserved: true, focus_order_preserved: true })));
  const traceability = [...nodes.map((item) => ({ artifact_ref: item.id, source_refs: item.source_refs })), ...edges.map((item) => ({ artifact_ref: item.id, source_refs: item.condition_source_refs })), ...surfaces.map((item) => ({ artifact_ref: `surface:${item.surface_ref}`, source_refs: item.source_refs })), ...state_matrix.map((item) => ({ artifact_ref: stateKey(item), source_refs: item.source_refs })), ...forms.map((item) => ({ artifact_ref: `form:${item.form_ref}`, source_refs: input.form_intents.find((form) => form.form_ref === item.form_ref)!.source_refs })), ...retries.map((item) => ({ artifact_ref: `retry:${item.source_variant_ref}`, source_refs: input.upstream_variants.find((variant) => variant.variant_ref === item.source_variant_ref)!.source_refs })), ...approvals.map((item) => ({ artifact_ref: `approval:${item.approval_ref}`, source_refs: [item.approval_ref] })), { artifact_ref: "accessibility", source_refs: unique([...input.policy_refs.accessibility_refs, ...input.spec_refs]) }, ...responsive.map((item) => ({ artifact_ref: `responsive:${item.surface_ref}:${item.viewport}`, source_refs: unique([...input.policy_refs.responsive_refs, ...input.spec_refs]) }))];
  return { status: "READY", blockers: [], task_ref: input.task_ref, spec_refs: [...input.spec_refs], flow_graph: { entry_node_ids: entryIds, goal_node_ids: goalIds, nodes, edges, interruptible_exit_policy_refs: nodes.length > 2 ? [...input.spec_refs] : [] }, surfaces, state_matrix, forms, retries, approvals, accessibility, responsive, traceability, acceptance: structuredClone(input.acceptance), evidence_required: structuredClone(input.evidence_required), deferred_to_s13l: ["security and authorization enforcement"], deferred_to_s13o: ["retry mechanics and reliability"], deferred_to_s13p: ["AI-system observability"], deferred_to_s13q: ["delivery copy and demo"], deferred_to_s13r: ["deployment"], deferred_to_s14: ["browser/runtime capability binding"] };
}

function observe(decision: FrontendProductSurfaceDecision): Record<string, unknown> { const nodes = decision.flow_graph.nodes, edges = decision.flow_graph.edges, surfaces = decision.surfaces, states = decision.state_matrix, forms = decision.forms, retries = decision.retries, approvals = decision.approvals, responsive = decision.responsive, traceability = decision.traceability; return {
    "SD1-A": { goals: structuredClone(decision.flow_graph.goal_node_ids), topology: edges.map((edge) => ({ from: edge.from, to: edge.to })) }, "SD1-B": nodes.map((node) => node.terminal), "SD1-C": { entries: structuredClone(decision.flow_graph.entry_node_ids), exits: structuredClone(decision.flow_graph.interruptible_exit_policy_refs), recovery_flags: edges.map((edge) => edge.recovery) },
    "SD2-A": surfaces.map((item) => item.kind), "SD2-B": surfaces.map((item) => item.priority), "SD2-C": surfaces.map((item) => structuredClone(item.goal_refs)),
    "SD3-A": states.map((item) => ({ state: item.state, applicable: item.applicable })), "SD3-B": states.map((item) => structuredClone(item.upstream_variant_refs)), "SD3-C": states.map((item) => ({ copy: item.copy_intent ?? null, actions: structuredClone(item.available_action_refs), recovery: structuredClone(item.recovery_action_refs), announce: item.announcement_required })),
    "SD4-A": forms.map((item) => structuredClone(item.field_refs)), "SD4-B": forms.map((item) => ({ lifecycle: structuredClone(item.submit_lifecycle), duplicate_disabled: item.duplicate_submit_disabled_while_pending })), "SD4-C": forms.map((item) => ({ preserve: item.preserve_input_on_recoverable_error, cancel: item.cancel_exit_policy })),
    "SD5-A": retries.map((item) => ({ allowed: item.allowed, authorization: item.authorization_ref ?? null })), "SD5-B": approvals.map((item) => ({ pending: item.pending_state_ref, approved: item.approved_state_ref, rejected: item.rejected_state_ref })), "SD5-C": { guardrails: forms.map((item) => item.destructive_guardrail_ref ?? null), self_approval_count: approvals.filter((item) => item.frontend_can_self_approve !== false).length },
    "SD6-A": { semantic: decision.accessibility.semantic_structure_required, keyboard: structuredClone(decision.accessibility.keyboard_required_action_refs), visible_focus: decision.accessibility.visible_focus_required }, "SD6-B": { names: structuredClone(decision.accessibility.accessible_name_control_refs), descriptions: structuredClone(decision.accessibility.description_association_refs), errors: structuredClone(decision.accessibility.error_association_refs) }, "SD6-C": { focus_order: structuredClone(decision.accessibility.focus_order_refs), restore: structuredClone(decision.accessibility.focus_restore_transition_refs), announcements: structuredClone(decision.accessibility.announcement_state_refs), conformance: decision.accessibility.browser_conformance_claimed },
    "SD7-A": responsive.map((item) => item.viewport), "SD7-B": responsive.map((item) => ({ content: structuredClone(item.primary_content_refs), actions: structuredClone(item.primary_action_refs) })), "SD7-C": responsive.map((item) => ({ overflow: item.overflow_strategy, semantic: item.semantic_order_preserved, focus: item.focus_order_preserved })),
    "SD8-A": traceability.map((item) => item.artifact_ref), "SD8-B": traceability.map((item) => structuredClone(item.source_refs)), "SD8-C": { retry_variant_refs: retries.map((item) => item.source_variant_ref), approval_refs: approvals.map((item) => item.approval_ref) },
    "SD9-A": { task: decision.task_ref, specs: structuredClone(decision.spec_refs) }, "SD9-B": structuredClone(decision.acceptance), "SD9-C": structuredClone(decision.evidence_required),
    "SD10-A": { s13l: structuredClone(decision.deferred_to_s13l), s13o: structuredClone(decision.deferred_to_s13o), s13p: structuredClone(decision.deferred_to_s13p) }, "SD10-B": { s13q: structuredClone(decision.deferred_to_s13q), s13r: structuredClone(decision.deferred_to_s13r), s14: structuredClone(decision.deferred_to_s14) }, "SD10-C": { forbidden_binding: false, status: decision.status, blockers: structuredClone(decision.blockers) }, "XC-A": true,
  }; }

export const FROZEN_FRONTEND_SURFACE_FIXTURE_TRUTH: readonly FrozenFrontendSurfaceFixtureTruth[] = Object.freeze(ALL_POSITIVE_INPUTS.map((input) => Object.freeze({ task_ref: input.task_ref, expected_assertions: Object.freeze(observe(projectOracle(input))) })));
