import { createHash } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { ReferenceCapabilityProvider } from "../../src/providers/capability/referenceCapabilityProvider.js";
import { LocalReferenceSkillProvider } from "../../src/providers/skill/localReferenceSkillProvider.js";
import type { ModelDecisionRequest, ModelDecisionResult, ModelProvider } from "../../src/core/agent/index.js";
import { FRONTEND_SURFACE_COMPARISON_ASSERTIONS, FRONTEND_PRODUCT_SURFACE_SKILL_ID, compareFrontendProductSurfaceRuns, deriveFrontendSurfaceProfileFromRules, extractFrontendSurfaceAssertionObservations, gateFrontendProductSurface, planFrontendProductSurface, synthesizeFrontendProductSurfaceDecision, validateFrontendProductSurfaceDecision, validateFrontendProductSurfaceInput, type FrontendProductSurfaceDecision, type FrontendProductSurfaceInput } from "../../src/intelligence/frontend-product-surface/index.js";
import { frontendProductSurfaceS13K, referenceSkillCatalogEntries } from "../../src/intelligence/skills/index.js";
import { ALL_NEGATIVE_FIXTURES, ALL_POSITIVE_INPUTS, DeterministicFrontendSurfaceModelProvider, FX_POS_001, FX_POS_002, FX_POS_003, FX_POS_004, FX_POS_005, FX_POS_006, baseFrontendSurfaceInput, frontendSurfaceHost } from "./fixtures.js";
import { FROZEN_FRONTEND_SURFACE_FIXTURE_TRUTH } from "./fixtureTruth.js";

const capabilityProvider = new ReferenceCapabilityProvider(); const skillProvider = new LocalReferenceSkillProvider(referenceSkillCatalogEntries); const modelProvider = new DeterministicFrontendSurfaceModelProvider(); const sourceDir = "src/intelligence/frontend-product-surface";
const PART_A = ["brain-bootstrap/skills/FRONTEND_PRODUCT_SURFACE_SKILL_S13K.md", "brain-bootstrap/quality-contracts/S13K_FRONTEND_PRODUCT_SURFACE_DEEP.yaml", "brain-bootstrap/specs/FRONTEND_PRODUCT_SURFACE_CONTRACT_S13K.md"];
const rich = () => deriveFrontendSurfaceProfileFromRules([...frontendProductSurfaceS13K.rules.map((rule) => rule.statement), ...frontendProductSurfaceS13K.procedure.map((step) => step.instruction)]);
const faithful = (input: FrontendProductSurfaceInput) => synthesizeFrontendProductSurfaceDecision(input, rich());
async function run(input: FrontendProductSurfaceInput, withSkill: boolean) { const host = structuredClone(frontendSurfaceHost); if (!withSkill) host.skills = []; return planFrontendProductSurface(input, { baseDefinition: host, ...(withSkill ? { skillProvider } : {}), modelProvider, capabilityProvider }); }

describe("S13K Part A, typed Skill and bounded inputs T1-T4", () => {
  it("Part A hashes remain exact", () => expect(PART_A.map((path) => createHash("sha256").update(readFileSync(path)).digest("hex"))).toEqual(["10e8113d037c6dd262a82a33361558afc6bf783ffbac75443ee1aa3aa9b15ad0", "f9f86b248998f2bddc7e90edc5bf85c5bcabd20beb90ac109adf3ca9d25899b4", "375fe043c69b8c6d78381ce55036c3ea977e7de4843a5021d2d3b24356486b41"]));
  it("T1 valid bounded input and decision pass", () => { expect(validateFrontendProductSurfaceInput(FX_POS_001).valid).toBe(true); expect(validateFrontendProductSurfaceDecision(faithful(FX_POS_001), FX_POS_001).valid).toBe(true); });
  it("T2 input is immutable", () => { const input = baseFrontendSurfaceInput(); const before = JSON.stringify(input); faithful(input); expect(JSON.stringify(input)).toBe(before); });
  it("T3 one-task boundary blocks empty/mismatched task", () => { const input = baseFrontendSurfaceInput(); input.task_ref = ""; expect(validateFrontendProductSurfaceInput(input).valid).toBe(false); const d = faithful(FX_POS_001); d.task_ref = "other"; expect(gateFrontendProductSurface(FX_POS_001, d).decision.status).toBe("BLOCKED"); });
  it("T4/T70-T72 Skill is framework-neutral, SKILL_ONLY and side-effect free", () => { expect(frontendProductSurfaceS13K.requires.capabilities).toEqual([]); expect(frontendProductSurfaceS13K.permissions).toMatchObject({ allowed_capabilities: [], allowed_side_effects: ["NONE"] }); expect(readdirSync("src/intelligence/agent-definitions").some((name) => /frontend|surface|s13k/i.test(name))).toBe(false); for (const dir of ["src/core/agent", "src/core/skill"]) for (const name of readdirSync(dir)) if (name.endsWith(".ts")) expect(readFileSync(join(dir, name), "utf8")).not.toContain(FRONTEND_PRODUCT_SURFACE_SKILL_ID); });
});

describe("flow, state and form semantics T5-T41", () => {
  it("T5/T9 required goals are reachable and recoverable errors have recovery", () => { const d = faithful(FX_POS_001); expect(d.flow_graph.goal_node_ids.every((goal) => d.flow_graph.edges.some((edge) => edge.to === goal))).toBe(true); expect(d.state_matrix.find((state) => state.state === "ERROR")!.recovery_action_refs.length).toBeGreaterThan(0); });
  it("T11/T12 interruptible flows and transitions carry policy/source refs", () => { const d = faithful(FX_POS_005); expect(d.flow_graph.interruptible_exit_policy_refs.length).toBeGreaterThan(0); expect(d.flow_graph.edges.every((edge) => edge.condition_source_refs.length > 0)).toBe(true); });
  it("T13 success cannot bypass required validation/approval and approval states remain distinct", () => { const d = faithful(FX_POS_003); expect(d.approvals[0].frontend_can_self_approve).toBe(false); expect(new Set([d.approvals[0].pending_state_ref, d.approvals[0].approved_state_ref, d.approvals[0].rejected_state_ref]).size).toBe(3); const approvalNode = d.flow_graph.nodes.find((node) => node.source_refs.includes("approval:human-review"))!; expect(d.flow_graph.edges.some((edge) => edge.to === approvalNode.id)).toBe(true); const bypass = structuredClone(d); bypass.flow_graph.nodes = bypass.flow_graph.nodes.filter((node) => node.id !== approvalNode.id); bypass.flow_graph.edges = [{ id: "bypass", from: bypass.flow_graph.entry_node_ids[0], to: bypass.flow_graph.goal_node_ids[0], trigger: "bypass", condition_source_refs: ["spec:approval"], recovery: false }]; expect(gateFrontendProductSurface(FX_POS_003, bypass).decision.blockers.join(" ")).toContain("bypasses approval"); });
  it("T14-T20 loading/empty/error/unavailable/permission variants map distinctly", () => { for (const input of [FX_POS_001, FX_POS_002, FX_POS_006]) { const d = faithful(input); expect(input.upstream_variants.every((variant) => d.state_matrix.some((state) => state.upstream_variant_refs.includes(variant.variant_ref) && state.state === variant.semantic_kind))).toBe(true); expect(d.state_matrix.some((state) => state.state === "LOADING")).toBe(true); } });
  it("T21-T23 copy stays semantic and rejects internal or fabricated brand/legal content", () => { const d = faithful(FX_POS_001); expect(d.state_matrix.every((state) => !/stack|sqlstate|token=/i.test(state.copy_intent ?? ""))).toBe(true); for (const index of [24, 25]) expect(gateFrontendProductSurface(ALL_NEGATIVE_FIXTURES[index].input, ALL_NEGATIVE_FIXTURES[index].decision).decision.status).toBe("BLOCKED"); });
  it("T24-T32 forms preserve names, timings, associations, lifecycle, duplicate safety and exit", () => { const d = faithful(FX_POS_002), form = d.forms[0], inputForm = FX_POS_002.form_intents[0]; expect(d.accessibility.accessible_name_control_refs).toEqual(inputForm.field_intents.map((field) => field.field_ref)); expect(inputForm.field_intents.every((field) => field.validation_timings.length > 0)).toBe(true); expect(d.accessibility.error_association_refs).toEqual(inputForm.field_intents.map((field) => field.field_ref)); expect(form.submit_lifecycle).toEqual(["IDLE", "SUBMITTING", "SUCCESS_OR_ERROR"]); expect(form.duplicate_submit_disabled_while_pending).toBe(true); expect(form.preserve_input_on_recoverable_error).toBe(true); expect(form.cancel_exit_policy.length).toBeGreaterThan(0); const safe = structuredClone(FX_POS_002); safe.form_intents[0].duplicate_submit_policy = "EXPLICITLY_SAFE_MULTI_SUBMIT"; safe.form_intents[0].source_refs.push("proof:safe-multi-submit"); expect(validateFrontendProductSurfaceInput(safe).valid).toBe(true); });
  it("T33-T41 retry/approval/destructive/auth authority boundaries are source-backed", () => { const list = faithful(FX_POS_001); expect(list.retries.find((retry) => retry.source_variant_ref === "variant:list-error")!.allowed).toBe(true); const destructive = faithful(FX_POS_004); expect(destructive.retries.find((retry) => retry.source_variant_ref === "variant:delete-error")!.allowed).toBe(false); expect(destructive.forms[0].destructive_guardrail_ref).toBe("guardrail:destructive-approval"); const policy = faithful(FX_POS_006); expect(policy.retries.find((retry) => retry.source_variant_ref === "variant:report-unavailable")!.authorization_ref).toBe("retry:availability-policy"); expect(JSON.stringify(policy)).not.toMatch(/client[_ -](?:tenant|user).*(?:authority|enforce)/i); });
});

describe("accessibility, responsive, hierarchy and traceability T42-T68", () => {
  it("T42-T51 accessibility intent covers keyboard/focus/names/descriptions/errors/announcements without conformance claim", () => { const d = faithful(FX_POS_002); expect(d.accessibility.semantic_structure_required).toBe(true); expect(d.accessibility.keyboard_required_action_refs.length).toBeGreaterThan(0); expect(d.accessibility.focus_order_refs.length).toBeGreaterThan(0); expect(d.accessibility.focus_restore_transition_refs.length).toBeGreaterThan(0); expect(d.accessibility.visible_focus_required).toBe(true); expect(d.accessibility.accessible_name_control_refs).toHaveLength(2); expect(d.accessibility.description_association_refs).toHaveLength(2); expect(d.accessibility.error_association_refs).toHaveLength(2); expect(d.accessibility.announcement_state_refs.length).toBeGreaterThan(0); expect(d.accessibility.browser_conformance_claimed).toBe(false); });
  it("T52-T58 NARROW/MEDIUM/WIDE preserve primary reachability/order and dense strategy", () => { const d = faithful(FX_POS_001); for (const surface of d.surfaces) { const rows = d.responsive.filter((row) => row.surface_ref === surface.surface_ref); expect(rows.map((row) => row.viewport)).toEqual(["NARROW", "MEDIUM", "WIDE"]); expect(rows.every((row) => row.primary_content_refs.length && row.primary_action_refs.length && row.semantic_order_preserved && row.focus_order_preserved)).toBe(true); expect(rows.find((row) => row.viewport === "NARROW")!.overflow_strategy).toMatch(/stack|overflow|reflow/i); } });
  it("T59-T62 inventory priorities and source traceability cover every artifact", () => { const d = faithful(FX_POS_004); expect(d.surfaces.every((surface) => surface.goal_refs.length && surface.source_refs.length)).toBe(true); expect(d.surfaces.filter((surface) => surface.kind === "TERMINAL").every((surface) => surface.priority !== "OPTIONAL")).toBe(true); expect(d.traceability.length).toBeGreaterThan(d.surfaces.length + d.state_matrix.length); expect(validateFrontendProductSurfaceDecision(d, FX_POS_004).valid).toBe(true); });
  it("T63-T68 S13I semantics/adjacent boundaries/acceptance/evidence remain unchanged", () => { const d = faithful(FX_POS_006); expect(d.state_matrix.flatMap((state) => state.upstream_variant_refs).filter(Boolean).every((ref) => FX_POS_006.upstream_variants.some((variant) => variant.variant_ref === ref))).toBe(true); expect([d.deferred_to_s13l, d.deferred_to_s13o, d.deferred_to_s13p, d.deferred_to_s13q, d.deferred_to_s13r, d.deferred_to_s14].every((items) => items.length)).toBe(true); expect(d.acceptance).toEqual(FX_POS_006.acceptance); expect(d.evidence_required).toEqual(FX_POS_006.evidence_required); });
});

describe("actual candidate, real runtime and anti-substitution T69-T80", () => {
  it("T69 candidate READY with unreachable goal gates BLOCKED and preserves the actual candidate", () => { const candidate = faithful(FX_POS_001); candidate.flow_graph.edges = []; candidate.surfaces[0].source_refs.push("marker:actual-candidate"); candidate.status = "READY"; const gated = gateFrontendProductSurface(FX_POS_001, candidate); expect(gated.decision.status).toBe("BLOCKED"); expect(gated.decision.surfaces[0].source_refs).toContain("marker:actual-candidate"); });
  it("T73/T74 metadata-only discovery and lazy S13K load are real", async () => { let loads = 0; const entries = referenceSkillCatalogEntries.map((entry) => entry.descriptor.id === FRONTEND_PRODUCT_SURFACE_SKILL_ID ? { descriptor: entry.descriptor, load_definition: async () => { loads += 1; return entry.load_definition(); } } : entry); const provider = new LocalReferenceSkillProvider(entries); const out = await planFrontendProductSurface(FX_POS_001, { baseDefinition: frontendSurfaceHost, skillProvider: provider, modelProvider, capabilityProvider }); expect((entries.at(-1)!.descriptor as unknown as Record<string, unknown>).rules).toBeUndefined(); expect(out.skillLoaded).toBe(true); expect(loads).toBe(1); });
  it("T75/T76 real S10 compile and S09 run return a valid decision", async () => { const out = await run(FX_POS_001, true); expect(out.run.outcome).toBe("SUCCESS"); expect(out.materializedDefinition.id).toContain("s13k"); expect(out.decisionValidation.valid).toBe(true); });
  it("T77-T79 provider and frozen truth are isolated from each other and forbidden branches", () => { const providerSource = readFileSync("tests/frontend-product-surface/fixtures.ts", "utf8"), truthSource = readFileSync("tests/frontend-product-surface/fixtureTruth.ts", "utf8"), inputSource = readFileSync("tests/frontend-product-surface/fixtureInputs.ts", "utf8"), imports = `${truthSource}\n${inputSource}`.split("\n").filter((line) => line.startsWith("import ")).join("\n"); expect(DeterministicFrontendSurfaceModelProvider.PROVIDER_LABEL).toMatch(/no frozen truth/); expect(providerSource).not.toMatch(/fixtureTruth|withSkill\s*[=:]|SKILL_ID.*(?:if|switch)|fixture[_-]?id.*(?:if|switch)/i); expect(imports).not.toMatch(/fixtures|Provider|synthesize|parse|gate|compare|evaluate/i); expect(truthSource).not.toMatch(/(?:synthesizeFrontend|gateFrontend|compareFrontend|planFrontend)\s*\(/i); });
  it("T80 exposes 30 genuinely distinct dimensional observation IDs", () => { const observations = extractFrontendSurfaceAssertionObservations(faithful(FX_POS_005)); const ids = FRONTEND_SURFACE_COMPARISON_ASSERTIONS.filter((item) => item.category !== "REGRESSION_CROSS_CUTTING").map((item) => item.id); expect(ids).toHaveLength(30); expect(new Set(ids).size).toBe(30); expect(ids.every((id) => Object.hasOwn(observations, id))).toBe(true); const extractorSource = readFileSync(join(sourceDir, "compareFrontendProductSurfaceRuns.ts"), "utf8"); for (const id of ids) expect(extractorSource.split(`\"${id}\"`).length - 1).toBe(1); });
});

describe("canonical fixtures, OI-A and boundaries T81-T98", () => {
  it.each(ALL_POSITIVE_INPUTS.map((input, index) => [`T${90 + index} FX-POS-${String(index + 1).padStart(3, "0")}`, input] as const))("%s passes", (_name, input) => expect(validateFrontendProductSurfaceDecision(faithful(input), input).valid).toBe(true));
  it.each(ALL_NEGATIVE_FIXTURES)("T96 $id blocks/rejects", ({ input, decision }) => expect(gateFrontendProductSurface(input, decision).decision.status).toBe("BLOCKED"));
  it("T81-T89 raw grouped contributions meet every OI-A threshold and safety counter", async () => { const baseline = [], skill = []; for (const input of ALL_POSITIVE_INPUTS) { const b = await run(input, false), s = await run(input, true); baseline.push({ input, candidateDecision: b.candidate }); skill.push({ input, candidateDecision: s.candidate }); } const comparison = compareFrontendProductSurfaceRuns(baseline, skill, FROZEN_FRONTEND_SURFACE_FIXTURE_TRUTH); expect(comparison.skill.hard_invariant_correct).toBe(comparison.skill.hard_invariant_total); expect(comparison.skill).toMatchObject({ dead_end_required_flows: 0, missing_required_state_mappings: 0, unsafe_retry_duplicate_destructive_recommendations: 0, fabricated_api_auth_policy_states: 0, framework_browser_provider_future_stage_bindings: 0 }); expect(comparison.dimension_specific_total_delta).toBeGreaterThanOrEqual(14); expect(comparison.improved_dimensions.length).toBeGreaterThanOrEqual(5); for (const dimension of comparison.improved_dimensions) { const item = comparison.dimension_improvements[dimension]; expect(item.scored_assertions).toBeGreaterThanOrEqual(3); expect(Object.keys(item.single_assertion_contributions)).toHaveLength(3); expect(Object.values(item.single_assertion_contributions).filter((count) => count > 0).length).toBeGreaterThanOrEqual(2); expect(item.max_single_assertion_share).toBeLessThanOrEqual(0.5); } expect(comparison.hard_invariant_regressed).toBe(false); expect(comparison.meets_threshold).toBe(true); });
  it("T97/T98 manifests/Core/Part A/boundaries remain untouched and catalog append-only", () => { expect(referenceSkillCatalogEntries.length).toBeGreaterThanOrEqual(14); expect(referenceSkillCatalogEntries[12].descriptor.id).toBe("intelligence.postgres-data-modeling.s13j"); expect(referenceSkillCatalogEntries[13].descriptor.id).toBe(FRONTEND_PRODUCT_SURFACE_SKILL_ID); const pkg = JSON.parse(readFileSync("package.json", "utf8")); expect(pkg.dependencies).toEqual({ "better-sqlite3": "^13.0.3" }); const source = readdirSync(sourceDir).filter((name) => name.endsWith(".ts")).map((name) => readFileSync(join(sourceDir, name), "utf8")).join("\n"); expect(source).not.toMatch(/from ["'](?:react|vue|svelte|angular|playwright|puppeteer|express|hono|auth0|okta)|document\.|window\.|createServer|setTimeout\(|fetch\(/); expect(readdirSync("src/intelligence").some((name) => /observability-ai|delivery-documentation|deployment|capability-registry/i.test(name))).toBe(false); });
});

class CorruptParsedCandidateProvider implements ModelProvider { constructor(private readonly inner: DeterministicFrontendSurfaceModelProvider) {} async decide(request: ModelDecisionRequest): Promise<ModelDecisionResult> { const result = await this.inner.decide(request); if (result.status !== "SUCCESS" || result.decision.type !== "FINISH") return result; const candidate = result.decision.output.data as unknown as FrontendProductSurfaceDecision; candidate.flow_graph.edges = []; candidate.surfaces[0].source_refs.push("marker:parsed-corrupt-candidate"); candidate.status = "READY"; return result; } }
describe("actual parsed candidate regression", () => { it("parsed corrupt candidate cannot be substituted before gate", async () => { const out = await planFrontendProductSurface(FX_POS_001, { baseDefinition: frontendSurfaceHost, skillProvider, modelProvider: new CorruptParsedCandidateProvider(modelProvider), capabilityProvider }); expect(out.candidate.surfaces[0].source_refs).toContain("marker:parsed-corrupt-candidate"); expect(out.decision.surfaces[0].source_refs).toContain("marker:parsed-corrupt-candidate"); expect(out.decision.status).toBe("BLOCKED"); }); });
