export const POSTGRES_DATA_MODELING_SKILL_ID = "intelligence.postgres-data-modeling.s13j";
export const POSTGRES_DATA_MODELING_QUALITY_CONTRACT_REF = "S13J_POSTGRES_DATA_MODELING_DEEP";
export const POSTGRES_DATA_MODELING_INPUT_MARKER = "BRAIN_S13J_POSTGRES_DATA_MODELING_INPUT:";
export const POSTGRES_DATA_MODELING_SKILL_MARKER = "BRAIN_S13J_POSTGRES_DATA_MODELING_SKILL_RULES:";
export const SAFE_IDENTIFIER = /^[a-z][a-z0-9_]{0,62}$/;
