import type { PostgresInspectOperation } from "./types.js";

export const BEGIN_READ_ONLY = "BEGIN TRANSACTION READ ONLY";
export const VERIFY_READ_ONLY = "SELECT pg_catalog.current_setting('transaction_read_only') AS transaction_read_only";
export const ROLLBACK = "ROLLBACK";

export const POSTGRES_INSPECTION_QUERIES: Readonly<Record<PostgresInspectOperation,string>> = Object.freeze({
  server: "SELECT pg_catalog.current_setting('server_version') AS server_version, pg_catalog.current_setting('server_version_num') AS server_version_num ORDER BY server_version, server_version_num LIMIT $1",
  schemas: "SELECT n.nspname AS schema FROM pg_catalog.pg_namespace AS n WHERE n.nspname = ANY($1::text[]) ORDER BY schema LIMIT $2",
  tables: "SELECT n.nspname AS schema, c.relname AS \"table\", CASE c.relkind WHEN 'r' THEN 'table' WHEN 'p' THEN 'partitioned_table' WHEN 'v' THEN 'view' WHEN 'm' THEN 'materialized_view' WHEN 'f' THEN 'foreign_table' END AS kind FROM pg_catalog.pg_class AS c JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace WHERE n.nspname = ANY($1::text[]) AND ($2::text IS NULL OR n.nspname = $2) AND c.relkind IN ('r','p','v','m','f') ORDER BY schema, \"table\", kind LIMIT $3",
  columns: "SELECT n.nspname AS schema, c.relname AS \"table\", a.attname AS \"column\", a.attnum AS ordinal_position, pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type, NOT a.attnotnull AS nullable, a.atthasdef AS has_default, a.attgenerated <> '' AS generated FROM pg_catalog.pg_attribute AS a JOIN pg_catalog.pg_class AS c ON c.oid = a.attrelid JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace WHERE n.nspname = $1 AND c.relname = $2 AND c.relkind IN ('r','p','v','m','f') AND a.attnum > 0 AND NOT a.attisdropped ORDER BY schema, \"table\", ordinal_position, \"column\" LIMIT $3",
  indexes: "SELECT n.nspname AS schema, t.relname AS \"table\", x.relname AS index, i.indisunique AS \"unique\", i.indisprimary AS \"primary\", COALESCE((array_agg(a.attname ORDER BY k.ordinality) FILTER (WHERE a.attname IS NOT NULL))::text[], ARRAY[]::text[]) AS columns, COALESCE(bool_or(k.attnum = 0), false) AS expression_index FROM pg_catalog.pg_index AS i JOIN pg_catalog.pg_class AS t ON t.oid = i.indrelid JOIN pg_catalog.pg_namespace AS n ON n.oid = t.relnamespace JOIN pg_catalog.pg_class AS x ON x.oid = i.indexrelid LEFT JOIN LATERAL unnest(i.indkey) WITH ORDINALITY AS k(attnum, ordinality) ON true LEFT JOIN pg_catalog.pg_attribute AS a ON a.attrelid = t.oid AND a.attnum = k.attnum WHERE n.nspname = $1 AND t.relname = $2 GROUP BY n.nspname, t.relname, x.relname, i.indisunique, i.indisprimary ORDER BY schema, \"table\", index LIMIT $3",
  constraints: "SELECT n.nspname AS schema, t.relname AS \"table\", c.conname AS \"constraint\", CASE c.contype WHEN 'p' THEN 'primary_key' WHEN 'u' THEN 'unique' WHEN 'f' THEN 'foreign_key' WHEN 'c' THEN 'check' WHEN 'x' THEN 'exclusion' END AS type, COALESCE(cols.names::text[], ARRAY[]::text[]) AS columns, rn.nspname AS referenced_schema, rt.relname AS referenced_table, refs.names::text[] AS referenced_columns, c.condeferrable AS deferrable, c.condeferred AS initially_deferred FROM pg_catalog.pg_constraint AS c JOIN pg_catalog.pg_class AS t ON t.oid = c.conrelid JOIN pg_catalog.pg_namespace AS n ON n.oid = t.relnamespace LEFT JOIN pg_catalog.pg_class AS rt ON rt.oid = c.confrelid LEFT JOIN pg_catalog.pg_namespace AS rn ON rn.oid = rt.relnamespace LEFT JOIN LATERAL (SELECT array_agg(a.attname ORDER BY k.ordinality) AS names FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ordinality) JOIN pg_catalog.pg_attribute AS a ON a.attrelid = t.oid AND a.attnum = k.attnum) AS cols ON true LEFT JOIN LATERAL (SELECT array_agg(a.attname ORDER BY k.ordinality) AS names FROM unnest(c.confkey) WITH ORDINALITY AS k(attnum, ordinality) JOIN pg_catalog.pg_attribute AS a ON a.attrelid = rt.oid AND a.attnum = k.attnum) AS refs ON true WHERE n.nspname = $1 AND t.relname = $2 AND c.contype IN ('p','u','f','c','x') ORDER BY schema, \"table\", \"constraint\" LIMIT $3",
});

export const ALL_PRODUCTION_SQL = Object.freeze([BEGIN_READ_ONLY, VERIFY_READ_ONLY, ...Object.values(POSTGRES_INSPECTION_QUERIES), ROLLBACK]);
