import { afterEach,describe,expect,it } from "vitest";
import { Client } from "pg";
import { attachPgIdleErrorGuard } from "../../src/providers/capability/postgres/pgClientFactory.js";
import { FakeClientFactory,harness,material,request } from "./helpers.js";

const ENV_KEYS=["PGHOST","PGPORT","PGDATABASE","PGUSER","PGPASSWORD","PGSSLMODE","PGOPTIONS","PGSSLNEGOTIATION","PGCLIENT_ENCODING","PGREPLICATION"] as const;
const original=new Map<string,string|undefined>();
afterEach(()=>{for(const key of ENV_KEYS){const value=original.get(key);if(value===undefined)delete process.env[key];else process.env[key]=value;}original.clear();});

describe("S14H pg environment and idle-error regressions",()=>{
  it("hostile libpq environment fallback cannot override provider-owned Client parameters",async()=>{for(const key of ENV_KEYS)original.set(key,process.env[key]);try{Object.assign(process.env,{PGHOST:"hostile.invalid",PGPORT:"6543",PGDATABASE:"HOSTILE_DATABASE",PGUSER:"HOSTILE_USER",PGPASSWORD:"HOSTILE_PASSWORD",PGSSLMODE:"verify-full",PGOPTIONS:"-c search_path=HOSTILE",PGSSLNEGOTIATION:"direct",PGCLIENT_ENCODING:"LATIN1",PGREPLICATION:"database"});const factory=new FakeClientFactory();await harness(factory).provider.invoke(request({operation:"server"}));const captured=factory.options[0];const password=captured.password as unknown as ()=>string|Promise<string>;const client=new Client(captured) as Client&{password:unknown;replication:string;connectionParameters:{options:string;password:unknown;client_encoding:string;replication:string};sslNegotiation:string;getStartupConf():{replication?:string}};expect(client.host).toBe(material().host);expect(client.port).toBe(material().port);expect(client.database).toBe(material().database);expect(client.user).toBe(material().user);expect(typeof captured.password).toBe("function");expect(await password()).toBe(material().password);expect(client.password).toBe(captured.password);expect(client.ssl).toBe(false);expect(client.connectionParameters.options).toBe("-c default_transaction_read_only=on");expect(client.sslNegotiation).toBe("postgres");expect(client.connectionParameters.client_encoding).toBe("UTF8");expect(client.replication).toBe("false");expect(client.connectionParameters.replication).toBe("false");expect(client.getStartupConf().replication).toBe("false");expect(client.connectionParameters.password).toBe(captured.password);}finally{for(const key of ENV_KEYS){const value=original.get(key);if(value===undefined)delete process.env[key];else process.env[key]=value;}original.clear();}});
  it("empty resolved password remains authoritative and makes PGPASSWORD and pgpass unreachable",async()=>{for(const key of ENV_KEYS)original.set(key,process.env[key]);try{Object.assign(process.env,{PGPASSWORD:"HOSTILE_PASSWORD",PGCLIENT_ENCODING:"LATIN1",PGREPLICATION:"database"});const factory=new FakeClientFactory();await harness(factory,{resolve:async()=>material({password:""})}).provider.invoke(request({operation:"server"}));const captured=factory.options[0];const password=captured.password as unknown as ()=>string|Promise<string>;const client=new Client(captured) as Client&{password:unknown;connectionParameters:{client_encoding:string;replication:string};getStartupConf():{replication?:string}};expect(typeof captured.password).toBe("function");expect(await password()).toBe("");expect(client.password).toBe(captured.password);expect(client.password).not.toBe(null);expect(client.password).not.toBe(process.env.PGPASSWORD);expect(client.connectionParameters.client_encoding).toBe("UTF8");expect(client.connectionParameters.replication).toBe("false");expect(client.getStartupConf().replication).toBe("false");}finally{for(const key of ENV_KEYS){const value=original.get(key);if(value===undefined)delete process.env[key];else process.env[key]=value;}original.clear();}});
  it("real pg Client idle error guard consumes raw errors and stores boolean-only state",()=>{const client=new Client({host:"127.0.0.1",ssl:false});const state=attachPgIdleErrorGuard(client);const uncaught:unknown[]=[];const spy=(error:unknown)=>uncaught.push(error);process.on("uncaughtException",spy);const sentinel=Object.assign(new Error("S14H_IDLE_SENTINEL_MESSAGE"),{detail:"S14H_IDLE_SENTINEL_DETAIL"});try{expect(()=>client.emit("error",sentinel)).not.toThrow();expect(state).toEqual({fatal:true});expect(JSON.stringify(state)).not.toContain("S14H_IDLE_SENTINEL");expect(uncaught).toEqual([]);}finally{process.off("uncaughtException",spy);}});
  it("provider cannot resurrect SUCCESS after a fatal idle client error",async()=>{const raw="S14H_IDLE_SENTINEL_PROVIDER";const uncaught:unknown[]=[];const unhandled:unknown[]=[];const onUncaught=(e:unknown)=>uncaught.push(e);const onUnhandled=(e:unknown)=>unhandled.push(e);process.on("uncaughtException",onUncaught);process.on("unhandledRejection",onUnhandled);try{const factory=new FakeClientFactory({select:{idleError:Object.assign(new Error(raw),{detail:`${raw}_DETAIL`})}});const result=await harness(factory).provider.invoke(request({operation:"server"}));expect(result).toMatchObject({status:"FAIL",error:{code:"UNAVAILABLE",retryable:true}});expect(JSON.stringify(result)).not.toContain(raw);expect(factory.clients[0].log).toEqual(["connect","begin","verify","select","rollback","end"]);await Promise.resolve();expect(uncaught).toEqual([]);expect(unhandled).toEqual([]);}finally{process.off("uncaughtException",onUncaught);process.off("unhandledRejection",onUnhandled);}});
});
