import { afterEach,describe,expect,it } from "vitest";
import { Client } from "pg";
import { attachPgIdleErrorGuard } from "../../src/providers/capability/postgres/pgClientFactory.js";
import { FakeClientFactory,harness,material,request } from "./helpers.js";

const ENV_KEYS=["PGHOST","PGPORT","PGDATABASE","PGUSER","PGPASSWORD","PGSSLMODE","PGOPTIONS","PGSSLNEGOTIATION"] as const;
const original=new Map<string,string|undefined>();
afterEach(()=>{for(const key of ENV_KEYS){const value=original.get(key);if(value===undefined)delete process.env[key];else process.env[key]=value;}original.clear();});

describe("S14H pg environment and idle-error regressions",()=>{
  it("hostile libpq environment fallback cannot override provider-owned Client parameters",async()=>{for(const key of ENV_KEYS)original.set(key,process.env[key]);Object.assign(process.env,{PGHOST:"hostile.invalid",PGPORT:"6543",PGDATABASE:"HOSTILE_DATABASE",PGUSER:"HOSTILE_USER",PGPASSWORD:"HOSTILE_PASSWORD",PGSSLMODE:"verify-full",PGOPTIONS:"-c search_path=HOSTILE",PGSSLNEGOTIATION:"direct"});const factory=new FakeClientFactory();await harness(factory).provider.invoke(request({operation:"server"}));const captured=factory.options[0];const client=new Client(captured) as Client&{connectionParameters:{options:string};sslNegotiation:string};expect(client.host).toBe(material().host);expect(client.port).toBe(material().port);expect(client.database).toBe(material().database);expect(client.user).toBe(material().user);expect(client.password).toBe(material().password);expect(client.ssl).toBe(false);expect(client.connectionParameters.options).toBe("-c default_transaction_read_only=on");expect(client.sslNegotiation).toBe("postgres");});
  it("real pg Client idle error guard consumes raw errors and stores boolean-only state",()=>{const client=new Client({host:"127.0.0.1",ssl:false});const state=attachPgIdleErrorGuard(client);const uncaught:unknown[]=[];const spy=(error:unknown)=>uncaught.push(error);process.on("uncaughtException",spy);const sentinel=Object.assign(new Error("S14H_IDLE_SENTINEL_MESSAGE"),{detail:"S14H_IDLE_SENTINEL_DETAIL"});try{expect(()=>client.emit("error",sentinel)).not.toThrow();expect(state).toEqual({fatal:true});expect(JSON.stringify(state)).not.toContain("S14H_IDLE_SENTINEL");expect(uncaught).toEqual([]);}finally{process.off("uncaughtException",spy);}});
  it("provider cannot resurrect SUCCESS after a fatal idle client error",async()=>{const raw="S14H_IDLE_SENTINEL_PROVIDER";const uncaught:unknown[]=[];const unhandled:unknown[]=[];const onUncaught=(e:unknown)=>uncaught.push(e);const onUnhandled=(e:unknown)=>unhandled.push(e);process.on("uncaughtException",onUncaught);process.on("unhandledRejection",onUnhandled);try{const factory=new FakeClientFactory({select:{idleError:Object.assign(new Error(raw),{detail:`${raw}_DETAIL`})}});const result=await harness(factory).provider.invoke(request({operation:"server"}));expect(result).toMatchObject({status:"FAIL",error:{code:"UNAVAILABLE",retryable:true}});expect(JSON.stringify(result)).not.toContain(raw);expect(factory.clients[0].log).toEqual(["connect","begin","verify","select","rollback","end"]);await Promise.resolve();expect(uncaught).toEqual([]);expect(unhandled).toEqual([]);}finally{process.off("uncaughtException",onUncaught);process.off("unhandledRejection",onUnhandled);}});
});
