import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
import { ALL_PRODUCTION_SQL,PgPostgresInspectProvider,POSTGRES_INSPECTION_QUERIES,descriptorsFor } from "../../src/providers/capability/postgres/index.js";
import { RestrictedCapabilityProvider } from "../../src/core/agent/restrictedCapabilityProvider.js";
import { CompatiblePostgresInspectTestProvider,DEFINITION_BYTES,FakeClientFactory,SECRET,agentExec,assertCompatibleContracts,baseConfig,definition,fail,harness,material,request,success } from "./helpers.js";
import { productionSources } from "./audit.js";

const checks:Array<[string,string,()=>unknown|Promise<unknown>]>=[
 ["S14H-HI-001","Exactly postgres.inspect is advertised and EXTERNAL",()=>expect(descriptorsFor().map(d=>[d.capability_id,d.side_effects])).toEqual([["postgres.inspect","EXTERNAL"]])],
 ["S14H-HI-002","Core Registry and prior protected surfaces are not imported for mutation",()=>expect(productionSources()).not.toMatch(/writeFile|src\/core/)],
 ["S14H-HI-003","vendor and connection identity do not enter capability identity",()=>expect(JSON.stringify(descriptorsFor())).not.toMatch(/qa\.pg|pg\.Client|connection_ref|password/)],
 ["S14H-HI-004","input schema is closed to operation schema table",()=>expect((descriptorsFor()[0].input_schema as any).properties).toEqual(expect.objectContaining({operation:expect.anything(),schema:expect.anything(),table:expect.anything()}))],
 ["S14H-HI-005","operation matrix is pre-resolver",async()=>{const h=harness();fail(await h.provider.invoke(request({operation:"indexes"})),"INVALID_INPUT");expect(h.factory.creates).toBe(0)}],
 ["S14H-HI-006","schema allowlist and system rejection",()=>expect(()=>new PgPostgresInspectProvider(baseConfig({allowed_schemas:["pg_toast"]}))).toThrow()],
 ["S14H-HI-007","connection ref and material remain private",async()=>expect(JSON.stringify(success(await harness().provider.invoke(request({operation:"server"}))))).not.toContain("secret://")],
 ["S14H-HI-008","resolver deadline contains hangs",async()=>fail(await harness(new FakeClientFactory(),{resolve:()=>new Promise(()=>undefined)},baseConfig({max_timeout_ms:10})).provider.invoke(request({operation:"server"},10)),"TIMEOUT")],
 ["S14H-HI-009","material is bounded and remote TLS enforced",async()=>fail(await harness(new FakeClientFactory(),{resolve:async()=>material({host:"remote"})}).provider.invoke(request({operation:"server"})),"PERMISSION_DENIED")],
 ["S14H-HI-010","fresh Client per invocation no pool",async()=>{const h=harness();await h.provider.invoke(request({operation:"server"}));await h.provider.invoke(request({operation:"server"}));expect(h.factory.creates).toBe(2);expect(productionSources()).not.toMatch(/new Pool|pg-native/)}],
 ["S14H-HI-011","all Client connection fields explicit",async()=>{const h=harness();await h.provider.invoke(request({operation:"server"}));expect(Object.keys(h.factory.options[0]).sort()).toEqual(["application_name","connectionTimeoutMillis","database","host","keepAlive","options","password","pipeline","port","query_timeout","ssl","sslnegotiation","statement_timeout","user"].sort())}],
 ["S14H-HI-012","dependency pins exact",()=>{const p=JSON.parse(readFileSync("package.json","utf8"));expect([p.dependencies.pg,p.devDependencies["@types/pg"]]).toEqual(["8.23.0","8.23.1"])}],
 ["S14H-HI-013","SQL is a closed fixed registry",()=>expect(Object.keys(POSTGRES_INSPECTION_QUERIES)).toEqual(["server","schemas","tables","columns","indexes","constraints"])],
 ["S14H-HI-014","model identifiers are values only",async()=>{const h=harness();await h.provider.invoke(request({operation:"columns",schema:"app",table:"a"}));expect(h.factory.clients[0].queries.at(-2)).toMatchObject({text:POSTGRES_INSPECTION_QUERIES.columns,values:["app","a",21]})}],
 ["S14H-HI-015","BEGIN READ ONLY precedes inspection",async()=>{const h=harness();await h.provider.invoke(request({operation:"server"}));expect(h.factory.clients[0].log.slice(0,4)).toEqual(["connect","begin","verify","select"])}],
 ["S14H-HI-016","read-only state is verified",()=>expect(ALL_PRODUCTION_SQL[1]).toContain("transaction_read_only")],
 ["S14H-HI-017","command classes are only begin select rollback",()=>ALL_PRODUCTION_SQL.forEach(sql=>expect(sql).toMatch(/^(?:BEGIN TRANSACTION READ ONLY|SELECT|ROLLBACK)/))],
 ["S14H-HI-018","no user table rows are queried",()=>expect(ALL_PRODUCTION_SQL.join(" ")).not.toMatch(/FROM\s+(?:app|brain_s14h_smoke)\./i)],
 ["S14H-HI-019","catalog scope excludes sensitive catalogs",()=>expect(ALL_PRODUCTION_SQL.join(" ")).not.toMatch(/pg_(?:auth|roles|shadow|user|settings|stat_)/i)],
 ["S14H-HI-020","outputs are closed normalized records",async()=>{const o=success(await harness().provider.invoke(request({operation:"server"})));expect(Object.keys((o.items as Record<string,unknown>[])[0])).toEqual(["server_version","server_version_num"])}],
 ["S14H-HI-021","results ordered bounded and truncated",async()=>{const f=new FakeClientFactory({}, {schemas:[{schema:"z"},{schema:"a"}]});const o=success(await harness(f,undefined,baseConfig({max_rows:1})).provider.invoke(request({operation:"schemas"})));expect([o.items,o.truncated]).toEqual([[{schema:"a"}],true])}],
 ["S14H-HI-022","output overflow is atomic",async()=>{const f=new FakeClientFactory({}, {schemas:Array.from({length:100},(_,i)=>({schema:`${i}${"x".repeat(60)}`}))});fail(await harness(f,undefined,baseConfig({max_rows:100,max_output_bytes:4096})).provider.invoke(request({operation:"schemas"})),"EXECUTION_FAILED")}],
 ["S14H-HI-023","secret and raw error fields do not leak",async()=>{const f=new FakeClientFactory({connect:Object.assign(new Error(SECRET),{code:"28P01",detail:SECRET})});const r=await harness(f).provider.invoke(request({operation:"server"}));expect(JSON.stringify(r)).not.toContain(SECRET)}],
 ["S14H-HI-024","errors use safe existing Brain codes",async()=>fail(await harness(new FakeClientFactory({connect:Object.assign(new Error("x"),{code:"ENOTFOUND"})})).provider.invoke(request({operation:"server"})),"UNAVAILABLE",true)],
 ["S14H-HI-025","one monotonic deadline covers all work",async()=>{const f=new FakeClientFactory({connect:{delay:8},select:"never"});fail(await harness(f,undefined,baseConfig({max_timeout_ms:15})).provider.invoke(request({operation:"server"},15)),"TIMEOUT")}],
 ["S14H-HI-026","rollback then end cleanup is bounded",async()=>{const f=new FakeClientFactory({rollback:"never"});await harness(f,undefined,baseConfig({max_timeout_ms:15})).provider.invoke(request({operation:"server"},15));expect(f.clients[0].log.slice(-2)).toEqual(["rollback","end"])}],
 ["S14H-HI-027","late settlements are contained",async()=>{const r=await harness(new FakeClientFactory({select:{delay:30,reject:true}}),undefined,baseConfig({max_timeout_ms:5})).provider.invoke(request({operation:"server"},5));fail(r,"TIMEOUT")}],
 ["S14H-HI-028","Restricted denial precedes resolver network",async()=>{const h=harness();const p=new RestrictedCapabilityProvider(h.provider,new Set(),new Set());expect((await p.invoke(request({operation:"server"}))).status).toBe("BLOCKED");expect(h.factory.creates).toBe(0)}],
 ["S14H-HI-029","Compatible provider swap works through Registry Restricted and runAgent with identical AgentDefinition bytes",async()=>{const h=harness();const alt=new CompatiblePostgresInspectTestProvider();await assertCompatibleContracts(h.provider,alt);const bytes=JSON.stringify(definition);expect(bytes).toBe(DEFINITION_BYTES);const real=await agentExec(h.provider,{operation:"server"},definition,"selected-real");expect(JSON.stringify(definition)).toBe(DEFINITION_BYTES);const compatible=await agentExec(alt,{operation:"server"},definition,"selected-compatible");expect(JSON.stringify(definition)).toBe(DEFINITION_BYTES);expect([real.outcome,compatible.outcome]).toEqual(["SUCCESS","SUCCESS"]);expect(h.factory.creates).toBe(1);expect(alt.invokeCallCount).toBe(1);expect(Object.keys(real.output!.data!).sort()).toEqual(Object.keys(compatible.output!.data!).sort())}],
 ["S14H-HI-030","canonical deterministic tests require no shared database",()=>{expect(material().host).toBe("127.0.0.1");expect(readFileSync("tests/postgres-capability/realPostgresSmoke.test.ts","utf8")).toContain("describe.skipIf(!enabled)")}],
 ["S14H-HI-032","Part A state future phase and honor remain untouched",()=>expect(productionSources()).not.toMatch(/STATE\.yaml|CURRENT\.md|S14I\s*=|HI-054\s*:\s*AWARDED/)],
];
describe("S14H hard invariants",()=>{for(const [id,name,fn] of checks)it(`${id}: ${name}`,fn);});
