import { describe,expect,it } from "vitest";
import { RestrictedCapabilityProvider,runAgent,type ModelProvider } from "../../src/core/agent/index.js";
import { CapabilityRegistryProvider } from "../../src/providers/capability/registry/capabilityRegistryProvider.js";
import { descriptorsFor,POSTGRES_INSPECT } from "../../src/providers/capability/postgres/index.js";
import { CompatiblePostgresInspectTestProvider,DEFINITION_BYTES,FakeClientFactory,agentExec,assertCompatibleContracts,baseConfig,definition,harness,request,success } from "./helpers.js";

describe("S14H canonical positive fixtures",()=>{
 it("FX-POS-001 Exact deterministic postgres.inspect descriptor and EXTERNAL classification",async()=>{expect(descriptorsFor()).toEqual(descriptorsFor());expect(descriptorsFor()[0]).toMatchObject({capability_id:POSTGRES_INSPECT,side_effects:"EXTERNAL",input_schema:{additionalProperties:false}});});
 it("FX-POS-002 server returns only safe version metadata through a read-only transaction",async()=>{const h=harness();const o=success(await h.provider.invoke(request({operation:"server"})));expect(o.items).toEqual([{server_version:"16.4",server_version_num:"160004"}]);expect(h.factory.clients[0].log).toEqual(["connect","begin","verify","select","rollback","end"]);});
 it("FX-POS-003 schemas returns only existing configured allowed schemas in deterministic order",async()=>{const o=success(await harness().provider.invoke(request({operation:"schemas"})));expect(o.items).toEqual([{schema:"app"},{schema:"brain_s14h_smoke"}]);});
 it("FX-POS-004 tables across configured schemas returns bounded normalized relation metadata",async()=>{const o=success(await harness().provider.invoke(request({operation:"tables"})));expect(o.items).toEqual([{schema:"app",table:"a",kind:"table"},{schema:"app",table:"z",kind:"view"}]);});
 it("FX-POS-005 tables scoped to one allowed schema returns only that schema",async()=>{const h=harness();success(await h.provider.invoke(request({operation:"tables",schema:"app"})));expect(h.factory.clients[0].queries.at(-2)).toMatchObject({values:[["brain_s14h_smoke","app"],"app",21]});});
 it("FX-POS-006 columns returns normalized metadata without default expression",async()=>{const o=success(await harness().provider.invoke(request({operation:"columns",schema:"app",table:"a"})));expect(o.items).toEqual([{schema:"app",table:"a",column:"id",ordinal_position:1,data_type:"integer",nullable:false,has_default:true,generated:false}]);expect(JSON.stringify(o)).not.toContain("nextval");});
 it("FX-POS-007 indexes returns normalized metadata without raw index SQL",async()=>{const o=success(await harness().provider.invoke(request({operation:"indexes",schema:"app",table:"a"})));expect(o.items).toEqual([{schema:"app",table:"a",index:"a_expr_idx",unique:false,primary:false,columns:[],expression_index:true}]);expect(JSON.stringify(o)).not.toContain("CREATE INDEX");});
 it("FX-POS-008 constraints returns normalized reference metadata without expressions",async()=>{const o=success(await harness().provider.invoke(request({operation:"constraints",schema:"app",table:"a"})));expect(o.items).toEqual([{schema:"app",table:"a",constraint:"a_pkey",type:"primary_key",columns:["id"],deferrable:false,initially_deferred:false}]);});
 it("FX-POS-009 max_rows plus one detection returns deterministic first max_rows and truncated true",async()=>{const f=new FakeClientFactory({}, {schemas:[{schema:"c"},{schema:"a"},{schema:"b"}]});const h=harness(f,undefined,baseConfig({max_rows:2}));const o=success(await h.provider.invoke(request({operation:"schemas"})));expect(o.items).toEqual([{schema:"a"},{schema:"b"}]);expect(o.truncated).toBe(true);});
 it("FX-POS-010 Actual Registry plus Restricted plus runAgent executes allowed postgres.inspect",async()=>{const inner=harness().provider;const registry=new CapabilityRegistryProvider({providers:[{provider_id:"pg",provider:inner}],bindings:[{capability_id:POSTGRES_INSPECT,selected_provider_id:"pg"}]});const restricted=new RestrictedCapabilityProvider(registry,new Set([POSTGRES_INSPECT]),new Set(["EXTERNAL"]));let turn=0;const model:ModelProvider={decide:async()=>turn++===0?{status:"SUCCESS",decision:{type:"TOOL_CALL",rationale:"inspect",tool_call:{call_id:"x",capability_id:POSTGRES_INSPECT,input:{operation:"server"}}}}:{status:"SUCCESS",decision:{type:"FINISH",rationale:"done",output:{summary:"done"}}}};const r=await runAgent({modelProvider:model,capabilityProvider:restricted,goal:"inspect",limits:{max_turns:2,timeout_ms:5000},runId:"s14h"});expect(r.outcome).toBe("SUCCESS");expect(r.events.some(e=>e.type==="TOOL_COMPLETED")).toBe(true);});
 it("FX-POS-011 Compatible alternate provider executes same semantic request with identical AgentDefinition bytes",async()=>{const h=harness();const alt=new CompatiblePostgresInspectTestProvider();await assertCompatibleContracts(h.provider,alt);expect(JSON.stringify(definition)).toBe(DEFINITION_BYTES);const first=await agentExec(h.provider,{operation:"server"},definition,"postgres-pg");expect(JSON.stringify(definition)).toBe(DEFINITION_BYTES);const second=await agentExec(alt,{operation:"server"},definition,"compatible-test");expect(JSON.stringify(definition)).toBe(DEFINITION_BYTES);expect([first.outcome,second.outcome]).toEqual(["SUCCESS","SUCCESS"]);expect(h.factory.creates).toBeGreaterThanOrEqual(1);expect(alt.invokeCallCount).toBe(1);expect(Object.keys(first.output!.data!).sort()).toEqual(Object.keys(second.output!.data!).sort());expect(DEFINITION_BYTES).not.toMatch(/127\.0\.0\.1|secret:\/\/|password|postgres-pg|compatible-test/);});
});
