import { describe,expect,it } from "vitest";
import { RestrictedCapabilityProvider,runAgent,type CapabilityProvider,type ModelProvider } from "../../src/core/agent/index.js";
import { CapabilityRegistryProvider } from "../../src/providers/capability/registry/capabilityRegistryProvider.js";
import { descriptorsFor,POSTGRES_INSPECT } from "../../src/providers/capability/postgres/index.js";
import { FakeClientFactory,baseConfig,harness,request,success } from "./helpers.js";

describe("S14H canonical positive fixtures",()=>{
 it("FX-POS-001 Exact deterministic postgres.inspect descriptor and EXTERNAL classification",async()=>{expect(descriptorsFor()).toEqual(descriptorsFor());expect(descriptorsFor()[0]).toMatchObject({capability_id:POSTGRES_INSPECT,side_effects:"EXTERNAL",input_schema:{additionalProperties:false}});});
 it("FX-POS-002 server returns only safe version metadata through a read-only transaction",async()=>{const h=harness();const o=success(await h.provider.invoke(request({operation:"server"})));expect(o.items).toEqual([{server_version:"16.4",server_version_num:"160004"}]);expect(h.factory.clients[0].log).toEqual(["connect","begin","verify","select","rollback","end"]);});
 it("FX-POS-003 schemas returns only existing configured allowed schemas in deterministic order",async()=>{const o=success(await harness().provider.invoke(request({operation:"schemas"})));expect(o.items).toEqual([{schema:"app"},{schema:"brain_s14h_smoke"}]);});
 it("FX-POS-004 tables across configured schemas returns bounded normalized relation metadata",async()=>{const o=success(await harness().provider.invoke(request({operation:"tables"})));expect(o.items).toEqual([{schema:"app",table:"a",kind:"table"},{schema:"app",table:"z",kind:"view"}]);});
 it("FX-POS-005 tables scoped to one allowed schema returns only that schema",async()=>{const h=harness();success(await h.provider.invoke(request({operation:"tables",schema:"app"})));expect(h.factory.clients[0].queries.at(-2)).toMatchObject({values:[["brain_s14h_smoke","app"],"app",21]});});
 it("FX-POS-006 columns returns normalized metadata without default expression",async()=>{const o=success(await harness().provider.invoke(request({operation:"columns",schema:"app",table:"a"})));expect(o.items).toEqual([{schema:"app",table:"a",column:"id",ordinal_position:1,data_type:"integer",nullable:false,has_default:true,generated:false}]);expect(JSON.stringify(o)).not.toContain("nextval");});
 it("FX-POS-007 indexes returns normalized metadata without raw index SQL",async()=>{const o=success(await harness().provider.invoke(request({operation:"indexes",schema:"app",table:"a"})));expect(o.items).toEqual([{schema:"app",table:"a",index:"a_expr_idx",unique:false,primary:false,columns:[],expression_index:true}]);expect(JSON.stringify(o)).not.toContain("CREATE INDEX");});
 it("FX-POS-008 constraints returns normalized reference metadata without expressions",async()=>{const o=success(await harness().provider.invoke(request({operation:"constraints",schema:"app",table:"a"})));expect(o.items).toEqual([{schema:"app",table:"a",constraint:"a_pkey",type:"primary_key",columns:["id"],deferrable:false,initially_deferred:false}]);});
 it("FX-POS-009 max_rows plus one detection returns deterministic first max_rows and truncated true",async()=>{const f=new FakeClientFactory({}, {schemas:[{schema:"c"},{schema:"a"},{schema:"b"}]});const h=harness(f,undefined,baseConfig({max_rows:2}));const o=success(await h.provider.invoke(request({operation:"schemas"})));expect(o.items).toEqual([{schema:"a"},{schema:"b"}]);expect(o.truncated).toBe(true);});
 it("FX-POS-010 Actual Registry plus Restricted plus runAgent executes allowed postgres.inspect",async()=>{const inner=harness().provider;const registry=new CapabilityRegistryProvider({providers:[{provider_id:"pg",provider:inner}],bindings:[{capability_id:POSTGRES_INSPECT,selected_provider_id:"pg"}]});const restricted=new RestrictedCapabilityProvider(registry,new Set([POSTGRES_INSPECT]),new Set(["EXTERNAL"]));let turn=0;const model:ModelProvider={decide:async()=>turn++===0?{status:"SUCCESS",decision:{type:"TOOL_CALL",rationale:"inspect",tool_call:{call_id:"x",capability_id:POSTGRES_INSPECT,input:{operation:"server"}}}}:{status:"SUCCESS",decision:{type:"FINISH",rationale:"done",output:{summary:"done"}}}};const r=await runAgent({modelProvider:model,capabilityProvider:restricted,goal:"inspect",limits:{max_turns:2,timeout_ms:5000},runId:"s14h"});expect(r.outcome).toBe("SUCCESS");expect(r.events.some(e=>e.type==="TOOL_COMPLETED")).toBe(true);});
 it("FX-POS-011 Compatible alternate provider executes same semantic request with identical AgentDefinition bytes",async()=>{const definition={tools:[POSTGRES_INSPECT],capabilities:[POSTGRES_INSPECT]};const bytes=JSON.stringify(definition);const alt:CapabilityProvider={list_capabilities:async()=>descriptorsFor(),invoke:async r=>({status:"SUCCESS",call_id:r.call_id,capability_id:r.capability_id,output:{connection_id:"alt",operation:"server",items:[],truncated:false,observed_at:new Date(0).toISOString()},duration_ms:0})};expect((await alt.invoke(request({operation:"server"}))).status).toBe("SUCCESS");expect(JSON.stringify(definition)).toBe(bytes);});
 it.skipIf(process.env.S14H_PG_REAL_SMOKE!=="1")("FX-POS-012 Real disposable local PostgreSQL smoke performs all six operations successfully without row-data access",()=>{expect(process.env.S14H_PG_REAL_SMOKE).toBe("1");});
});
