import type { SkillDefinition } from "../../core/skill/index.js";
import { ASYNC_RELIABILITY_QUALITY_CONTRACT_REF, ASYNC_RELIABILITY_SKILL_ID } from "./constants.js";
export { ASYNC_RELIABILITY_QUALITY_CONTRACT_REF, ASYNC_RELIABILITY_SKILL_ID } from "./constants.js";
const mustRules = [
  "One bounded operation/job subject.", "Decide only; never execute retry, sleep, cancel, enqueue, persist or deduplicate.", "Do not change Core or the S10 AgentDefinition schema.", "Preserve S09 runtime ownership.", "retryable is evidence, never retry authorization.", "Classify observed failures deterministically.", "Observed success is never retried.", "Invalid, auth, policy and permanent failures are never blindly retried.", "Transient, rate-limited and timeout failures remain conditional.", "Dispatch phase controls retry safety.",
  "Ambiguous effectful post-dispatch outcomes require reconciliation.", "Attempt budget is hard.", "Elapsed retry budget is hard.", "Effective deadline is hard.", "Retry-After is a minimum wait, not authorization.", "Use bounded deterministic fixed or exponential backoff.", "Schedule at most one next attempt.", "Read-only replay is safe only after all other eligibility gates pass.", "Idempotent-write replay needs explicit idempotence and stable fingerprint.", "Non-idempotent or external replay needs scoped replay proof.",
  "Never claim exactly-once execution.", "Idempotency evidence is scoped and opaque.", "Reconciliation evidence controls ambiguity resolution.", "Pre-dispatch cancellation may cancel safely.", "Unacknowledged post-dispatch cancellation reconciles.", "Success after cancellation remains truthful success with a race limitation.", "Use only explicit legal async-job transitions.", "Terminal jobs do not reopen for retry.", "Do not claim a durable queue, worker, store or scheduler.", "Keep job and retry state minimal and secret-free.",
  "Preserve authority across attempts.", "Required approval must remain current and matching.", "Retry cannot widen capabilities or side-effect class.", "Never place secret material in reliability state.", "Retry preserves the operation; it is not semantic replanning.", "Consume, but do not re-author, S13L security semantics.", "Do not introduce S13P observability.", "Do not introduce S14 connector, auth or HTTP bindings.", "Do not introduce an S15 verifier agent.", "Remain provider-neutral and dependency-free.",
  "Structural validation is total and fail-closed.", "Inputs are immutable.", "Gate and recompute every actual candidate.", "Derive status and action deterministically.", "Preserve uncertainty as INCONCLUSIVE plus RECONCILE.", "A/B arms use the same path except Skill prose or availability.", "Provider fixtures are packet-derived, never Skill-presence oracles.", "Improvement evidence is distributed across atomic assertions.", "Atomic ownership is source-fact isolated.", "Only fresh independent verification can close S13O."
] as const;

export const asyncReliabilitySkillS13O: SkillDefinition = { id:ASYNC_RELIABILITY_SKILL_ID, version:"1.0.0", description:"Produce one bounded, evidence-grounded reliability decision for an already-observed operation/job attempt without executing retry, queue, network, cancellation or persistence.", applies_when:{task_kinds:["async-reliability","retry-safety","idempotency","backoff"],signals:["retry","timeout","rate limited","idempotency","cancellation","async job"],exclusions:["queue worker","connector binding","telemetry platform","verifier agent"]},inputs:[{name:"async_reliability_input",description:"One bounded AsyncReliabilityInput.",required:true,schema:{type:"object"}}],outputs:[{name:"async_reliability_decision",description:"One deterministic AsyncReliabilityDecision.",required:true,schema:{type:"object"}}],requires:{skills:[],capabilities:[],context_sources:["CURRENT_TASK","APPROVED_SPEC","QUALITY_CONTRACT","AGENT_RUN_RESULT","SECURITY_DECISION","RUNTIME_METADATA"],quality_contract_refs:[ASYNC_RELIABILITY_QUALITY_CONTRACT_REF]},rules:mustRules.map((statement,index)=>({id:`AR-R${index+1}`,level:"MUST" as const,statement})),procedure:[{id:"AR-P1",title:"Validate",instruction:"Validate one bounded AsyncReliabilityInput and exact latest-attempt/job/operation bindings.",requires:["async_reliability_input"],produces:["validated_input"]},{id:"AR-P2",title:"Freeze projections",instruction:"Read only bounded policy, timing, side-effect, authority and evidence projections.",requires:["validated_input"],produces:["frozen_input"]},{id:"AR-P3",title:"Classify",instruction:"Recompute failure class, cancellation precedence, budgets, backoff and replay safety.",requires:["frozen_input"],produces:["evaluated_input"]},{id:"AR-P4",title:"Gate candidate",instruction:"Derive one legal action, validate the actual candidate and return safe evidence only.",requires:["evaluated_input"],produces:["async_reliability_decision"]}],verification:[{id:"AR-V1",kind:"DETERMINISTIC",criterion:"Unsafe effectful replay reconciles.",evidence_required:true},{id:"AR-V2",kind:"DETERMINISTIC",criterion:"Retry obeys budgets and Retry-After.",evidence_required:true},{id:"AR-V3",kind:"DETERMINISTIC",criterion:"Candidate claims are recomputed from the packet.",evidence_required:true}],permissions:{allowed_capabilities:[],allowed_side_effects:["NONE"],deny_unlisted_capabilities:true},evals:["evals/s13o/replay-safety","evals/s13o/retry-budget","evals/s13o/cancellation"]};
