import { ALLOWED_JOB_TRANSITIONS, FORBIDDEN_SENSITIVE_KEY, RETRY_CANDIDATES, TERMINAL_JOB_STATES } from "./constants.js";
import type { AsyncReliabilityDecision, AsyncReliabilityInput, AsyncReliabilityJobState, AsyncReliabilityReasonCode, AsyncReliabilityValidationResult, ReliabilityFailureClass, ReliabilityObservedErrorCode, ReplaySafetyAssessment } from "./types.js";

const strings = (x: unknown): x is string[] => Array.isArray(x) && x.every(v => typeof v === "string" && v.length > 0);
const ref = (x: unknown) => typeof x === "string" && x.length > 0 && !FORBIDDEN_SENSITIVE_KEY.test(x);
const int = (x: unknown) => Number.isSafeInteger(x) && (x as number) >= 0;
const clone = <T>(x:T):T => structuredClone(x);
const sensitive = (x: unknown): boolean => { if (!x || typeof x !== "object") return false; return Object.keys(x as Record<string,unknown>).some(k => FORBIDDEN_SENSITIVE_KEY.test(k)) || Object.values(x as Record<string,unknown>).some(v => typeof v === "object" && sensitive(v)); };

export function classifyReliabilityFailure(attempt: { observed_status: string; error_code?: ReliabilityObservedErrorCode; retryable_hint?: boolean }): ReliabilityFailureClass {
  if (attempt.observed_status === "SUCCESS") return "NONE";
  if (attempt.observed_status === "BLOCKED") return attempt.error_code === "AUTH_REQUIRED" ? "AUTH_REQUIRED" : "POLICY_BLOCKED";
  const map: Partial<Record<ReliabilityObservedErrorCode,ReliabilityFailureClass>> = { RATE_LIMITED:"RATE_LIMITED", TIMEOUT:"TIMEOUT", INVALID_REQUEST:"INVALID_INPUT", INVALID_INPUT:"INVALID_INPUT", AUTH_REQUIRED:"AUTH_REQUIRED", PERMISSION_DENIED:"POLICY_BLOCKED", NOT_FOUND:"PERMANENT", UNAVAILABLE:"TRANSIENT", CANCELLED:"CANCELLED", UNKNOWN_OUTCOME:"AMBIGUOUS_OUTCOME" };
  if (attempt.error_code && map[attempt.error_code]) return map[attempt.error_code]!;
  if (["INVALID_RESPONSE","EXECUTION_FAILED","INTERNAL_ERROR"].includes(attempt.error_code ?? "")) return attempt.retryable_hint === true ? "TRANSIENT" : "PERMANENT";
  return "UNKNOWN";
}
export function computeReliabilityBackoff(policy: AsyncReliabilityInput["policy"], retryOrdinal: number, retryAfter?: number): number {
  const policyDelay = policy.backoff.strategy === "FIXED" ? policy.backoff.base_delay_ms : Math.min(policy.backoff.max_delay_ms, Math.ceil(policy.backoff.base_delay_ms * policy.backoff.multiplier ** (retryOrdinal - 1)));
  return Math.max(policyDelay, retryAfter ?? 0);
}
export function validateAsyncJobTransition(from: AsyncReliabilityJobState, to: AsyncReliabilityJobState): boolean { return ALLOWED_JOB_TRANSITIONS[from].includes(to); }
export function validateAsyncReliabilityInput(value: unknown): AsyncReliabilityValidationResult {
  const x=value as Partial<AsyncReliabilityInput>, errors:string[]=[];
  if(!x||typeof x!=="object"||Array.isArray(x)||sensitive(x)) return {valid:false,errors:["malformed or sensitive reliability input"]};
  const safeRefs=(candidate:unknown):candidate is string[]=>Array.isArray(candidate)&&candidate.every(ref);
  if(!ref(x.task_ref)||!safeRefs(x.source_refs)||!safeRefs(x.evidence_refs)||!strings(x.limitations)) errors.push("top-level refs invalid");
  const o=x.operation,p=x.policy,c=x.clock,j=x.job,s=x.security,r=x.replay_evidence,z=x.cancellation;
  const sideEffects=["READ_ONLY","IDEMPOTENT_WRITE","NON_IDEMPOTENT_WRITE","EXTERNAL_SIDE_EFFECT"];
  if(!o||!ref(o.operation_ref)||!ref(o.request_fingerprint)||!ref(o.authority_ref)||!sideEffects.includes(o.side_effect_class)||typeof o.declared_idempotent!=="boolean"||typeof o.approval_required!=="boolean"||(o.approval_ref!==undefined&&!ref(o.approval_ref))||(o.capability_id!==undefined&&!ref(o.capability_id))) errors.push("operation invalid");
  if(!p||!Number.isSafeInteger(p.max_attempts)||p.max_attempts<1||!Number.isSafeInteger(p.max_elapsed_ms)||p.max_elapsed_ms<1||!p.backoff||!["FIXED","EXPONENTIAL"].includes(p.backoff.strategy)||!int(p.backoff.base_delay_ms)||!int(p.backoff.max_delay_ms)||typeof p.backoff.multiplier!=="number"||!Number.isFinite(p.backoff.multiplier)||p.backoff.multiplier<1||p.backoff.max_delay_ms<p.backoff.base_delay_ms||p.respect_retry_after!==true) errors.push("policy invalid");
  if(!c||!int(c.operation_started_at_ms)||!int(c.now_ms)||c.now_ms<c.operation_started_at_ms||(c.effective_deadline_at_ms!==undefined&&(!int(c.effective_deadline_at_ms)||c.effective_deadline_at_ms<c.operation_started_at_ms))) errors.push("clock invalid");
  const attempts=x.attempts;
  if(!Array.isArray(attempts)||attempts.length===0) errors.push("attempts missing");
  else {
    const seen=new Set<string>();
    attempts.forEach((a,index)=>{
      if(!a||typeof a!=="object"||!ref(a.attempt_id)||seen.has(a.attempt_id)||a.attempt_number!==index+1||!ref(a.operation_ref)||!ref(a.request_fingerprint)||!ref(a.authority_ref)||!int(a.started_at_ms)||(a.ended_at_ms!==undefined&&(!int(a.ended_at_ms)||a.ended_at_ms<a.started_at_ms))||!["NOT_DISPATCHED","DISPATCHED","ACKNOWLEDGED"].includes(a.dispatch_state)||!["SUCCESS","FAIL","BLOCKED"].includes(a.observed_status)||!["MODEL","CAPABILITY","UPSTREAM"].includes(a.source)||!safeRefs(a.evidence_refs)||(a.retryable_hint!==undefined&&typeof a.retryable_hint!=="boolean")||(a.approval_ref!==undefined&&!ref(a.approval_ref))||(a.capability_id!==undefined&&!ref(a.capability_id))) errors.push("attempt invalid");
      if(ref(a.attempt_id)) seen.add(a.attempt_id);
      if(a.error_code!==undefined&&!['UNAVAILABLE','TIMEOUT','INVALID_REQUEST','INVALID_RESPONSE','RATE_LIMITED','AUTH_REQUIRED','INTERNAL_ERROR','NOT_FOUND','INVALID_INPUT','PERMISSION_DENIED','EXECUTION_FAILED','CANCELLED','UNKNOWN_OUTCOME'].includes(a.error_code)) errors.push("unknown error code");
      if(a.retry_after_ms!==undefined&&(!int(a.retry_after_ms)||a.observed_status!=="FAIL")) errors.push("retry-after invalid");
      if(a.observed_status==="FAIL"&&!a.error_code) errors.push("fail needs code");
      if(a.observed_status==="SUCCESS"&&(a.error_code!==undefined||a.retry_after_ms!==undefined)) errors.push("success cannot have failure metadata");
      if(a.observed_status==="BLOCKED"&&a.error_code!==undefined&&!['AUTH_REQUIRED','PERMISSION_DENIED'].includes(a.error_code)) errors.push("blocked code invalid");
      if(a.operation_ref!==o?.operation_ref||a.request_fingerprint!==o?.request_fingerprint||a.authority_ref!==o?.authority_ref||a.approval_ref!==o?.approval_ref||a.capability_id!==o?.capability_id) errors.push("attempt binding mismatch");
      if(c&&int(a.started_at_ms)&&(a.started_at_ms<c.operation_started_at_ms||a.started_at_ms>c.now_ms||(a.ended_at_ms!==undefined&&a.ended_at_ms>c.now_ms))) errors.push("attempt timing outside clock");
    });
    if(p&&attempts.length>p.max_attempts) errors.push("attempt count exceeds policy");
  }
  if(!attempts?.length||x.latest_attempt_id!==attempts.at(-1)?.attempt_id) errors.push("latest attempt mismatch");
  if(!j||!ref(j.job_id)||!["PENDING","RUNNING","WAITING_RETRY","RECONCILING","SUCCEEDED","FAILED","CANCELLED","BLOCKED"].includes(j.state)||!int(j.created_at_ms)||(j.deadline_at_ms!==undefined&&(!int(j.deadline_at_ms)||j.deadline_at_ms<j.created_at_ms))||j.operation_ref!==o?.operation_ref||j.request_fingerprint!==o?.request_fingerprint) errors.push("job invalid");
  if(j?.state==="PENDING"&&attempts?.length) errors.push("pending job cannot contain a completed attempt");
  if(!s||!ref(s.authority_ref)||s.authority_ref!==o?.authority_ref||typeof s.approval_required!=="boolean"||!safeRefs(s.allowed_capability_ids)||!Array.isArray(s.allowed_side_effect_classes)||!s.allowed_side_effect_classes.every(item=>sideEffects.includes(item))||!s.allowed_side_effect_classes.includes(o?.side_effect_class as never)||(o?.capability_id!==undefined&&!s.allowed_capability_ids.includes(o.capability_id))||s.approval_required!==o?.approval_required||(s.approval_ref!==undefined&&!ref(s.approval_ref))||(o?.approval_required&&(!ref(o.approval_ref)||o.approval_ref!==s.approval_ref))) errors.push("security invalid");
  const replayKinds=['NONE','DECLARED_IDEMPOTENT','DURABLE_KEYED_DEDUPLICATION','RECONCILED_NOT_APPLIED','RECONCILED_APPLIED'];
  if(!r||!ref(r.operation_ref)||!ref(r.request_fingerprint)||r.operation_ref!==o?.operation_ref||r.request_fingerprint!==o?.request_fingerprint||!replayKinds.includes(r.kind)) errors.push("replay evidence invalid");
  if(r?.kind==="NONE"&&(r.evidence_ref!==undefined||r.key_scope_ref!==undefined||r.replay_safe!==undefined)) errors.push("none replay evidence carries proof");
  if(r?.kind==="DECLARED_IDEMPOTENT"&&(o?.side_effect_class!=="IDEMPOTENT_WRITE"||o.declared_idempotent!==true||r.evidence_ref!==undefined||r.key_scope_ref!==undefined||r.replay_safe!==undefined)) errors.push("declared idempotency evidence invalid");
  if(r?.kind==="DURABLE_KEYED_DEDUPLICATION"&&(!ref(r.evidence_ref)||!ref(r.key_scope_ref)||r.replay_safe!==true)) errors.push("durable replay evidence invalid");
  if(['RECONCILED_NOT_APPLIED','RECONCILED_APPLIED'].includes(r?.kind??"")&&(!ref(r?.evidence_ref)||r?.key_scope_ref!==undefined||r?.replay_safe!==undefined)) errors.push("reconciliation evidence invalid");
  if(!z||typeof z.requested!=="boolean"||typeof z.acknowledged!=="boolean"||(z.requested&&(!int(z.requested_at_ms)||!c||z.requested_at_ms!>c.now_ms))||(!z.requested&&z.requested_at_ms!==undefined)||(z.acknowledged&&(!z.requested||!ref(z.acknowledgement_ref)))||(!z.acknowledged&&z.acknowledgement_ref!==undefined)) errors.push("cancellation invalid");
  return {valid:errors.length===0,errors};
}
export function assessReplaySafety(input: AsyncReliabilityInput): ReplaySafetyAssessment { const a=input.attempts.at(-1)!; const r=input.replay_evidence; if(a.dispatch_state==='NOT_DISPATCHED'||input.operation.side_effect_class==='READ_ONLY') return {disposition:"NOT_REQUIRED",retryable:true,requires_reconciliation:false,reason:"TRANSIENT_RETRY_ALLOWED"}; if(r.operation_ref!==input.operation.operation_ref||r.request_fingerprint!==input.operation.request_fingerprint) return {disposition:"MISMATCH",retryable:false,requires_reconciliation:true,reason:"IDEMPOTENCY_EVIDENCE_MISMATCH"}; if(r.kind==='RECONCILED_APPLIED') return {disposition:"SUFFICIENT",retryable:false,requires_reconciliation:false,reason:"RECONCILED_APPLIED"}; if(input.operation.side_effect_class==='IDEMPOTENT_WRITE') { const ok=input.operation.declared_idempotent && (r.kind==='DECLARED_IDEMPOTENT'||r.kind==='DURABLE_KEYED_DEDUPLICATION'); return {disposition:ok?'SUFFICIENT':'INSUFFICIENT',retryable:ok,requires_reconciliation:!ok,reason:ok?'TRANSIENT_RETRY_ALLOWED':'IDEMPOTENCY_EVIDENCE_INSUFFICIENT'}; } const ok=r.kind==='DURABLE_KEYED_DEDUPLICATION'||r.kind==='RECONCILED_NOT_APPLIED'; return {disposition:ok?'SUFFICIENT':'INSUFFICIENT',retryable:ok,requires_reconciliation:!ok,reason:ok?'TRANSIENT_RETRY_ALLOWED':'IDEMPOTENCY_EVIDENCE_INSUFFICIENT'}; }
function blocked(input:Partial<AsyncReliabilityInput> | null | undefined, reason:AsyncReliabilityReasonCode, blockers:string[]): AsyncReliabilityDecision { const safe=input??{}; return {status:"BLOCKED",action:"BLOCK",task_ref:safe.task_ref??"invalid",operation_ref:safe.operation?.operation_ref??"invalid",job_id:safe.job?.job_id??"invalid",latest_attempt_id:safe.latest_attempt_id??"invalid",failure_class:"UNKNOWN",reason_code:reason,next_job_state:"BLOCKED",remaining_attempts:0,remaining_elapsed_ms:0,replay_disposition:"INSUFFICIENT",requires_reconciliation:false,authority_ref:safe.operation?.authority_ref??"invalid",evidence_refs:[],blockers,limitations:[],residual_unknowns:[]}; }
export function deriveAsyncReliabilityDecision(value: unknown): AsyncReliabilityDecision { const input=value as AsyncReliabilityInput; const check=validateAsyncReliabilityInput(input); if(!check.valid) return blocked(input,"INVALID_RELIABILITY_INPUT",check.errors); const x=clone(input), latest=x.attempts.at(-1)!, elapsed=x.clock.now_ms-x.clock.operation_started_at_ms, remainingElapsed=x.policy.max_elapsed_ms-elapsed, remainingAttempts=x.policy.max_attempts-x.attempts.length, remainingDeadline=x.clock.effective_deadline_at_ms===undefined?undefined:x.clock.effective_deadline_at_ms-x.clock.now_ms; const base={task_ref:x.task_ref,operation_ref:x.operation.operation_ref,job_id:x.job.job_id,latest_attempt_id:latest.attempt_id,remaining_attempts:remainingAttempts,remaining_elapsed_ms:remainingElapsed, ...(remainingDeadline===undefined?{}:{remaining_deadline_ms:remainingDeadline}),authority_ref:x.operation.authority_ref,...(x.operation.approval_ref?{approval_ref:x.operation.approval_ref}:{ }),evidence_refs:[...x.evidence_refs],blockers:[] as string[],limitations:[...x.limitations],residual_unknowns:[] as string[]};
  if(TERMINAL_JOB_STATES.has(x.job.state)) {
    if(x.job.state==="SUCCEEDED") return {...base,status:"READY",action:"COMPLETE",failure_class:"NONE",reason_code:"OBSERVED_SUCCESS",next_job_state:"SUCCEEDED",replay_disposition:"NOT_REQUIRED",requires_reconciliation:false,limitations:[...base.limitations,"TERMINAL_JOB_PRESERVED"]};
    if(x.job.state==="FAILED") return {...base,status:"READY",action:"STOP",failure_class:"UNKNOWN",reason_code:"NON_RETRYABLE_FAILURE",next_job_state:"FAILED",replay_disposition:"NOT_REQUIRED",requires_reconciliation:false,limitations:[...base.limitations,"TERMINAL_JOB_PRESERVED"]};
    if(x.job.state==="CANCELLED") return {...base,status:"READY",action:"CANCEL",failure_class:"UNKNOWN",reason_code:"CANCELLATION_CONFIRMED",next_job_state:"CANCELLED",replay_disposition:"NOT_REQUIRED",requires_reconciliation:false,limitations:[...base.limitations,"TERMINAL_JOB_PRESERVED"]};
    return {...base,status:"READY",action:"BLOCK",failure_class:"UNKNOWN",reason_code:"POLICY_BLOCKED",next_job_state:"BLOCKED",replay_disposition:"NOT_REQUIRED",requires_reconciliation:false,limitations:[...base.limitations,"TERMINAL_JOB_PRESERVED"]};
  }
  const failure=classifyReliabilityFailure(latest);
  if(latest.observed_status==='SUCCESS') return {...base,status:"READY",action:"COMPLETE",failure_class:"NONE",reason_code:"OBSERVED_SUCCESS",next_job_state:"SUCCEEDED",replay_disposition:"NOT_REQUIRED",requires_reconciliation:false,limitations:x.cancellation.requested?[...base.limitations,"CANCELLATION_RACE_OBSERVED_SUCCESS"]:base.limitations};
  if(x.cancellation.acknowledged || (x.cancellation.requested&&latest.dispatch_state==='NOT_DISPATCHED')) return {...base,status:"READY",action:"CANCEL",failure_class:failure,reason_code:"CANCELLATION_CONFIRMED",next_job_state:"CANCELLED",replay_disposition:"NOT_REQUIRED",requires_reconciliation:false};
  if(x.cancellation.requested&&latest.dispatch_state!=='NOT_DISPATCHED') return {...base,status:"INCONCLUSIVE",action:"RECONCILE",failure_class:failure,reason_code:"CANCELLATION_REQUIRES_RECONCILIATION",next_job_state:"RECONCILING",replay_disposition:"INSUFFICIENT",requires_reconciliation:true,residual_unknowns:["remote cancellation outcome"]};
  const replay=assessReplaySafety(x); if(replay.reason==='RECONCILED_APPLIED') return {...base,status:"READY",action:"COMPLETE",failure_class:failure,reason_code:"RECONCILED_APPLIED",next_job_state:"SUCCEEDED",replay_disposition:replay.disposition,requires_reconciliation:false};
  if((failure==='AMBIGUOUS_OUTCOME'||failure==='UNKNOWN')&&latest.dispatch_state!=='NOT_DISPATCHED'&&x.operation.side_effect_class!=='READ_ONLY') return {...base,status:"INCONCLUSIVE",action:"RECONCILE",failure_class:failure,reason_code:"AMBIGUOUS_REMOTE_OUTCOME",next_job_state:"RECONCILING",replay_disposition:replay.disposition,requires_reconciliation:true,residual_unknowns:["post-dispatch effect outcome"]};
  if(!RETRY_CANDIDATES.has(failure)) { const reason:AsyncReliabilityReasonCode=failure==='AUTH_REQUIRED'?'AUTH_REQUIRED':failure==='POLICY_BLOCKED'?'POLICY_BLOCKED':failure==='INVALID_INPUT'?'INVALID_INPUT':'NON_RETRYABLE_FAILURE'; return {...base,status:"READY",action:failure==='POLICY_BLOCKED'?'BLOCK':'STOP',failure_class:failure,reason_code:reason,next_job_state:failure==='POLICY_BLOCKED'?'BLOCKED':'FAILED',replay_disposition:replay.disposition,requires_reconciliation:false}; }
  if(!replay.retryable) return {...base,status:"INCONCLUSIVE",action:"RECONCILE",failure_class:failure,reason_code:replay.reason,next_job_state:"RECONCILING",replay_disposition:replay.disposition,requires_reconciliation:true,residual_unknowns:["post-dispatch effect outcome"]};
  if(remainingAttempts<=0) return {...base,status:"READY",action:"STOP",failure_class:failure,reason_code:"RETRY_BUDGET_EXHAUSTED",next_job_state:"FAILED",replay_disposition:replay.disposition,requires_reconciliation:false};
  if(remainingElapsed<=0) return {...base,status:"READY",action:"STOP",failure_class:failure,reason_code:"ELAPSED_BUDGET_EXHAUSTED",next_job_state:"FAILED",replay_disposition:replay.disposition,requires_reconciliation:false};
  const delay=computeReliabilityBackoff(x.policy,x.attempts.length,latest.retry_after_ms); if(delay>remainingElapsed) return {...base,status:"READY",action:"STOP",failure_class:failure,reason_code:"ELAPSED_BUDGET_EXHAUSTED",next_job_state:"FAILED",replay_disposition:replay.disposition,requires_reconciliation:false}; if(remainingDeadline!==undefined&&delay>=remainingDeadline) return {...base,status:"READY",action:"STOP",failure_class:failure,reason_code:"DEADLINE_EXHAUSTED",next_job_state:"FAILED",replay_disposition:replay.disposition,requires_reconciliation:false};
  const reason:AsyncReliabilityReasonCode=failure==='RATE_LIMITED'?'RATE_LIMITED_RETRY_ALLOWED':failure==='TIMEOUT'?'TIMEOUT_RETRY_ALLOWED':'TRANSIENT_RETRY_ALLOWED'; return {...base,status:"READY",action:"RETRY",failure_class:failure,reason_code:reason,next_job_state:"WAITING_RETRY",next_attempt_number:x.attempts.length+1,delay_ms:delay,replay_disposition:replay.disposition,requires_reconciliation:false}; }
export function validateAsyncReliabilityDecision(candidate: unknown,input: unknown): AsyncReliabilityValidationResult {
  const expected=deriveAsyncReliabilityDecision(input), c=candidate as AsyncReliabilityDecision;
  if(!c||typeof c!=="object"||sensitive(c)) return {valid:false,errors:["candidate malformed"]};
  const fields:(keyof AsyncReliabilityDecision)[]=["status","action","task_ref","operation_ref","job_id","latest_attempt_id","failure_class","reason_code","next_job_state","next_attempt_number","delay_ms","remaining_attempts","remaining_elapsed_ms","remaining_deadline_ms","replay_disposition","requires_reconciliation","authority_ref","approval_ref","evidence_refs","blockers","limitations","residual_unknowns"];
  const errors=fields.filter(k=>JSON.stringify(c[k])!==JSON.stringify(expected[k])).map(k=>`candidate ${k} differs from recomputed evidence`);
  if(/exactly[ -]?once/i.test(JSON.stringify(c))) errors.push("candidate claims forbidden exactly-once execution");
  return {valid:errors.length===0,errors};
}
export function evaluateAsyncReliabilityCandidateGate(input: unknown,candidate: unknown) { const validation=validateAsyncReliabilityDecision(candidate,input); return {candidate,decision:validation.valid?clone(candidate as AsyncReliabilityDecision):blocked(input as Partial<AsyncReliabilityInput>,"INVALID_RELIABILITY_INPUT",validation.errors),decisionValidation:validation}; }
