export type AsyncReliabilityStatus = "READY" | "INCONCLUSIVE" | "BLOCKED";
export type AsyncReliabilityAction = "COMPLETE" | "RETRY" | "RECONCILE" | "CANCEL" | "STOP" | "BLOCK";
export type ReliabilityAttemptSource = "MODEL" | "CAPABILITY" | "UPSTREAM";
export type ReliabilityObservedStatus = "SUCCESS" | "FAIL" | "BLOCKED";
export type ReliabilityDispatchState = "NOT_DISPATCHED" | "DISPATCHED" | "ACKNOWLEDGED";
export type ReliabilityObservedErrorCode = "UNAVAILABLE" | "TIMEOUT" | "INVALID_REQUEST" | "INVALID_RESPONSE" | "RATE_LIMITED" | "AUTH_REQUIRED" | "INTERNAL_ERROR" | "NOT_FOUND" | "INVALID_INPUT" | "PERMISSION_DENIED" | "EXECUTION_FAILED" | "CANCELLED" | "UNKNOWN_OUTCOME";
export type ReliabilityFailureClass = "NONE" | "TRANSIENT" | "RATE_LIMITED" | "TIMEOUT" | "PERMANENT" | "INVALID_INPUT" | "AUTH_REQUIRED" | "POLICY_BLOCKED" | "CANCELLED" | "AMBIGUOUS_OUTCOME" | "UNKNOWN";
export type ReliabilitySideEffectClass = "READ_ONLY" | "IDEMPOTENT_WRITE" | "NON_IDEMPOTENT_WRITE" | "EXTERNAL_SIDE_EFFECT";
export type ReliabilityBackoffStrategy = "FIXED" | "EXPONENTIAL";
export type ReliabilityReplayEvidenceKind = "NONE" | "DECLARED_IDEMPOTENT" | "DURABLE_KEYED_DEDUPLICATION" | "RECONCILED_NOT_APPLIED" | "RECONCILED_APPLIED";
export type AsyncReliabilityJobState = "PENDING" | "RUNNING" | "WAITING_RETRY" | "RECONCILING" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "BLOCKED";
export type AsyncReliabilityReasonCode = "OBSERVED_SUCCESS" | "TRANSIENT_RETRY_ALLOWED" | "RATE_LIMITED_RETRY_ALLOWED" | "TIMEOUT_RETRY_ALLOWED" | "RETRY_BUDGET_EXHAUSTED" | "DEADLINE_EXHAUSTED" | "ELAPSED_BUDGET_EXHAUSTED" | "NON_RETRYABLE_FAILURE" | "POLICY_BLOCKED" | "AUTH_REQUIRED" | "INVALID_INPUT" | "AMBIGUOUS_REMOTE_OUTCOME" | "IDEMPOTENCY_EVIDENCE_INSUFFICIENT" | "IDEMPOTENCY_EVIDENCE_MISMATCH" | "CANCELLATION_CONFIRMED" | "CANCELLATION_REQUIRES_RECONCILIATION" | "RECONCILED_APPLIED" | "INVALID_RELIABILITY_INPUT" | "ILLEGAL_JOB_TRANSITION" | "FUTURE_STAGE_REQUIRED";

export interface ReliabilityOperationProjection { operation_ref: string; side_effect_class: ReliabilitySideEffectClass; declared_idempotent: boolean; request_fingerprint: string; authority_ref: string; approval_required: boolean; approval_ref?: string; capability_id?: string; }
export interface ReliabilityAttemptProjection { attempt_id: string; attempt_number: number; operation_ref: string; request_fingerprint: string; authority_ref: string; approval_ref?: string; capability_id?: string; started_at_ms: number; ended_at_ms?: number; dispatch_state: ReliabilityDispatchState; observed_status: ReliabilityObservedStatus; source: ReliabilityAttemptSource; error_code?: ReliabilityObservedErrorCode; retryable_hint?: boolean; retry_after_ms?: number; evidence_refs: string[]; }
export interface ReliabilityRetryPolicy { max_attempts: number; max_elapsed_ms: number; backoff: { strategy: ReliabilityBackoffStrategy; base_delay_ms: number; max_delay_ms: number; multiplier: number; }; respect_retry_after: true; }
export interface ReliabilityClockProjection { operation_started_at_ms: number; now_ms: number; effective_deadline_at_ms?: number; }
export interface ReliabilityReplayEvidence { kind: ReliabilityReplayEvidenceKind; operation_ref: string; request_fingerprint: string; evidence_ref?: string; key_scope_ref?: string; replay_safe?: true; }
export interface ReliabilityCancellationProjection { requested: boolean; requested_at_ms?: number; acknowledged: boolean; acknowledgement_ref?: string; }
export interface AsyncReliabilityJobProjection { job_id: string; state: AsyncReliabilityJobState; created_at_ms: number; deadline_at_ms?: number; operation_ref: string; request_fingerprint: string; }
export interface AsyncReliabilityInput { task_ref: string; source_refs: string[]; operation: ReliabilityOperationProjection; policy: ReliabilityRetryPolicy; clock: ReliabilityClockProjection; attempts: ReliabilityAttemptProjection[]; latest_attempt_id: string; replay_evidence: ReliabilityReplayEvidence; cancellation: ReliabilityCancellationProjection; job: AsyncReliabilityJobProjection; security: { authority_ref: string; approval_required: boolean; approval_ref?: string; allowed_capability_ids: string[]; allowed_side_effect_classes: ReliabilitySideEffectClass[]; }; evidence_refs: string[]; limitations: string[]; }
export interface AsyncReliabilityDecision { status: AsyncReliabilityStatus; action: AsyncReliabilityAction; task_ref: string; operation_ref: string; job_id: string; latest_attempt_id: string; failure_class: ReliabilityFailureClass; reason_code: AsyncReliabilityReasonCode; next_job_state: AsyncReliabilityJobState; next_attempt_number?: number; delay_ms?: number; remaining_attempts: number; remaining_elapsed_ms: number; remaining_deadline_ms?: number; replay_disposition: "NOT_REQUIRED" | "SUFFICIENT" | "INSUFFICIENT" | "MISMATCH"; requires_reconciliation: boolean; authority_ref: string; approval_ref?: string; evidence_refs: string[]; blockers: string[]; limitations: string[]; residual_unknowns: string[]; }
export interface AsyncReliabilityValidationResult { valid: boolean; errors: string[]; }
export interface ReplaySafetyAssessment { disposition: AsyncReliabilityDecision["replay_disposition"]; retryable: boolean; requires_reconciliation: boolean; reason: AsyncReliabilityReasonCode; }
