import { createHash } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import type { ModelDecisionRequest, ModelDecisionResult, ModelProvider } from "../../src/core/agent/index.js";
import { ReferenceCapabilityProvider } from "../../src/providers/capability/referenceCapabilityProvider.js";
import { LocalReferenceSkillProvider } from "../../src/providers/skill/localReferenceSkillProvider.js";
import { GUARDRAILS_SECURITY_ATOMIC_ASSERTION_COUNT, GUARDRAILS_SECURITY_COMPARISON_ASSERTIONS, GUARDRAILS_SECURITY_SKILL_ID, compareGuardrailsSecurityRuns, deriveExpectedGuardrailsAtomic, deriveGuardrailsSecurityProfileFromRules, extractGuardrailsSecurityAssertionObservations, findForbiddenCredentialKeys, gateGuardrailsSecurity, planGuardrailsSecurity, synthesizeGuardrailsSecurityDecision, validateGuardrailsSecurityDecision, validateGuardrailsSecurityInput, type GuardrailsSecurityDecision, type GuardrailsSecurityInput } from "../../src/intelligence/guardrails-security/index.js";
import { guardrailsSecurityS13L, referenceSkillCatalogEntries } from "../../src/intelligence/skills/index.js";
import { ALL_NEGATIVE_FIXTURES, ALL_POSITIVE_INPUTS, DeterministicGuardrailsSecurityModelProvider, FX_POS_001, FX_POS_002, FX_POS_003, FX_POS_004, FX_POS_005, FX_POS_006, FX_POS_007, FX_POS_008, NEGATIVE_CONDITIONS, baseGuardrailsSecurityInput, guardrailsSecurityHost } from "./fixtures.js";
import { FROZEN_GUARDRAILS_SECURITY_FIXTURE_TRUTH } from "./fixtureTruth.js";

const capabilityProvider = new ReferenceCapabilityProvider(); const skillProvider = new LocalReferenceSkillProvider(referenceSkillCatalogEntries); const modelProvider = new DeterministicGuardrailsSecurityModelProvider(); const sourceDir = "src/intelligence/guardrails-security";
const PART_A = ["brain-bootstrap/skills/GUARDRAILS_SECURITY_SKILL_S13L.md", "brain-bootstrap/quality-contracts/S13L_GUARDRAILS_SECURITY_DEEP.yaml", "brain-bootstrap/specs/GUARDRAILS_SECURITY_CONTRACT_S13L.md"];
const rich = () => deriveGuardrailsSecurityProfileFromRules([...guardrailsSecurityS13L.rules.map((rule) => rule.statement), ...guardrailsSecurityS13L.procedure.map((step) => step.instruction)]);
const faithful = (input: GuardrailsSecurityInput) => synthesizeGuardrailsSecurityDecision(input, rich());
async function run(input: GuardrailsSecurityInput, withSkill: boolean) { const host = structuredClone(guardrailsSecurityHost); if (!withSkill) host.skills = []; return planGuardrailsSecurity(input, { baseDefinition: host, ...(withSkill ? { skillProvider } : {}), modelProvider, capabilityProvider }); }
function setFullyAllowlistedUnknownSideEffect(input: GuardrailsSecurityInput): void { (input.action as unknown as Record<string, unknown>).side_effect = "REMOTE"; (input.capability as unknown as Record<string, unknown>).descriptor_side_effect = "REMOTE"; (input.capability as unknown as Record<string, unknown>).agent_allowed_side_effects = ["REMOTE"]; (input.capability as unknown as Record<string, unknown>).skill_allowed_side_effects = ["REMOTE"]; (input.capability as unknown as Record<string, unknown>).policy_allowed_side_effects = ["REMOTE"]; }
const unknownEnumCases: ReadonlyArray<{ name: string; base: GuardrailsSecurityInput; mutate: (input: GuardrailsSecurityInput) => void; error: RegExp }> = [
  { name: "scope kind", base: FX_POS_002, mutate: (input) => { (input.scope as unknown as Record<string, unknown>).kind = "WORKSPACE"; }, error: /scope kind enum is unknown/ },
  { name: "action side effect", base: FX_POS_003, mutate: setFullyAllowlistedUnknownSideEffect, error: /action side-effect enum is unknown/ },
  { name: "descriptor side effect", base: FX_POS_003, mutate: setFullyAllowlistedUnknownSideEffect, error: /descriptor side-effect enum is unknown/ },
  { name: "secret propagation policy", base: FX_POS_007, mutate: (input) => { (input.policy as unknown as Record<string, unknown>).allowed_secret_reference_propagation = "PERSISTENT"; }, error: /propagation-policy enum is unknown/ },
];
const malformedCandidateCases: ReadonlyArray<{ name: string; mutate: (candidate: GuardrailsSecurityDecision) => void }> = [
  { name: "missing atomic group", mutate: (candidate) => { delete (candidate.atomic as unknown as Record<string, unknown>).scope; } },
  { name: "missing blockers collection", mutate: (candidate) => { delete (candidate as unknown as Record<string, unknown>).blockers; } },
  { name: "incomplete blocker item", mutate: (candidate) => { candidate.blockers = [{ code: "INCOMPLETE", message: "missing refs" } as unknown as GuardrailsSecurityDecision["blockers"][number]]; } },
  { name: "missing approval collection", mutate: (candidate) => { delete (candidate as unknown as Record<string, unknown>).approval_requirements; } },
  { name: "incomplete approval item", mutate: (candidate) => { candidate.approval_requirements = [{ code: "INCOMPLETE", action_fingerprint: FX_POS_001.action.action_fingerprint, reason: "missing refs" } as unknown as GuardrailsSecurityDecision["approval_requirements"][number]]; } },
];

describe("S13L Part A, bounded projection and Skill contract T1-T7", () => {
  it("Part A hashes remain exact", () => expect(PART_A.map((path) => createHash("sha256").update(readFileSync(path)).digest("hex"))).toEqual(["572da7681d138de5549931f9df00a850c4152670a3ba2a3dcbf694c724f0b3af", "cdaf6753dceef210208016c81acf3106c4d5f37079426ae7a442313c6d9e9f1c", "5f7eb7849934609870a09dd17ee8b9e45a8d878642754ed5bbed6bbc0f2e6bf5"]));
  it("T1/T3 valid input is one bounded action", () => { expect(validateGuardrailsSecurityInput(FX_POS_001).valid).toBe(true); const invalid = baseGuardrailsSecurityInput(); invalid.action.action_id = ""; expect(validateGuardrailsSecurityInput(invalid).valid).toBe(false); });
  it("T2 input stays immutable", () => { const input = baseGuardrailsSecurityInput(); const before = JSON.stringify(input); faithful(input); expect(JSON.stringify(input)).toBe(before); });
  it("T4/T5 Skill is capability-free and side-effect-free", () => { expect(guardrailsSecurityS13L.requires.capabilities).toEqual([]); expect(guardrailsSecurityS13L.permissions).toEqual({ allowed_capabilities: [], allowed_side_effects: ["NONE"], deny_unlisted_capabilities: true }); });
  it("T6/T7 no S13L AgentDefinition or Core semantic branch", () => { expect(readdirSync("src/intelligence/agent-definitions").some((name) => /guardrail|security|s13l/i.test(name))).toBe(false); for (const dir of ["src/core/agent", "src/core/skill"]) for (const name of readdirSync(dir)) if (name.endsWith(".ts")) expect(readFileSync(join(dir, name), "utf8")).not.toContain(GUARDRAILS_SECURITY_SKILL_ID); });
});

describe("AuthN/AuthZ, scope and confused deputy T8-T22", () => {
  it("public anonymous and trusted authenticated identities pass", () => { expect(deriveExpectedGuardrailsAtomic(FX_POS_001).identity).toEqual({ authentication_result: "PASS", provenance_result: "PASS", public_mode_result: "PASS" }); expect(deriveExpectedGuardrailsAtomic(FX_POS_002).identity).toMatchObject({ authentication_result: "PASS", provenance_result: "PASS" }); });
  it("missing/unknown/untrusted principal and required grant fail closed", () => { for (const index of [0, 1, 2]) expect(gateGuardrailsSecurity(ALL_NEGATIVE_FIXTURES[index].input, ALL_NEGATIVE_FIXTURES[index].decision).decision.status).toBe("BLOCKED"); });
  it("trusted matching scope passes while client scope, mismatch and tool redirect block", () => { expect(deriveExpectedGuardrailsAtomic(FX_POS_002).scope).toEqual({ authorization_result: "PASS", tenant_isolation_result: "PASS", confused_deputy_result: "PASS" }); for (const index of [3, 4, 5]) expect(gateGuardrailsSecurity(ALL_NEGATIVE_FIXTURES[index].input, ALL_NEGATIVE_FIXTURES[index].decision).decision.status).toBe("BLOCKED"); });
  it("explicit policy-approved cross-scope grant can pass", () => { const input = structuredClone(FX_POS_002); input.scope.resource_scope_ref = "tenant:beta"; input.scope.cross_scope_grant_ref = "grant:cross-scope"; input.policy.cross_scope_allowed_with_explicit_grant = true; expect(deriveExpectedGuardrailsAtomic(input).scope.tenant_isolation_result).toBe("PASS"); });
});

describe("least privilege, action impact and approval T23-T47", () => {
  it("no capability is N/A; known NONE-side-effect intersection passes", () => { expect(Object.values(deriveExpectedGuardrailsAtomic(FX_POS_001).capability)).toEqual(["NOT_APPLICABLE", "NOT_APPLICABLE", "NOT_APPLICABLE"]); expect(Object.values(deriveExpectedGuardrailsAtomic(FX_POS_003).capability)).toEqual(["PASS", "PASS", "PASS"]); });
  it("every capability/side-effect layer and known id are conjunctive", () => { for (const index of [6, 7, 8, 9, 10, 11]) expect(gateGuardrailsSecurity(ALL_NEGATIVE_FIXTURES[index].input, ALL_NEGATIVE_FIXTURES[index].decision).decision.status).toBe("BLOCKED"); });
  it("read/reversible pass and high/destructive require explicit policy path", () => { const reversible = structuredClone(FX_POS_001); reversible.action.impact = "REVERSIBLE"; expect(deriveExpectedGuardrailsAtomic(reversible).action.impact_result).toBe("PASS"); expect(gateGuardrailsSecurity(ALL_NEGATIVE_FIXTURES[12].input, ALL_NEGATIVE_FIXTURES[12].decision).decision.status).toBe("BLOCKED"); });
  it("fresh exact distinct approval and destructive recovery pass", () => { expect(deriveExpectedGuardrailsAtomic(FX_POS_004).action).toMatchObject({ impact_result: "PASS", approval_result: "PASS" }); expect(deriveExpectedGuardrailsAtomic(FX_POS_005).action).toEqual({ impact_result: "PASS", approval_result: "PASS", recovery_result: "PASS" }); });
  it("missing/wrong/stale/self approval is APPROVAL_REQUIRED only when otherwise safe", () => { expect(faithful(FX_POS_008).status).toBe("APPROVAL_REQUIRED"); for (const index of [13, 14, 15]) expect(gateGuardrailsSecurity(ALL_NEGATIVE_FIXTURES[index].input, ALL_NEGATIVE_FIXTURES[index].decision).decision.status).toBe("APPROVAL_REQUIRED"); });
  it("approval cannot override AuthZ failure and destructive recovery cannot be invented", () => { for (const index of [16, 17]) expect(gateGuardrailsSecurity(ALL_NEGATIVE_FIXTURES[index].input, ALL_NEGATIVE_FIXTURES[index].decision).decision.status).toBe("BLOCKED"); });
  it("irreversibility acknowledgement needs source evidence and approved path; time is supplied", () => { const input = structuredClone(FX_POS_005); input.action.recovery_mode = "IRREVERSIBILITY_ACKNOWLEDGEMENT"; input.action.recovery_evidence_ref = "ack:irreversible"; expect(deriveExpectedGuardrailsAtomic(input).action.recovery_result).toBe("PASS"); expect(input.approval.evaluation_time_epoch_ms).toBe(1_800_000_000_000); });
});

describe("finite secrets, instruction authority and minimization T48-T77", () => {
  it("finite known-key scan and supplied HIGH finding block without universal claim", () => { expect(findForbiddenCredentialKeys(ALL_NEGATIVE_FIXTURES[18].input)).toContain("$.access_token"); for (const index of [18, 19, 20]) expect(gateGuardrailsSecurity(ALL_NEGATIVE_FIXTURES[index].input, ALL_NEGATIVE_FIXTURES[index].decision).decision.status).toBe("BLOCKED"); expect(readFileSync(join(sourceDir, "modeling.ts"), "utf8")).toMatch(/finite known-key defense only/i); });
  it("opaque safe secret reference is not authority and does not propagate", () => { const decision = faithful(FX_POS_007); expect(decision.status).toBe("ALLOW"); expect(decision).not.toHaveProperty("secret_refs"); expect(FX_POS_007.subject.authorization_grant_refs).not.toContain(FX_POS_007.secrets.secret_refs[0].ref); expect(JSON.stringify(decision)).not.toContain("payments-primary"); });
  it("opaque reference log, durable-memory and user-output propagation each block", () => { for (const target of ["proposed_log_field_refs", "proposed_durable_memory_field_refs", "proposed_disclosure_field_refs"] as const) { const input = structuredClone(FX_POS_007); input.sensitive_data.available_fields = [{ field_ref: "field:secret-ref", classification: "SECRET_REFERENCE", purpose_ref: "purpose:internal-use" }]; input.sensitive_data.purpose_required_field_refs = ["field:secret-ref"]; input.sensitive_data.authorized_disclosure_field_refs = ["field:secret-ref"]; input.sensitive_data[target] = ["field:secret-ref"]; input.policy.allowed_secret_reference_propagation = "TRANSIENT_ONLY"; input.secrets.allow_safe_ref_in_logs = true; input.secrets.allow_safe_ref_in_durable_memory = true; input.secrets.allow_safe_ref_in_user_output = true; expect(gateGuardrailsSecurity(input, faithful(input)).decision.status).toBe("BLOCKED"); } });
  it("authorized task authority passes; retrieval injection remains DATA_ONLY", () => { expect(deriveExpectedGuardrailsAtomic(FX_POS_006).content).toEqual({ instruction_data_result: "PASS", indirect_injection_result: "PASS", authority_conflict_result: "PASS" }); });
  it("user payload, retrieval, tool output, history and external documents remain DATA_ONLY", () => { const input = structuredClone(FX_POS_001); for (const source of ["USER_PAYLOAD", "RETRIEVED_CONTENT", "TOOL_OUTPUT", "HISTORICAL_MEMORY", "EXTERNAL_DOCUMENT"] as const) input.content.items.push({ item_ref: `data:${source}`, source, authority: "DATA_ONLY", instruction_like_finding: true, source_refs: [`source:${source}`] }); expect(deriveExpectedGuardrailsAtomic(input).content).toEqual({ instruction_data_result: "PASS", indirect_injection_result: "PASS", authority_conflict_result: "PASS" }); for (const item of input.content.items.slice(1)) { const elevated = structuredClone(input); elevated.content.items.find((candidate) => candidate.item_ref === item.item_ref)!.authority = "TASK_INSTRUCTION"; expect(gateGuardrailsSecurity(elevated, faithful(elevated)).decision.status).toBe("BLOCKED"); } });
  it("retrieval/tool/history elevation and unresolved authority conflict block", () => { for (const index of [21, 22, 23, 24]) expect(gateGuardrailsSecurity(ALL_NEGATIVE_FIXTURES[index].input, ALL_NEGATIVE_FIXTURES[index].decision).decision.status).toBe("BLOCKED"); });
  it("purpose and authorization independently bound disclosure/log/memory", () => { for (const index of [25, 26]) expect(gateGuardrailsSecurity(ALL_NEGATIVE_FIXTURES[index].input, ALL_NEGATIVE_FIXTURES[index].decision).decision.status).toBe("BLOCKED"); const input = structuredClone(FX_POS_001); input.sensitive_data.purpose_required_field_refs = ["field:title"]; input.sensitive_data.authorized_disclosure_field_refs = ["field:title"]; input.sensitive_data.proposed_disclosure_field_refs = ["field:title"]; expect(deriveExpectedGuardrailsAtomic(input).data).toEqual({ minimization_result: "PASS", disclosure_result: "PASS", memory_logging_result: "PASS" }); });
  it("general log and durable-memory fields require both purpose and authorization", () => { for (const target of ["proposed_log_field_refs", "proposed_durable_memory_field_refs"] as const) { const missingPurpose = structuredClone(FX_POS_001); missingPurpose.sensitive_data.authorized_disclosure_field_refs = ["field:title"]; missingPurpose.sensitive_data[target] = ["field:title"]; expect(gateGuardrailsSecurity(missingPurpose, faithful(missingPurpose)).decision.status).toBe("BLOCKED"); const missingAuth = structuredClone(FX_POS_001); missingAuth.sensitive_data.purpose_required_field_refs = ["field:title"]; missingAuth.sensitive_data[target] = ["field:title"]; expect(gateGuardrailsSecurity(missingAuth, faithful(missingAuth)).decision.status).toBe("BLOCKED"); } });
  it("fixtures and decisions contain no realistic PII/token/cookie/private-key values", () => { expect(JSON.stringify(ALL_POSITIVE_INPUTS)).not.toMatch(/bearer\s+[a-z0-9._-]+|BEGIN PRIVATE KEY|session_cookie|@example\./i); });
});

describe("enforcement, actual candidate and traceability T78-T90", () => {
  it("protected operations require an enforcement point; public read may use N/A", () => { expect(deriveExpectedGuardrailsAtomic(FX_POS_002).enforcement.point_result).toBe("PASS"); expect(deriveExpectedGuardrailsAtomic(FX_POS_001).enforcement.point_result).toBe("NOT_APPLICABLE"); expect(gateGuardrailsSecurity(ALL_NEGATIVE_FIXTURES[27].input, ALL_NEGATIVE_FIXTURES[27].decision).decision.status).toBe("BLOCKED"); });
  it("stale/current fingerprint evidence and unknown policy fail closed", () => { expect(gateGuardrailsSecurity(ALL_NEGATIVE_FIXTURES[28].input, ALL_NEGATIVE_FIXTURES[28].decision).decision.status).toBe("BLOCKED"); const input = structuredClone(FX_POS_001); input.policy.policy_ref = ""; expect(validateGuardrailsSecurityInput(input).valid).toBe(false); });
  it("unknown impact/enforcement enum values fail closed at runtime", () => { const impact = structuredClone(FX_POS_001); (impact.action as { impact: string }).impact = "UNKNOWN"; expect(gateGuardrailsSecurity(impact, faithful(impact)).decision.status).toBe("BLOCKED"); const point = structuredClone(FX_POS_002); (point.enforcement as { enforcement_point: string }).enforcement_point = "VENDOR_GATE"; expect(gateGuardrailsSecurity(point, faithful(point)).decision.status).toBe("BLOCKED"); });
  it.each(unknownEnumCases)("unknown $name is rejected before evaluation and never reaches ALLOW", ({ base, mutate, error }) => { const input = structuredClone(base); mutate(input); const validation = validateGuardrailsSecurityInput(input); expect(validation).toMatchObject({ valid: false, recomputed_status: "BLOCKED" }); expect(validation.errors.join("\n")).toMatch(error); expect(faithful(input).status).toBe("BLOCKED"); const candidate = faithful(base); candidate.status = "ALLOW"; expect(gateGuardrailsSecurity(input, candidate).decision.status).toBe("BLOCKED"); });
  it("candidate ALLOW/PASS cannot self-certify an auth bypass", () => { const fixture = ALL_NEGATIVE_FIXTURES[29]; const gated = gateGuardrailsSecurity(fixture.input, fixture.decision); expect(gated.decision.status).toBe("BLOCKED"); expect(gated.decision.atomic.identity.authentication_result).toBe("PASS"); });
  it("actual candidate fields are preserved while terminal status is recomputed", () => { const candidate = faithful(FX_POS_002); candidate.atomic.identity.authentication_result = "FAIL"; candidate.spec_refs.push("marker:actual-candidate"); candidate.status = "ALLOW"; const gated = gateGuardrailsSecurity(FX_POS_002, candidate); expect(gated.decision.status).toBe("BLOCKED"); expect(gated.decision.atomic.identity.authentication_result).toBe("FAIL"); expect(gated.decision.spec_refs).toContain("marker:actual-candidate"); });
  it("candidate cannot smuggle extra capability, side effect or disclosure through an otherwise passing atomic decision", () => { const candidate = faithful(FX_POS_001); candidate.permitted_capability_ids = ["capability:overbroad"]; candidate.permitted_side_effects = ["EXTERNAL"]; candidate.allowed_disclosure_field_refs = ["field:private"]; expect(gateGuardrailsSecurity(FX_POS_001, candidate).decision.status).toBe("BLOCKED"); });
  it("blockers and approval requirements are source/fingerprint traceable; acceptance/evidence unchanged", () => { const blocked = gateGuardrailsSecurity(ALL_NEGATIVE_FIXTURES[0].input, ALL_NEGATIVE_FIXTURES[0].decision).decision; expect(blocked.blockers.every((item) => item.source_refs.length)).toBe(true); const pending = faithful(FX_POS_008); expect(pending.approval_requirements[0]).toMatchObject({ action_fingerprint: FX_POS_008.action.action_fingerprint }); expect(pending.approval_requirements[0].required_evidence_refs.length).toBeGreaterThan(0); expect(faithful(FX_POS_002).acceptance).toEqual(FX_POS_002.acceptance); expect(faithful(FX_POS_002).evidence_required).toEqual(FX_POS_002.evidence_required); });
  it.each(malformedCandidateCases)("$name is deterministically invalid/BLOCKED without throwing", ({ mutate }) => { const candidate = faithful(FX_POS_001); mutate(candidate); let validation: ReturnType<typeof validateGuardrailsSecurityDecision> | undefined; expect(() => { validation = validateGuardrailsSecurityDecision(candidate, FX_POS_001); }).not.toThrow(); expect(validation).toMatchObject({ valid: false, recomputed_status: "BLOCKED" }); let outcome: ReturnType<typeof gateGuardrailsSecurity> | undefined; expect(() => { outcome = gateGuardrailsSecurity(FX_POS_001, candidate); }).not.toThrow(); expect(outcome!.decision.status).toBe("BLOCKED"); expect(outcome!.decision.blockers.some((item) => item.message.includes("parsed candidate structure is missing or incomplete"))).toBe(true); expect(outcome!.decisionValidation).toMatchObject({ valid: false, recomputed_status: "BLOCKED" }); });
  it("non-object candidate is deterministically invalid/BLOCKED without throwing", () => { const candidate = null as unknown as GuardrailsSecurityDecision; expect(() => validateGuardrailsSecurityDecision(candidate, FX_POS_001)).not.toThrow(); expect(validateGuardrailsSecurityDecision(candidate, FX_POS_001)).toMatchObject({ valid: false, recomputed_status: "BLOCKED" }); expect(() => gateGuardrailsSecurity(FX_POS_001, candidate)).not.toThrow(); expect(gateGuardrailsSecurity(FX_POS_001, candidate)).toMatchObject({ decision: { status: "BLOCKED" }, decisionValidation: { valid: false, recomputed_status: "BLOCKED" } }); });
});

describe("real S12→S10→S09 path and isolation T91-T105", () => {
  it("metadata-only discovery and exactly one lazy S13L load are real", async () => { let loads = 0; const entries = referenceSkillCatalogEntries.map((entry) => entry.descriptor.id === GUARDRAILS_SECURITY_SKILL_ID ? { descriptor: entry.descriptor, load_definition: async () => { loads += 1; return entry.load_definition(); } } : entry); const provider = new LocalReferenceSkillProvider(entries); const output = await planGuardrailsSecurity(FX_POS_001, { baseDefinition: guardrailsSecurityHost, skillProvider: provider, modelProvider, capabilityProvider }); const descriptor = entries.find((entry) => entry.descriptor.id === GUARDRAILS_SECURITY_SKILL_ID)!.descriptor as unknown as Record<string, unknown>; expect(descriptor.rules).toBeUndefined(); expect(output.skillLoaded).toBe(true); expect(loads).toBe(1); });
  it("unchanged S10 compile and S09 run return a parsed valid candidate", async () => { const output = await run(FX_POS_001, true); expect(output.run.outcome).toBe("SUCCESS"); expect(output.materializedDefinition.id).toContain("s13l"); expect(output.candidate.status).toBe("ALLOW"); expect(output.decisionValidation.valid).toBe(true); });
  it("provider is truth-blind and frozen truth is production-blind", () => { const providerSource = readFileSync("tests/guardrails-security/fixtures.ts", "utf8"), truthSource = readFileSync("tests/guardrails-security/fixtureTruth.ts", "utf8"), inputSource = readFileSync("tests/guardrails-security/fixtureInputs.ts", "utf8"), imports = `${truthSource}\n${inputSource}`.split("\n").filter((line) => line.startsWith("import ")).join("\n"); expect(DeterministicGuardrailsSecurityModelProvider.PROVIDER_LABEL).toMatch(/no frozen truth/); expect(providerSource).not.toMatch(/fixtureTruth|withSkill\s*[=:]|SKILL_ID.*(?:if|switch)|fixture[_-]?id.*(?:if|switch)/i); expect(imports).not.toMatch(/fixtures|Provider|synthesize|parse|gate|compare|evaluate/i); expect(truthSource).not.toMatch(/(?:synthesizeGuardrails|gateGuardrails|compareGuardrails|planGuardrails)\s*\(/i); });
  it("exactly 30 unique atomic ownership IDs exist", () => { const ids = GUARDRAILS_SECURITY_COMPARISON_ASSERTIONS.filter((item) => item.category !== "REGRESSION_CROSS_CUTTING").map((item) => item.id); expect(GUARDRAILS_SECURITY_ATOMIC_ASSERTION_COUNT).toBe(30); expect(ids).toHaveLength(30); expect(new Set(ids).size).toBe(30); const observations = extractGuardrailsSecurityAssertionObservations(faithful(FX_POS_004)); expect(ids.every((id) => Object.hasOwn(observations, id))).toBe(true); const source = readFileSync(join(sourceDir, "compareGuardrailsSecurityRuns.ts"), "utf8"); for (const id of ids) expect(source.split(`\"${id}\"`).length - 1).toBe(1); });
});

describe("canonical fixtures, OI-A, safety and boundaries T106-T112", () => {
  it.each(ALL_POSITIVE_INPUTS.map((input, index) => [`FX-POS-${String(index + 1).padStart(3, "0")}`, input] as const))("%s validates with its canonical status", (_id, input) => { const decision = faithful(input); expect(validateGuardrailsSecurityDecision(decision, input).valid).toBe(true); expect(decision.status).toBe(input === FX_POS_008 ? "APPROVAL_REQUIRED" : "ALLOW"); });
  it.each(ALL_NEGATIVE_FIXTURES)("$id fails closed as $expected", ({ input, decision, expected }) => expect(gateGuardrailsSecurity(input, decision).decision.status).toBe(expected));
  it("raw grouped OI-A contributions and eight unsafe counters meet DEEP thresholds", async () => { const baseline = [], skill = []; for (const input of ALL_POSITIVE_INPUTS) { const b = await run(input, false), s = await run(input, true); baseline.push({ input, candidateDecision: b.candidate }); skill.push({ input, candidateDecision: s.candidate }); } const comparison = compareGuardrailsSecurityRuns(baseline, skill, FROZEN_GUARDRAILS_SECURITY_FIXTURE_TRUTH); expect({ baseline: [comparison.baseline.correct, comparison.baseline.total_assertions], skill: [comparison.skill.correct, comparison.skill.total_assertions], baseline_hard: [comparison.baseline.hard_invariant_correct, comparison.baseline.hard_invariant_total], skill_hard: [comparison.skill.hard_invariant_correct, comparison.skill.hard_invariant_total], delta: comparison.dimension_specific_total_delta, improved: comparison.improved_dimensions }).toEqual({ baseline: [120, 248], skill: [248, 248], baseline_hard: [392, 400], skill_hard: [400, 400], delta: 128, improved: ["SD-001", "SD-002", "SD-003", "SD-004", "SD-005", "SD-006", "SD-007", "SD-008"] }); expect(comparison.skill.unsafe_counters).toEqual({ auth_bypass: 0, cross_tenant_authority: 0, overbroad_capability: 0, destructive_approval_bypass: 0, secret_value_propagation: 0, untrusted_instruction_elevation: 0, sensitive_data_overdisclosure: 0, provider_or_future_stage_binding: 0 }); for (const dimension of comparison.improved_dimensions) { const evidence = comparison.dimension_improvements[dimension]; expect(evidence).toMatchObject({ delta: 16, scored_assertions: 3, single_assertion_contributions: { [`SD${Number(dimension.slice(-3))}-A`]: 8, [`SD${Number(dimension.slice(-3))}-B`]: 8, [`SD${Number(dimension.slice(-3))}-C`]: 0 }, max_single_assertion_share: 0.5 }); } expect(comparison.hard_invariant_regressed).toBe(false); expect(comparison.meets_threshold).toBe(true); });
  it("all 36 named negative conditions are represented exactly once", () => { expect(ALL_NEGATIVE_FIXTURES).toHaveLength(36); expect(new Set(ALL_NEGATIVE_FIXTURES.map((fixture) => fixture.id)).size).toBe(36); expect(ALL_NEGATIVE_FIXTURES.map((fixture) => fixture.condition)).toEqual(NEGATIVE_CONDITIONS); });
  it("provider/future/prior rewrite candidates block", () => { for (const index of [30, 31, 32, 33, 34, 35]) expect(gateGuardrailsSecurity(ALL_NEGATIVE_FIXTURES[index].input, ALL_NEGATIVE_FIXTURES[index].decision).decision.status).toBe("BLOCKED"); });
  it("append-only catalog, package/Core and adjacent-stage boundaries remain intact", () => { expect(referenceSkillCatalogEntries).toHaveLength(19); expect(referenceSkillCatalogEntries[13].descriptor.id).toBe("intelligence.frontend-product-surface.s13k"); expect(referenceSkillCatalogEntries[14].descriptor.id).toBe(GUARDRAILS_SECURITY_SKILL_ID); expect(referenceSkillCatalogEntries[15].descriptor.id).toBe("intelligence.qa-debugging.s13m"); expect(referenceSkillCatalogEntries[16].descriptor.id).toBe("intelligence.agent-evals.s13n"); expect(referenceSkillCatalogEntries[17].descriptor.id).toBe("intelligence.async-reliability.s13o"); expect(referenceSkillCatalogEntries[18].descriptor.id).toBe("intelligence.observability-ai-systems.s13p"); expect(JSON.parse(readFileSync("package.json", "utf8")).dependencies).toEqual({ "better-sqlite3": "^13.0.3" }); const source = readdirSync(sourceDir).filter((name) => name.endsWith(".ts")).map((name) => readFileSync(join(sourceDir, name), "utf8")).join("\n"); expect(source).not.toMatch(/from ["'](?:auth0|okta|vault|express|hono|fastify|jsonwebtoken|jose)|createServer|setTimeout\(|fetch\(/); expect(readdirSync("src/intelligence").some((name) => /delivery|deployment|capability-registry/i.test(name))).toBe(false); });
});

class CorruptParsedCandidateProvider implements ModelProvider { constructor(private readonly inner: DeterministicGuardrailsSecurityModelProvider) {} async decide(request: ModelDecisionRequest): Promise<ModelDecisionResult> { const result = await this.inner.decide(request); if (result.status !== "SUCCESS" || result.decision.type !== "FINISH") return result; const candidate = result.decision.output.data as unknown as GuardrailsSecurityDecision; candidate.atomic.identity.authentication_result = "FAIL"; candidate.spec_refs.push("marker:parsed-corrupt-candidate"); candidate.status = "ALLOW"; return result; } }
describe("actual parsed candidate anti-substitution regression", () => { it("parsed corrupt candidate survives to deterministic gate and blocks", async () => { const output = await planGuardrailsSecurity(FX_POS_001, { baseDefinition: guardrailsSecurityHost, skillProvider, modelProvider: new CorruptParsedCandidateProvider(modelProvider), capabilityProvider }); expect(output.candidate.spec_refs).toContain("marker:parsed-corrupt-candidate"); expect(output.decision.spec_refs).toContain("marker:parsed-corrupt-candidate"); expect(output.decision.atomic.identity.authentication_result).toBe("FAIL"); expect(output.decision.status).toBe("BLOCKED"); }); });
class IncompleteParsedCandidateProvider implements ModelProvider { constructor(private readonly inner: DeterministicGuardrailsSecurityModelProvider) {} async decide(request: ModelDecisionRequest): Promise<ModelDecisionResult> { const result = await this.inner.decide(request); if (result.status !== "SUCCESS" || result.decision.type !== "FINISH") return result; const candidate = result.decision.output.data as unknown as Record<string, unknown>; delete candidate.blockers; candidate.status = "ALLOW"; return result; } }
describe("actual parsed candidate structural regression", () => { it("parsed incomplete candidate reaches the total shape guard and returns BLOCKED without throwing", async () => { const output = await planGuardrailsSecurity(FX_POS_001, { baseDefinition: guardrailsSecurityHost, skillProvider, modelProvider: new IncompleteParsedCandidateProvider(modelProvider), capabilityProvider }); expect(output.candidate).not.toHaveProperty("blockers"); expect(output.decision.status).toBe("BLOCKED"); expect(output.decisionValidation).toMatchObject({ valid: false, recomputed_status: "BLOCKED" }); }); });
