import type { GuardrailsSecurityDecision, SecurityCheckResult } from "../../src/intelligence/guardrails-security/types.js";

export const DIMENSION_OBSERVATION_IDS = Array.from({ length: 10 }, (_, dimension) => ["A", "B", "C"].map((suffix) => `SD${dimension + 1}-${suffix}`)).flat();
export const OBSERVATION_ISOLATION_DECISION: GuardrailsSecurityDecision = {
  status: "ALLOW", task_ref: "probe:task", spec_refs: ["probe:spec"],
  atomic: {
    identity: { authentication_result: "PASS", provenance_result: "PASS", public_mode_result: "NOT_APPLICABLE" }, scope: { authorization_result: "PASS", tenant_isolation_result: "PASS", confused_deputy_result: "PASS" }, capability: { allowlist_result: "PASS", side_effect_result: "PASS", least_privilege_result: "PASS" }, action: { impact_result: "PASS", approval_result: "PASS", recovery_result: "PASS" }, secrets: { no_secret_value_result: "PASS", reference_result: "PASS", propagation_result: "PASS" }, content: { instruction_data_result: "PASS", indirect_injection_result: "PASS", authority_conflict_result: "PASS" }, data: { minimization_result: "PASS", disclosure_result: "PASS", memory_logging_result: "PASS" }, enforcement: { point_result: "PASS", freshness_result: "PASS", fail_closed_result: "PASS" }, traceability: { source_refs_result: "PASS", evidence_result: "PASS", blocker_traceability_result: "PASS" }, boundary: { provider_neutral_result: "PASS", future_stage_result: "PASS", prior_contract_result: "PASS" },
  },
  blockers: [], approval_requirements: [], permitted_capability_ids: [], permitted_side_effects: ["NONE"], allowed_disclosure_field_refs: [], enforcement_required: false, enforcement_point: "NOT_APPLICABLE",
  acceptance: [{ id: "probe:acceptance", condition: "probe", verification_method: "CONTRACT_TEST", evidence_expected: "probe" }], evidence_required: [{ kind: "SECURITY_CHECK", description: "probe" }],
};
const next = (value: SecurityCheckResult): SecurityCheckResult => value === "PASS" ? "FAIL" : "PASS";
export const OBSERVATION_ATOMIC_MUTATIONS: Record<string, (decision: GuardrailsSecurityDecision) => void> = {
  "SD1-A": (d) => { d.atomic.identity.authentication_result = next(d.atomic.identity.authentication_result); }, "SD1-B": (d) => { d.atomic.identity.provenance_result = next(d.atomic.identity.provenance_result); }, "SD1-C": (d) => { d.atomic.identity.public_mode_result = next(d.atomic.identity.public_mode_result); },
  "SD2-A": (d) => { d.atomic.scope.authorization_result = next(d.atomic.scope.authorization_result); }, "SD2-B": (d) => { d.atomic.scope.tenant_isolation_result = next(d.atomic.scope.tenant_isolation_result); }, "SD2-C": (d) => { d.atomic.scope.confused_deputy_result = next(d.atomic.scope.confused_deputy_result); },
  "SD3-A": (d) => { d.atomic.capability.allowlist_result = next(d.atomic.capability.allowlist_result); }, "SD3-B": (d) => { d.atomic.capability.side_effect_result = next(d.atomic.capability.side_effect_result); }, "SD3-C": (d) => { d.atomic.capability.least_privilege_result = next(d.atomic.capability.least_privilege_result); },
  "SD4-A": (d) => { d.atomic.action.impact_result = next(d.atomic.action.impact_result); }, "SD4-B": (d) => { d.atomic.action.approval_result = next(d.atomic.action.approval_result); }, "SD4-C": (d) => { d.atomic.action.recovery_result = next(d.atomic.action.recovery_result); },
  "SD5-A": (d) => { d.atomic.secrets.no_secret_value_result = next(d.atomic.secrets.no_secret_value_result); }, "SD5-B": (d) => { d.atomic.secrets.reference_result = next(d.atomic.secrets.reference_result); }, "SD5-C": (d) => { d.atomic.secrets.propagation_result = next(d.atomic.secrets.propagation_result); },
  "SD6-A": (d) => { d.atomic.content.instruction_data_result = next(d.atomic.content.instruction_data_result); }, "SD6-B": (d) => { d.atomic.content.indirect_injection_result = next(d.atomic.content.indirect_injection_result); }, "SD6-C": (d) => { d.atomic.content.authority_conflict_result = next(d.atomic.content.authority_conflict_result); },
  "SD7-A": (d) => { d.atomic.data.minimization_result = next(d.atomic.data.minimization_result); }, "SD7-B": (d) => { d.atomic.data.disclosure_result = next(d.atomic.data.disclosure_result); }, "SD7-C": (d) => { d.atomic.data.memory_logging_result = next(d.atomic.data.memory_logging_result); },
  "SD8-A": (d) => { d.atomic.enforcement.point_result = next(d.atomic.enforcement.point_result); }, "SD8-B": (d) => { d.atomic.enforcement.freshness_result = next(d.atomic.enforcement.freshness_result); }, "SD8-C": (d) => { d.atomic.enforcement.fail_closed_result = next(d.atomic.enforcement.fail_closed_result); },
  "SD9-A": (d) => { d.atomic.traceability.source_refs_result = next(d.atomic.traceability.source_refs_result); }, "SD9-B": (d) => { d.atomic.traceability.evidence_result = next(d.atomic.traceability.evidence_result); }, "SD9-C": (d) => { d.atomic.traceability.blocker_traceability_result = next(d.atomic.traceability.blocker_traceability_result); },
  "SD10-A": (d) => { d.atomic.boundary.provider_neutral_result = next(d.atomic.boundary.provider_neutral_result); }, "SD10-B": (d) => { d.atomic.boundary.future_stage_result = next(d.atomic.boundary.future_stage_result); }, "SD10-C": (d) => { d.atomic.boundary.prior_contract_result = next(d.atomic.boundary.prior_contract_result); },
};

