import type { SkillDefinition } from "../../../core/skill/index.js";
import {
  BACKEND_API_ENGINEERING_QUALITY_CONTRACT_REF,
  BACKEND_API_ENGINEERING_SKILL_ID,
} from "../../backend-api-engineering/constants.js";

/** Mechanical SkillDefinition projection of the committed S13I Part A. */
export const backendApiEngineeringS13I: SkillDefinition = {
  id: BACKEND_API_ENGINEERING_SKILL_ID,
  version: "1.0.0",
  description: "Produce a framework-neutral, provider-neutral backend HTTP API engineering decision for exactly one bounded operation, without implementing a web server or application endpoint.",
  applies_when: {
    task_kinds: ["backend-api-engineering", "http-api-contract", "endpoint-design"],
    signals: ["request validation", "auth boundary", "application service", "data port", "response schema", "safe error", "idempotency", "pagination"],
    exclusions: ["web server implementation", "framework binding", "database schema", "auth provider", "retry runtime", "observability vendor", "capability registry"],
  },
  inputs: [{ name: "backend_api_engineering_input", description: "One bounded BackendApiEngineeringInput with operation, request/response/error/auth/service/data/side-effect/observability/compatibility and acceptance/evidence contracts.", required: true, schema: { type: "object" } }],
  outputs: [{ name: "backend_api_engineering_decision", description: "A deterministic-gateable BackendApiEngineeringDecision with READY or BLOCKED status.", required: true, schema: { type: "object" } }],
  requires: {
    skills: [],
    capabilities: [],
    context_sources: ["CURRENT_API_TASK", "APPROVED_SPEC", "API_POLICY", "AUTH_BOUNDARY_INPUT", "ACCEPTANCE_EVIDENCE"],
    quality_contract_refs: [BACKEND_API_ENGINEERING_QUALITY_CONTRACT_REF],
  },
  rules: [
    { id: "BAE-R1", level: "MUST", statement: "One decision covers exactly one bounded API operation and task." },
    { id: "BAE-R2", level: "MUST", statement: "HTTP semantics remain framework-neutral and provider-neutral; no router, controller, framework, server, or provider binding is allowed." },
    { id: "BAE-R3", level: "MUST", statement: "Thin transport only: extract, validate and explicitly normalize, establish auth context, invoke authorization, invoke an application-service contract, map output/errors, and observe endpoint outcome." },
    { id: "BAE-R4", level: "MUST", statement: "Every consumed request field is declared; unknown fields reject by default and additional fields require an explicit bounded declaration." },
    { id: "BAE-R5", level: "MUST", statement: "No implicit coercion: normalization is explicit and always fails closed with REJECT." },
    { id: "BAE-R6", level: "MUST", statement: "Body-bearing operations declare accepted content types and a positive maximum body size; S13I invents no default." },
    { id: "BAE-R7", level: "MUST", statement: "Output validation mandatory: every externally reachable response variant has id, status, condition and schema." },
    { id: "BAE-R8", level: "MUST", statement: "External errors use stable codes, compatible HTTP status and safe messages, with no internal cause." },
    { id: "BAE-R9", level: "MUST", statement: "No response leakage of stack traces, raw SQL, secrets, credentials, tokens, private keys, internal paths, or undeclared upstream payloads." },
    { id: "BAE-R10", level: "MUST", statement: "Transport invokes an application-service contract and never embeds business/domain decisions." },
    { id: "BAE-R11", level: "MUST", statement: "No direct SQL, ORM, data-port or provider persistence call from transport; persistence needs are abstract logical data-port requirements." },
    { id: "BAE-R12", level: "MUST", statement: "S13J owns schema, table, column, index, migration, query plan and transaction mechanism; S13I may declare logical atomicity only." },
    { id: "BAE-R13", level: "MUST", statement: "Authentication mode is explicit: PUBLIC or AUTHENTICATED." },
    { id: "BAE-R14", level: "MUST", statement: "Authorization precedes every protected service effect or disclosure." },
    { id: "BAE-R15", level: "MUST", statement: "Client identity is not authority; client user, owner, tenant, account, role and permission fields are non-authoritative hints." },
    { id: "BAE-R16", level: "MUST", statement: "RESOURCE_REQUIRED declares a non-NONE scope and a provider-neutral trusted scope source." },
    { id: "BAE-R17", level: "MUST", statement: "Side effects classified as READ_ONLY, IDEMPOTENT_WRITE, NON_IDEMPOTENT_WRITE, or EXTERNAL_SIDE_EFFECT." },
    { id: "BAE-R18", level: "MUST", statement: "Idempotency handoff is required for caller-retryable duplicate-prone effects; S13O owns retry and storage mechanics." },
    { id: "BAE-R19", level: "MUST", statement: "Endpoint-local observability required for request id, operation, duration, outcome and safe error code." },
    { id: "BAE-R20", level: "MUST", statement: "Safe logging forbids raw headers/body and secret, token, credential, cookie, private-key or PII fields unless bounded allowlist/redaction semantics make them safe." },
    { id: "BAE-R21", level: "MUST", statement: "Breaking change must be explicit; an existing contract cannot silently use NEW and an unapproved break cannot be READY." },
    { id: "BAE-R22", level: "MUST", statement: "An unbounded list requires pagination or an explicit bounded-cardinality rationale." },
    { id: "BAE-R23", level: "MUST", statement: "Filter and sort fields are explicit request-field allowlists, never SQL expressions." },
    { id: "BAE-R24", level: "MUST", statement: "Rate limiting is a requirement reference only; 429 needs a policy ref and S13I implements no limiter." },
    { id: "BAE-R25", level: "MUST", statement: "OpenAPI is an optional derivative, never the authoritative source of the S13I structured contract." },
    { id: "BAE-R26", level: "MUST", statement: "No concrete framework, auth-provider, database/ORM/provider, observability-vendor or live transport binding." },
    { id: "BAE-R27", level: "MUST", statement: "No S14/S13J/S13L/S13O/S13P pull-forward; only explicit provider-neutral seams and handoff refs are allowed." },
    { id: "BAE-R28", level: "MUST", statement: "Acceptance/evidence preserved exactly; do not weaken, drop, invent, or claim completion evidence." },
    { id: "BAE-R29", level: "MUST", statement: "Inputs are immutable; all output projections are cloned and independently validated." },
    { id: "BAE-R30", level: "MUST", statement: "The canonical Skill runtime has no capabilities, performs no HTTP/network/DB side effect, starts no server, and returns only decision data." },
  ],
  procedure: [
    { id: "BAE-P1", title: "Bound the operation", instruction: "Validate one task_ref, one operation_id and immutable source refs.", requires: ["backend_api_engineering_input"], produces: ["bounded_operation"] },
    { id: "BAE-P2", title: "Validate request", instruction: "Validate declared fields, unknown policy, explicit normalization and body bounds.", requires: ["bounded_operation"], produces: ["request_design"] },
    { id: "BAE-P3", title: "Validate auth", instruction: "Derive provider-neutral authentication, authorization, scope and non-authoritative identity fields.", requires: ["request_design"], produces: ["auth_design"] },
    { id: "BAE-P4", title: "Separate service and data", instruction: "Keep transport thin, service transport-neutral and data ports logical/provider-neutral.", requires: ["auth_design"], produces: ["service_data_design"] },
    { id: "BAE-P5", title: "Validate responses", instruction: "Require schema-bound response variants and output validation.", requires: ["service_data_design"], produces: ["response_design"] },
    { id: "BAE-P6", title: "Validate errors", instruction: "Require stable safe errors/status mappings and reject never-leak classes.", requires: ["response_design"], produces: ["error_design"] },
    { id: "BAE-P7", title: "Classify side effects", instruction: "Derive side-effect/idempotency contract and S13O handoff without implementing reliability mechanics.", requires: ["service_data_design"], produces: ["side_effect_design"] },
    { id: "BAE-P8", title: "Validate observability", instruction: "Require endpoint-local safe observability and reject raw logging/vendor bindings.", requires: ["error_design"], produces: ["observability_design"] },
    { id: "BAE-P9", title: "Validate compatibility", instruction: "Validate explicit compatibility, pagination/rationale and filter/sort allowlists.", requires: ["request_design"], produces: ["compatibility_design"] },
    { id: "BAE-P10", title: "Preserve evidence", instruction: "Copy acceptance and allowed evidence requirements exactly.", requires: ["backend_api_engineering_input"], produces: ["traceability"] },
    { id: "BAE-P11", title: "Recompute invariants", instruction: "Recompute every hard boundary and final status; never trust candidate status/booleans.", requires: ["request_design", "auth_design", "service_data_design", "response_design", "error_design", "side_effect_design", "observability_design", "compatibility_design"], produces: ["gated_decision"] },
    { id: "BAE-P12", title: "Stop at S13I", instruction: "Return the decision only; do not start a server, call a provider, or implement S13J/S13L/S13O/S13P/S14.", requires: ["gated_decision"], produces: ["backend_api_engineering_decision"] },
  ],
  verification: [
    { id: "BAE-V1", kind: "DETERMINISTIC", criterion: "One bounded immutable operation and source refs are preserved.", evidence_required: true },
    { id: "BAE-V2", kind: "DETERMINISTIC", criterion: "Request/body/normalization validation fails closed.", evidence_required: true },
    { id: "BAE-V3", kind: "DETERMINISTIC", criterion: "Auth/resource boundary precedes effects and client identity is non-authoritative.", evidence_required: true },
    { id: "BAE-V4", kind: "DETERMINISTIC", criterion: "Transport/service/data-port boundaries contain no framework or persistence implementation.", evidence_required: true },
    { id: "BAE-V5", kind: "DETERMINISTIC", criterion: "Response/output/error/no-leak contracts pass.", evidence_required: true },
    { id: "BAE-V6", kind: "DETERMINISTIC", criterion: "Side-effect/idempotency seam passes without S13O mechanics.", evidence_required: true },
    { id: "BAE-V7", kind: "DETERMINISTIC", criterion: "Endpoint observability and safe logging pass without vendor binding.", evidence_required: true },
    { id: "BAE-V8", kind: "DETERMINISTIC", criterion: "Compatibility, pagination, filter/sort and rate-limit reference checks pass.", evidence_required: true },
    { id: "BAE-V9", kind: "DETERMINISTIC", criterion: "Acceptance/evidence is preserved and status is recomputed rather than trusted.", evidence_required: true },
    { id: "BAE-V10", kind: "DETERMINISTIC", criterion: "S12 metadata discovery/lazy load, S10 compile and S09 run are exercised with a caller AgentDefinition.", evidence_required: true },
    { id: "BAE-V11", kind: "DETERMINISTIC", criterion: "Built-in Node HTTP realism fixture is loopback-only, ephemeral and disposed.", evidence_required: true },
    { id: "BAE-V12", kind: "SEMANTIC", criterion: "OI-A-safe Skill-vs-no-Skill scoring passes with dimension-specific raw evidence.", evidence_required: true },
  ],
  permissions: { allowed_capabilities: [], allowed_side_effects: ["NONE"], deny_unlisted_capabilities: true },
  evals: ["evals/s13i/backend-api-engineering-positive", "evals/s13i/backend-api-engineering-negative", "evals/s13i/backend-api-engineering-skill-comparison"],
};
