import type { SkillDefinition } from "../../../core/skill/index.js";
import { POSTGRES_DATA_MODELING_QUALITY_CONTRACT_REF, POSTGRES_DATA_MODELING_SKILL_ID } from "../../postgres-data-modeling/constants.js";

const statements = [
  "One decision represents one bounded modeling task.",
  "SKILL_ONLY: no dedicated S13J AgentDefinition or Core branch.",
  "No live PostgreSQL side effect: no connection, SQL, migration, credentials, pool, or server lifecycle.",
  "Schema, version, extensions and search_path assumptions are explicit.",
  "Safe identifiers are lower_snake_case, unquoted, schema-qualified, and at most 63 UTF-8 bytes.",
  "Every persisted table has PK.",
  "Natural keys require stable immutable domain proof.",
  "UUID versus bigint follows approved generation topology.",
  "Relationship integrity is explicit through FK unless the reference is approved external.",
  "CASCADE and SET NULL require explicit lifecycle proof.",
  "Nullability follows required-at-insert and lifecycle intent.",
  "Concurrency-critical uniqueness belongs in DB.",
  "Row-local deterministic invariants use CHECK when safe.",
  "Multi-tenancy is optional and never invented.",
  "RLS is never invented and policy design remains S13L-owned.",
  "Real instants use timestamptz.",
  "Exact money is not floating point.",
  "Evolving status avoids PostgreSQL enum by default.",
  "JSONB cannot hide relational integrity, joins, uniqueness, sorting, or independent updates.",
  "Arrays are only for bounded atomic collections.",
  "Indexes come from access patterns.",
  "Do not duplicate PK/UNIQUE indexes.",
  "Critical high-cardinality access paths require justified support or explicit runtime evidence.",
  "Composite B-tree order follows equality, range, and order query shape.",
  "Partial, expression, and INCLUDE indexes need exact query justification.",
  "Queries are bounded with stable pagination order.",
  "Avoid N+1 plans.",
  "Actual EXPLAIN and index use are future runtime evidence, never fabricated.",
  "Atomic groups become transaction boundaries.",
  "Prefer constraints over stronger isolation.",
  "SERIALIZABLE requires retry handoff to S13O.",
  "Multiple row locks require deterministic lock ordering.",
  "Advisory locks require an approved exceptional need.",
  "Existing schema evolution defaults to expand/contract.",
  "Destructive migration requires approval and recovery evidence.",
  "Populated-table required-field changes require bounded backfill and validation.",
  "Large or hot migration lock and rewrite risk is explicit.",
  "Concurrent index creation is forbidden inside a regular transaction block.",
  "Rollback may be a safe roll-forward recovery plan.",
  "Race prevention is database constraint or transaction backed, never service pre-check only.",
  "Triggers are not default and require explicit justification.",
  "Derived DDL has no ambient search_path dependency.",
  "PostgreSQL extensions are explicit and never silently introduced.",
  "Sensitive data requires an approved S13L storage policy reference.",
  "The structured model is authoritative and DDL is deterministic derived preview.",
  "Acceptance/evidence preserved without invention or weakening.",
  "Inputs immutable, including S13I snapshots.",
  "Recompute invariants, blockers and status; do not trust candidate READY claims.",
  "No future-stage pull-forward of S13K, S13L, S13O, S13R, or S14 implementation.",
  "S07 SQLite MemoryProvider remains separate from application PostgreSQL modeling.",
];

export const postgresDataModelingS13J: SkillDefinition = {
  id: POSTGRES_DATA_MODELING_SKILL_ID,
  version: "1.0.0",
  description: "Produce one safe PostgreSQL application data-modeling decision and deterministic DDL preview without executing PostgreSQL.",
  applies_when: { task_kinds: ["postgres-data-modeling", "relational-schema", "database-migration-design"], signals: ["schema", "primary key", "foreign key", "index", "query plan", "transaction", "migration"], exclusions: ["live database execution", "ORM", "migration runner", "credentials", "deployment"] },
  inputs: [{ name: "postgres_data_modeling_input", description: "One immutable PostgresDataModelingInput.", required: true, schema: { type: "object" } }],
  outputs: [{ name: "postgres_data_modeling_decision", description: "A deterministic-gateable READY or BLOCKED structured decision.", required: true, schema: { type: "object" } }],
  requires: { skills: [], capabilities: [], context_sources: ["APPROVED_DATA_INTENT", "APPROVED_SPEC", "ACCESS_PATTERNS", "COMPATIBILITY_CONSTRAINTS", "ATOMICITY_INTENT", "ACCEPTANCE_EVIDENCE"], quality_contract_refs: [POSTGRES_DATA_MODELING_QUALITY_CONTRACT_REF] },
  rules: statements.map((statement, index) => ({ id: `PDM-R${index + 1}`, level: "MUST" as const, statement })),
  procedure: [
    ["PDM-P1", "Bound input", "Validate one task, schema target, entities, relationships and immutable source refs."],
    ["PDM-P2", "Design identities", "Choose safe PK strategies and relational column types from approved facts."],
    ["PDM-P3", "Design integrity", "Derive FK, uniqueness, nullability and CHECK constraints."],
    ["PDM-P4", "Design access", "Derive non-redundant indexes from concrete query patterns."],
    ["PDM-P5", "Check queries", "Reject unbounded, unstable, unknown-field and N+1 shapes; expose runtime evidence gaps."],
    ["PDM-P6", "Design transactions", "Map atomic groups and concurrency invariants without implementing retries."],
    ["PDM-P7", "Plan migrations", "Use expand/backfill/validate/cutover/contract semantics with explicit risk."],
    ["PDM-P8", "Preserve boundaries", "Carry security, reliability, deployment and runtime work as explicit handoffs."],
    ["PDM-P9", "Gate candidate", "Recompute hard invariants and terminal status from the actual parsed candidate."],
    ["PDM-P10", "Render DDL", "Render deterministic schema-qualified preview only after structured validation."],
    ["PDM-P11", "Stop at S13J", "Return decision data without DB/provider/future-stage execution."],
  ].map(([id, title, instruction]) => ({ id, title, instruction, requires: ["postgres_data_modeling_input"], produces: [id.toLowerCase()] })),
  verification: [...Array(12)].map((_, index) => ({ id: `PDM-V${index + 1}`, kind: index === 11 ? "SEMANTIC" as const : "DETERMINISTIC" as const, criterion: `S13J canonical verification group ${index + 1} passes with honest evidence.`, evidence_required: true })),
  permissions: { allowed_capabilities: [], allowed_side_effects: ["NONE"], deny_unlisted_capabilities: true },
  evals: ["evals/s13j/postgres-data-modeling-positive", "evals/s13j/postgres-data-modeling-negative", "evals/s13j/postgres-data-modeling-skill-comparison"],
};
