import type { FrozenPostgresFixtureTruth } from "../../src/intelligence/postgres-data-modeling/index.js";
import type { PostgresDataModelingInput } from "../../src/intelligence/postgres-data-modeling/types.js";
import { ALL_POSITIVE_INPUTS } from "./fixtures.js";

const typeMap: Record<string, string> = { IDENTIFIER: "text", TEXT: "text", BOOLEAN: "boolean", INTEGER: "bigint", DECIMAL: "numeric", MONEY: "numeric(19,4)", DATE: "date", INSTANT: "timestamptz", LOCAL_DATETIME: "timestamp without time zone", STATUS: "text", JSON_DOCUMENT: "jsonb", ATOMIC_LIST: "text[]", BINARY: "bytea" };
const byId = <T extends { id: string }>(items: T[]): T[] => [...items].sort((a, b) => a.id.localeCompare(b.id));

/** Independent frozen oracle: it imports no production synthesizer/provider/evaluator helper. */
function truthFor(input: PostgresDataModelingInput): FrozenPostgresFixtureTruth {
  const entities = byId(input.entities.filter((entity) => entity.persisted));
  const columns = entities.flatMap((entity) => byId([
    { id: `${entity.id}.id`, name: "id", type: entity.identity.distributed_generation_required || entity.identity.external_preallocation_required ? "uuid" : "bigint", nullable: false, sensitivity: "NONE" },
    ...entity.fields.map((field) => ({ id: field.id, name: field.logical_name, type: typeMap[field.semantic_type], nullable: !field.required_at_insert, sensitivity: field.sensitivity })),
  ]).map((column) => ({ table: entity.id, ...column })));
  const indexRows = input.query_patterns.map((query) => { const equality = query.predicates.filter((predicate) => predicate.operator === "EQ" || predicate.operator === "IN").map((predicate) => predicate.field_ref); const range = query.predicates.filter((predicate) => predicate.operator === "RANGE" || predicate.operator === "PREFIX").map((predicate) => predicate.field_ref); const ordered = query.order_by.map((order) => order.field_ref).filter((ref) => !equality.includes(ref) && !range.includes(ref)); return { id: `idx_${query.id}`, table: query.entity_ref, unique: false, method: "BTREE", keys: [...equality, ...range, ...ordered], order: [...equality.map(() => "ASC"), ...range.map(() => "ASC"), ...query.order_by.filter((order) => ordered.includes(order.field_ref)).map((order) => order.direction)] }; }).sort((a, b) => a.id.localeCompare(b.id));
  const queryRows = [...input.query_patterns].sort((a, b) => a.id.localeCompare(b.id));
  const migration = input.mode === "GREENFIELD"
    ? [{ id: "migration-create", phase: "EXPAND", mode: "REQUIRED", destructive: false, lock: "LOW", rewrite: "LOW", bounded: true, approval: null, recovery: [] }, ...indexRows.filter((index) => input.query_patterns.find((query) => `idx_${query.id}` === index.id)!.cardinality === "HIGH").map((index) => ({ id: `migration-${index.id}`, phase: "EXPAND", mode: "FORBIDDEN", destructive: false, lock: "LOW", rewrite: "LOW", bounded: true, approval: null, recovery: [] }))]
    : [{ id: "migration-expand", phase: "EXPAND", mode: "OPTIONAL", destructive: false, lock: input.migration_compatibility.large_or_hot_entities.length ? "MEDIUM" : "LOW", rewrite: "LOW", bounded: true, approval: null, recovery: input.migration_compatibility.recovery_evidence_refs }, { id: "migration-backfill", phase: "BACKFILL", mode: "OPTIONAL", destructive: false, lock: "LOW", rewrite: "MEDIUM", bounded: true, approval: null, recovery: input.migration_compatibility.recovery_evidence_refs }, { id: "migration-validate", phase: "VALIDATE", mode: "OPTIONAL", destructive: false, lock: "LOW", rewrite: "LOW", bounded: true, approval: null, recovery: input.migration_compatibility.recovery_evidence_refs }, ...indexRows.map((index) => ({ id: `migration-${index.id}`, phase: "EXPAND", mode: "FORBIDDEN", destructive: false, lock: "LOW", rewrite: "LOW", bounded: true, approval: null, recovery: [] }))];
  const transactions = input.atomicity_intent.requirement === "ATOMIC_GROUP_REQUIRED" ? [{ id: "tx-atomic-group", operations: input.atomicity_intent.logical_operation_refs, isolation: "READ_COMMITTED", lock: "NONE", order: [], retry: null, invariants: input.atomicity_intent.source_refs }] : [];
  return Object.freeze({ task_ref: input.task_ref, expected_assertions: Object.freeze({
    "SD1-A": entities.map((entity) => ({ id: entity.id, schema: input.target.schema_name, name: entity.logical_name })), "SD1-B": true, "SD1-C": entities.map((entity) => ({ id: entity.id, strategy: entity.identity.distributed_generation_required || entity.identity.external_preallocation_required ? "SURROGATE_UUID" : "SURROGATE_BIGINT", refs: [`${entity.id}.id`] })),
    "SD2-A": input.relationships.filter((rel) => rel.integrity_required && !rel.external_reference).map((rel) => ({ table: rel.from_entity_ref, id: rel.id, from: rel.from_field_refs, to_table: rel.to_entity_ref, to: rel.to_field_refs, delete: rel.preferred_delete_action ?? "NO_ACTION", update: "NO_ACTION" })), "SD2-B": columns.map((column) => ({ id: column.id, nullable: column.nullable })), "SD2-C": entities.map((entity) => ({ id: entity.id, unique: entity.identity.natural_key_candidates.filter((key) => key.domain_unique).map((key) => key.field_refs), checks: entity.fields.filter((field) => field.semantic_type === "STATUS" && field.closed_stable_values?.length).map((field) => `${field.logical_name} IN (${field.closed_stable_values!.map((value) => `'${value}'`).join(", ")})`) })),
    "SD3-A": columns.map((column) => ({ id: column.id, type: column.type })), "SD3-B": columns.map((column) => ({ id: column.id, sensitivity: column.sensitivity })), "SD3-C": [],
    "SD4-A": indexRows.map(({ id, table, unique, method }) => ({ id, table, unique, method })), "SD4-B": indexRows.map(({ id, keys, order }) => ({ id, keys, order, predicate: null, expression: null })), "SD4-C": { rejected: [], missing: [] },
    "SD5-A": queryRows.map((query) => ({ id: query.id, status: query.runtime_plan_evidence_required ? "RUNTIME_EVIDENCE_REQUIRED" : "STATIC_PASS" })), "SD5-B": queryRows.map((query) => ({ id: query.id, indexes: [`idx_${query.id}`], blockers: [] })), "SD5-C": queryRows.map((query) => ({ id: query.id, runtime: query.runtime_plan_evidence_required ? ["future EXPLAIN evidence via S14"] : [] })),
    "SD6-A": transactions.map(({ id, operations }) => ({ id, operations })), "SD6-B": transactions.map(({ id, isolation, lock }) => ({ id, isolation, lock })), "SD6-C": transactions.map(({ id, order, retry, invariants }) => ({ id, order, retry, invariants })),
    "SD7-A": input.mode === "GREENFIELD" ? "GREENFIELD" : "EXPAND_CONTRACT", "SD7-B": [...migration].sort((a, b) => a.id.localeCompare(b.id)).map(({ id, phase, mode, destructive }) => ({ id, phase, mode, destructive })), "SD7-C": [...migration].sort((a, b) => a.id.localeCompare(b.id)).map(({ id, lock, rewrite, bounded, approval, recovery }) => ({ id, lock, rewrite, bounded, approval, recovery })),
    "SD8-A": entities.map((entity) => ({ id: entity.id, rls: entity.tenant_scope_required && input.target.rls_mode === "REQUIRED_BY_UPSTREAM" })), "SD8-B": entities.map((entity) => ({ id: entity.id, schema: input.target.schema_name })), "SD8-C": { extensions: input.target.extensions, versions: [] },
    "SD9-A": { task: input.task_ref, specs: input.spec_refs }, "SD9-B": input.acceptance, "SD9-C": input.evidence_required,
    "SD10-A": { s13l: [], s13o: [], s13r: ["migration rollout execution"], s14: ["PostgreSQL runtime capability and plan inspection"] }, "SD10-B": input.query_patterns.filter((query) => query.runtime_plan_evidence_required).map((query) => query.id), "SD10-C": { status: "READY", blockers: [] }, "XC-A": true,
  }) });
}

export const FROZEN_POSTGRES_FIXTURE_TRUTH = Object.freeze(ALL_POSITIVE_INPUTS.map(truthFor));
