import type { AgentDefinition, ModelDecisionRequest, ModelDecisionResult, ModelProvider } from "../../src/core/agent/index.js";
import { POSTGRES_DATA_MODELING_INPUT_MARKER, derivePostgresProfileFromRules, synthesizePostgresDataModelingDecision, type PostgresDataModelingDecision, type PostgresDataModelingInput } from "../../src/intelligence/postgres-data-modeling/index.js";
import { postgresDataModelingS13J } from "../../src/intelligence/skills/index.js";

const OUTPUT_SCHEMA = { type: "object", required: ["summary"], properties: { summary: { type: "string" }, data: {}, evidence_refs: { type: "array" } }, additionalProperties: false };
export const postgresModelingHost: AgentDefinition = {
  id: "s13j-generic-skill-host", role: "generic-skill-host", objective: "Execute one caller-selected Intelligence Skill and return structured decision data.",
  model_policy: { routing_class: "QUALITY", require_structured_decisions: true, allow_provider_substitution: true },
  context_policy: { retrieval_mode: "BOUNDED", max_context_tokens: 16000, max_items: 50, allowed_sources: ["CURRENT_TASK", "EXPLICIT_SPEC", "VERIFIED_HANDOFF"], require_source_refs: true },
  state_schema: { type: "object", additionalProperties: false, properties: { selected: { type: "string" } } }, tools: [], skills: [postgresDataModelingS13J.id], capabilities: [],
  memory_policy: { retrieve: false, remember_candidate: false, commit_verified_memory: false, search_history: false, promotion_policy: "DISABLED" }, permissions: { allowed_side_effects: ["NONE"], deny_unlisted_capabilities: true }, delegation: { allowed: false }, limits: { max_turns: 3, timeout_ms: 15000 }, termination: { require_terminal_outcome: true, require_explanation: true }, output_schema: structuredClone(OUTPUT_SCHEMA), rubric: { quality_contract_ref: "S13J_POSTGRES_DATA_MODELING_DEEP" }, evals: ["evals/s13j/host-run"],
};
const field = (id: string, logical_name: string, semantic_type: PostgresDataModelingInput["entities"][number]["fields"][number]["semantic_type"], required = true): PostgresDataModelingInput["entities"][number]["fields"][number] => ({ id, logical_name, semantic_type, required_at_insert: required, mutable: logical_name !== "id", sensitivity: "NONE", queryable_independently: true, source_refs: ["spec:data"] });
export function basePostgresInput(): PostgresDataModelingInput {
  return {
    task_ref: "TASK-DB-001", spec_refs: ["spec:data"], mode: "GREENFIELD", target: { schema_name: "app", major_version: 16, extensions: [], rls_mode: "NOT_REQUESTED" },
    entities: [
      { id: "account", logical_name: "accounts", persisted: true, fields: [field("account.email", "email", "TEXT")], identity: { distributed_generation_required: false, external_preallocation_required: false, association_identity: false, natural_key_candidates: [{ field_refs: ["account.email"], domain_unique: true, stable: true, immutable: true, source_refs: ["spec:data"] }], source_refs: ["spec:data"] }, tenant_scope_required: false, audit_requirements: { created_at_required: false, updated_at_required: false, soft_delete_required: false }, source_refs: ["spec:data"] },
      { id: "entry", logical_name: "entries", persisted: true, fields: [field("entry.account_id", "account_id", "IDENTIFIER"), field("entry.title", "title", "TEXT"), field("entry.created_at", "created_at", "INSTANT")], identity: { distributed_generation_required: false, external_preallocation_required: false, association_identity: false, natural_key_candidates: [], source_refs: ["spec:data"] }, tenant_scope_required: false, audit_requirements: { created_at_required: true, updated_at_required: false, soft_delete_required: false }, source_refs: ["spec:data"] },
    ],
    relationships: [{ id: "entry_account_fk", from_entity_ref: "entry", from_field_refs: ["entry.account_id"], to_entity_ref: "account", to_field_refs: ["account.id"], integrity_required: true, external_reference: false, child_may_outlive_parent: false, orphan_valid: false, preferred_delete_action: "RESTRICT", source_refs: ["spec:data"] }],
    data_access_requirements: [{ id: "entries.list", kind: "LIST", entity_ref: "entry", field_intent_refs: ["entry.account_id", "entry.created_at"], source_refs: ["spec:data"] }], atomicity_intent: { requirement: "NONE", logical_operation_refs: [], source_refs: [] },
    query_patterns: [{ id: "entries_by_account", operation_ref: "entries.list", entity_ref: "entry", joins: [], predicates: [{ field_ref: "entry.account_id", operator: "EQ" }], order_by: [{ field_ref: "entry.created_at", direction: "DESC" }], pagination: "KEYSET", max_rows: 100, potentially_unbounded: true, n_plus_one_shape: false, cardinality: "HIGH", criticality: "HIGH", runtime_plan_evidence_required: true, source_refs: ["spec:data"] }],
    migration_compatibility: { external_consumers_exist: false, backward_compatible_required: false, destructive_change_approved: false, recovery_evidence_refs: [], populated_entities: [], large_or_hot_entities: [] },
    acceptance: [{ id: "AC-DB-1", condition: "Model preserves integrity and bounded access.", verification_method: "contract tests", evidence_expected: "validated structured decision" }], evidence_required: [{ kind: "CONTRACT_TEST", description: "S13J deterministic validation" }, { kind: "QUERY_PLAN_FUTURE", description: "Future PostgreSQL EXPLAIN evidence" }],
  };
}
const clone = <T>(value: T): T => structuredClone(value);
export const FX_POS_001 = basePostgresInput();
export const FX_POS_002 = (() => { const i = basePostgresInput(); i.task_ref = "TASK-DB-002"; i.target.rls_mode = "REQUIRED_BY_UPSTREAM"; for (const e of i.entities) { e.tenant_scope_required = true; const f = field(`${e.id}.tenant_id`, "tenant_id", "IDENTIFIER"); e.fields.unshift(f); e.tenant_field_ref = f.id; } return i; })();
export const FX_POS_003 = (() => { const i = basePostgresInput(); i.task_ref = "TASK-DB-003"; i.entities[1].fields.push(field("entry.amount", "amount", "MONEY"), { ...field("entry.status", "status", "STATUS"), closed_stable_values: ["OPEN", "CLOSED"] }, field("entry.local_start", "local_start", "LOCAL_DATETIME", false)); return i; })();
export const FX_POS_004 = (() => { const i = basePostgresInput(); i.task_ref = "TASK-DB-004"; i.query_patterns[0].max_rows = 50; return i; })();
export const FX_POS_005 = (() => { const i = basePostgresInput(); i.task_ref = "TASK-DB-005"; i.atomicity_intent = { requirement: "ATOMIC_GROUP_REQUIRED", logical_operation_refs: ["account.debit", "entry.create"], source_refs: ["spec:data"] }; return i; })();
export const FX_POS_006 = (() => { const i = basePostgresInput(); i.task_ref = "TASK-DB-006"; i.mode = "EVOLUTION"; i.migration_compatibility = { external_consumers_exist: true, backward_compatible_required: true, destructive_change_approved: false, recovery_evidence_refs: [], populated_entities: ["entry"], large_or_hot_entities: ["entry"] }; return i; })();
export const ALL_POSITIVE_INPUTS = [FX_POS_001, FX_POS_002, FX_POS_003, FX_POS_004, FX_POS_005, FX_POS_006];

function negative(index: number, mutate: (input: PostgresDataModelingInput, decision: PostgresDataModelingDecision) => void) { const input = basePostgresInput(); const decision = synthesizePostgresDataModelingDecision(input); mutate(input, decision); return { id: `FX-NEG-${String(index).padStart(3, "0")}`, input, decision }; }
const mutators: Array<(i: PostgresDataModelingInput, d: PostgresDataModelingDecision) => void> = [
  (i) => { i.task_ref = ""; }, (i) => { i.spec_refs = []; }, (i) => { i.target.schema_name = "Bad Schema"; }, (i) => { i.target.schema_name = "a".repeat(64); }, (i) => { i.entities[0].logical_name = "MixedCase"; },
  (i) => { i.entities[0].identity.preferred_strategy = "NATURAL"; i.entities[0].identity.natural_key_candidates[0].stable = false; }, (i) => { i.entities[0].identity.preferred_strategy = "NATURAL"; i.entities[0].identity.natural_key_candidates[0].immutable = false; }, (i) => { i.entities[0].identity.preferred_strategy = "COMPOSITE"; },
  (i) => { i.relationships[0].to_entity_ref = "missing"; }, (i) => { i.relationships[0].from_field_refs = ["missing"]; }, (i) => { i.relationships[0].integrity_required = true; i.relationships[0].external_reference = true; }, (i) => { i.relationships[0].preferred_delete_action = "CASCADE"; i.relationships[0].child_may_outlive_parent = true; },
  (i) => { i.relationships[0].preferred_delete_action = "SET_NULL"; i.relationships[0].orphan_valid = false; }, (i) => { i.entities[0].tenant_scope_required = true; }, (i) => { i.entities[0].tenant_field_ref = "account.tenant_id"; },
  (i) => { i.entities[0].fields[0].sensitivity = "SECRET"; }, (i) => { i.entities[0].fields[0].sensitivity = "CREDENTIAL_MATERIAL"; }, (i) => { i.entities[0].fields[0].semantic_type = "JSON_DOCUMENT"; }, (i) => { i.entities[0].fields[0].semantic_type = "ATOMIC_LIST"; },
  (i) => { i.query_patterns[0].pagination = "NONE"; }, (i) => { delete i.query_patterns[0].max_rows; }, (i) => { i.query_patterns[0].order_by = []; }, (i) => { i.query_patterns[0].n_plus_one_shape = true; }, (i) => { i.query_patterns[0].entity_ref = "missing"; }, (i) => { i.query_patterns[0].predicates[0].field_ref = "missing"; },
  (i) => { i.atomicity_intent = { requirement: "ATOMIC_GROUP_REQUIRED", logical_operation_refs: ["one"], source_refs: [] }; }, (i) => { i.mode = "EVOLUTION"; i.migration_compatibility.external_consumers_exist = true; }, (i) => { i.migration_compatibility.destructive_change_approved = true; }, (i) => { i.migration_compatibility.destructive_change_approved = true; i.migration_compatibility.destructive_approval_ref = "approval"; },
  (_i, d) => { d.schema_model.tables[0].primary_key.column_refs = []; }, (_i, d) => { d.schema_model.tables[1].foreign_keys = []; }, (_i, d) => { d.schema_model.tables[0].columns[0].postgres_type = "double precision"; }, (_i, d) => { d.index_plan.indexes = []; }, (_i, d) => { d.query_check_plan.checks[0].status = "STATIC_PASS"; d.query_check_plan.checks[0].runtime_evidence_required = []; },
  (_i, d) => { d.transaction_plan.transactions.push({ id: "bad", operation_refs: [], isolation: "SERIALIZABLE", lock_mode: "NONE", lock_order_refs: [], invariant_refs: [], source_refs: [] }); }, (_i, d) => { d.migration_plan.steps[0].destructive = true; }, (_i, d) => { d.schema_model.required_extensions = ["pgcrypto"]; }, (_i, d) => { d.acceptance = []; }, (_i, d) => { d.boundary_handoffs.deferred_to_s14 = []; }, (_i, d) => { d.status = "READY"; d.blockers = ["self certified"]; },
];
export const ALL_NEGATIVE_FIXTURES = mutators.map((mutate, index) => negative(index + 1, mutate));

function extractInput(goal: string): PostgresDataModelingInput { const at = goal.indexOf(POSTGRES_DATA_MODELING_INPUT_MARKER); if (at < 0) throw new Error("S13J input marker missing"); const after = goal.slice(at + POSTGRES_DATA_MODELING_INPUT_MARKER.length).trim(); const end = after.indexOf("\n\n"); return JSON.parse(end < 0 ? after : after.slice(0, end)) as PostgresDataModelingInput; }
export class DeterministicPostgresModelProvider implements ModelProvider {
  static readonly PROVIDER_LABEL = "deterministic/reference provider; bounded input and semantic rule prose only; no DB, network, credentials, frozen truth, ids, or arm flags";
  async decide(request: ModelDecisionRequest): Promise<ModelDecisionResult> { const input = extractInput(request.goal.statement); const profile = derivePostgresProfileFromRules([request.goal.statement]); const decision = synthesizePostgresDataModelingDecision(input, profile); return { status: "SUCCESS", decision: { type: "FINISH", rationale: "Derived from bounded input and materialized semantic rules.", output: { summary: `PostgreSQL modeling decision ${decision.status}`, data: decision as unknown as Record<string, unknown>, evidence_refs: [...input.spec_refs] } } }; }
}
export const cloneFixture = clone;
