import type { CapabilityListRequest, CapabilityProvider, ModelDecisionRequest, ModelDecisionResult, ModelProvider, ToolDescriptor, ToolInvocationRequest, ToolInvocationResult } from "../../src/core/agent/index.js";
import type { QaDebuggingDecision, QaDebuggingInput } from "../../src/intelligence/qa-debugging/types.js";
/** Truth-blind deterministic evaluator: derives solely from the bounded objective packet and materialized prose. */
function candidateFromObjective(objective: string): QaDebuggingDecision {
  const marker = "[[QA_DEBUGGING_INPUT]]\n"; const tail = objective.split(marker)[1]; if (!tail) throw new Error("Missing bounded QA input marker."); const input = JSON.parse(tail.split("\n\n[[QA_DEBUGGING_SKILL]]")[0]) as QaDebuggingInput; const skilled = objective.includes("Require discriminating causal evidence") && objective.includes("Actual parsed candidates are total-validated");
  const matched = input.reproduction_attempts.filter(a => a.outcome === "MATCHED_FAILURE" && a.observed_signature_ref === input.incident.failure_signature.signature_ref).length;
  const green = input.reproduction_attempts.filter(a => a.outcome === "NO_FAILURE").length;
  const reproduction_state = matched && green ? "INTERMITTENT" : matched ? "REPRODUCED" : input.reproduction_attempts.length ? "NOT_REPRODUCED" : "INSUFFICIENT_EVIDENCE";
  const hypothesis = input.hypotheses.find(h => h.failure_class !== "UNKNOWN"); const experiment = hypothesis && input.causal_experiments.find(e => e.hypothesis_ref === hypothesis.hypothesis_ref && e.outcome === "SUPPORTS_CAUSE" && e.held_constant_refs.length > 0);
  const root_cause = !hypothesis ? { state: "UNRESOLVED" as const, failure_class: "UNKNOWN" as const, supporting_evidence_refs: [], contradicting_evidence_refs: [], unresolved_alternative_refs: [] } : experiment ? { state: "PROVEN" as const, failure_class: hypothesis.failure_class, hypothesis_ref: hypothesis.hypothesis_ref, causal_factor_ref: experiment.changed_factor_ref, supporting_evidence_refs: hypothesis.supporting_evidence_refs, contradicting_evidence_refs: hypothesis.contradicting_evidence_refs, unresolved_alternative_refs: [] } : { state: "HYPOTHESIS" as const, failure_class: hypothesis.failure_class, hypothesis_ref: hypothesis.hypothesis_ref, supporting_evidence_refs: hypothesis.supporting_evidence_refs, contradicting_evidence_refs: hypothesis.contradicting_evidence_refs, unresolved_alternative_refs: [] };
  const hasFix = input.candidate_fix.kind !== "NO_FIX_YET"; const proven = root_cause.state === "PROVEN"; const aligned = proven && input.candidate_fix.causal_factor_refs.includes("factor:root"); const post = hasFix && input.regression.post_fix_outcome === "PASS" && input.regression.post_fix_revision_ref === input.candidate_fix.candidate_revision_ref; const suites = hasFix && input.suite_results.every(s => s.outcome === "PASS" && s.candidate_revision_ref === input.candidate_fix.candidate_revision_ref); const closure = reproduction_state !== "NOT_REPRODUCED" && reproduction_state !== "INSUFFICIENT_EVIDENCE" && proven && aligned && post && suites;
  const p = skilled ? "PASS" : "FAIL"; const atomic = { reproduction: { signature_result: matched ? p : "FAIL", setup_result: p, evidence_result: p }, evidence: { traceability_result: p, revision_binding_result: p, contradiction_result: p }, root_cause: { hypothesis_result: p, causal_evidence_result: proven ? p : "PASS", classification_result: proven ? p : "PASS" }, fix: { causal_alignment_result: hasFix ? (aligned ? p : "FAIL") : "PASS", minimal_scope_result: p, semantic_boundary_result: p }, regression: { pre_fix_result: p, post_fix_result: post ? p : "FAIL", candidate_binding_result: p }, suite: { selection_result: p, result_result: suites ? p : "FAIL", shared_surface_result: p }, stability: { intermittent_result: reproduction_state === "INTERMITTENT" ? "FAIL" : p, environment_result: p, retry_boundary_result: p }, security: { security_boundary_result: p, data_hygiene_result: p, override_result: p }, decision: { status_result: p, blocker_result: p, uncertainty_result: p }, boundary: { provider_neutral_result: p, future_stage_result: p, prior_contract_result: p } } as QaDebuggingDecision["atomic"];
  const status = skilled ? closure ? "FIX_VERIFIED" : proven && hasFix && reproduction_state !== "NOT_REPRODUCED" ? "FIX_CANDIDATE" : "INVESTIGATING" : "INVESTIGATING";
  return { status, task_ref: input.task_ref, incident_ref: input.incident.incident_ref, reproduction_state, root_cause, candidate_fix_kind: input.candidate_fix.kind, ...(input.candidate_fix.candidate_revision_ref ? { candidate_revision_ref: input.candidate_fix.candidate_revision_ref } : {}), required_suite_refs: input.suite_descriptors.map(s => s.suite_ref), atomic, blockers: [], next_action: status === "FIX_VERIFIED" ? "READY_FOR_INDEPENDENT_VERIFICATION" : reproduction_state === "NOT_REPRODUCED" ? "REPRODUCE_FAILURE" : proven ? "RUN_REGRESSION_BEFORE_AFTER" : "COLLECT_DISCRIMINATING_EVIDENCE", evidence_refs: input.evidence_records.map(e => e.evidence_ref), contradiction_refs: [], residual_unknowns: [], limitations: input.known_limitations, acceptance: input.acceptance, evidence_required: input.evidence_required };
}
export class QaCandidateTransportProvider implements ModelProvider { constructor(private readonly injectedCandidate?: unknown) {} async decide(request: ModelDecisionRequest): Promise<ModelDecisionResult> { return { status: "SUCCESS", decision: { type: "FINISH", rationale: "Derive bounded candidate from task evidence and materialized procedure.", output: { summary: "candidate", data: (this.injectedCandidate ?? candidateFromObjective(request.goal.statement)) as Record<string, unknown> } } }; } }
export class EmptyCapabilityProvider implements CapabilityProvider { async list_capabilities(_request?: CapabilityListRequest): Promise<ToolDescriptor[]> { return []; } async invoke(request: ToolInvocationRequest): Promise<ToolInvocationResult> { return { status: "BLOCKED", call_id: request.call_id, capability_id: request.capability_id, reason: "No capabilities are permitted for S13M.", duration_ms: 0 }; } }
