import type { QaDebuggingDecision, QaCheckResult } from "../../src/intelligence/qa-debugging/types.js";
import { candidateFor, baseQaInput } from "./fixtures.js";
export const DIMENSION_OBSERVATION_IDS = Array.from({ length: 10 }, (_, n) => ["A", "B", "C"].map((s) => `SD${n + 1}-${s}`)).flat();
export const OBSERVATION_ISOLATION_DECISION = candidateFor(baseQaInput("probe"));
const flip = (value: QaCheckResult): QaCheckResult => value === "PASS" ? "FAIL" : "PASS";
export const OBSERVATION_ATOMIC_MUTATIONS: Record<string, (d: QaDebuggingDecision) => void> = {
  "SD1-A": d => { d.atomic.reproduction.signature_result = flip(d.atomic.reproduction.signature_result); }, "SD1-B": d => { d.atomic.reproduction.setup_result = flip(d.atomic.reproduction.setup_result); }, "SD1-C": d => { d.atomic.reproduction.evidence_result = flip(d.atomic.reproduction.evidence_result); },
  "SD2-A": d => { d.atomic.evidence.traceability_result = flip(d.atomic.evidence.traceability_result); }, "SD2-B": d => { d.atomic.evidence.revision_binding_result = flip(d.atomic.evidence.revision_binding_result); }, "SD2-C": d => { d.atomic.evidence.contradiction_result = flip(d.atomic.evidence.contradiction_result); },
  "SD3-A": d => { d.atomic.root_cause.hypothesis_result = flip(d.atomic.root_cause.hypothesis_result); }, "SD3-B": d => { d.atomic.root_cause.causal_evidence_result = flip(d.atomic.root_cause.causal_evidence_result); }, "SD3-C": d => { d.atomic.root_cause.classification_result = flip(d.atomic.root_cause.classification_result); },
  "SD4-A": d => { d.atomic.fix.causal_alignment_result = flip(d.atomic.fix.causal_alignment_result); }, "SD4-B": d => { d.atomic.fix.minimal_scope_result = flip(d.atomic.fix.minimal_scope_result); }, "SD4-C": d => { d.atomic.fix.semantic_boundary_result = flip(d.atomic.fix.semantic_boundary_result); },
  "SD5-A": d => { d.atomic.regression.pre_fix_result = flip(d.atomic.regression.pre_fix_result); }, "SD5-B": d => { d.atomic.regression.post_fix_result = flip(d.atomic.regression.post_fix_result); }, "SD5-C": d => { d.atomic.regression.candidate_binding_result = flip(d.atomic.regression.candidate_binding_result); },
  "SD6-A": d => { d.atomic.suite.selection_result = flip(d.atomic.suite.selection_result); }, "SD6-B": d => { d.atomic.suite.result_result = flip(d.atomic.suite.result_result); }, "SD6-C": d => { d.atomic.suite.shared_surface_result = flip(d.atomic.suite.shared_surface_result); },
  "SD7-A": d => { d.atomic.stability.intermittent_result = flip(d.atomic.stability.intermittent_result); }, "SD7-B": d => { d.atomic.stability.environment_result = flip(d.atomic.stability.environment_result); }, "SD7-C": d => { d.atomic.stability.retry_boundary_result = flip(d.atomic.stability.retry_boundary_result); },
  "SD8-A": d => { d.atomic.security.security_boundary_result = flip(d.atomic.security.security_boundary_result); }, "SD8-B": d => { d.atomic.security.data_hygiene_result = flip(d.atomic.security.data_hygiene_result); }, "SD8-C": d => { d.atomic.security.override_result = flip(d.atomic.security.override_result); },
  "SD9-A": d => { d.atomic.decision.status_result = flip(d.atomic.decision.status_result); }, "SD9-B": d => { d.atomic.decision.blocker_result = flip(d.atomic.decision.blocker_result); }, "SD9-C": d => { d.atomic.decision.uncertainty_result = flip(d.atomic.decision.uncertainty_result); },
  "SD10-A": d => { d.atomic.boundary.provider_neutral_result = flip(d.atomic.boundary.provider_neutral_result); }, "SD10-B": d => { d.atomic.boundary.future_stage_result = flip(d.atomic.boundary.future_stage_result); }, "SD10-C": d => { d.atomic.boundary.prior_contract_result = flip(d.atomic.boundary.prior_contract_result); },
};
