import { FORBIDDEN_SENSITIVE_KEY, FUTURE_STAGE_PATTERN } from "./constants.js";
import type { CandidateFixKind, FailureClass, QaCheckResult, QaDebuggingAtomicDecision, QaDebuggingBlocker, QaDebuggingDecision, QaDebuggingInput, QaDebuggingNextAction, QaDebuggingStatus, QaDebuggingValidationResult, QaRootCauseAssessment, ReproductionState, RootCauseState, SuiteCheckOutcome } from "./types.js";

const statuses = ["INVESTIGATING", "FIX_CANDIDATE", "FIX_VERIFIED", "BLOCKED"] as const;
const checkResults = ["PASS", "FAIL", "NOT_APPLICABLE"] as const;
const reproductionOutcomes = ["MATCHED_FAILURE", "NO_FAILURE", "DIFFERENT_FAILURE", "BLOCKED"] as const;
const failureClasses = ["CODE", "TEST", "DATA", "CONFIGURATION", "ENVIRONMENT", "DEPENDENCY", "CONTRACT", "SECURITY_BOUNDARY", "UNKNOWN"] as const;
const rootStates = ["HYPOTHESIS", "PROVEN", "DISPROVEN", "UNRESOLVED"] as const;
const fixKinds = ["CODE_CHANGE", "TEST_CHANGE", "DATA_FIXTURE_CHANGE", "CONFIGURATION_CHANGE", "DEPENDENCY_CHANGE", "ENVIRONMENT_CHANGE", "NO_FIX_YET"] as const;
const suiteOutcomes = ["PASS", "FAIL", "NOT_RUN", "NOT_APPLICABLE"] as const;
const securityStatuses = ["ALLOW", "APPROVAL_REQUIRED", "BLOCKED", "NOT_APPLICABLE"] as const;
const suiteScopes = ["DIRECT_REGRESSION", "IMPACTED_MODULE", "CONTRACT_BOUNDARY", "SHARED_SURFACE", "FULL_SUITE"] as const;
const nextActions = ["REPRODUCE_FAILURE", "COLLECT_DISCRIMINATING_EVIDENCE", "RESOLVE_CONTRADICTION", "PREPARE_MINIMAL_FIX", "RUN_REGRESSION_BEFORE_AFTER", "RUN_RELEVANT_SUITE", "REQUEST_SEMANTIC_REAUTHOR", "REQUEST_SECURITY_OR_AUTHORITY_DECISION", "READY_FOR_INDEPENDENT_VERIFICATION", "STOP_BLOCKED"] as const;
const blockerCodes = ["INVALID_INPUT", "REQUIRED_EVIDENCE_UNAVAILABLE", "SECURITY_BOUNDARY_BLOCKED", "SEMANTIC_REAUTHOR_REQUIRED", "REQUIRED_AUTHORITY_OR_PERMISSION_MISSING", "FUTURE_STAGE_PULL_FORWARD", "PROHIBITED_SENSITIVE_PAYLOAD"] as const;
const asRecord = (v: unknown): v is Record<string, unknown> => v !== null && typeof v === "object" && !Array.isArray(v);
const text = (v: unknown): v is string => typeof v === "string" && v.trim().length > 0;
const strings = (v: unknown): v is string[] => Array.isArray(v) && v.every(text);
const known = (xs: readonly string[], v: unknown): boolean => typeof v === "string" && xs.includes(v);
const optionalText = (v: unknown): boolean => v === undefined || text(v);
const nonNegativeInteger = (v: unknown): v is number => typeof v === "number" && Number.isInteger(v) && v >= 0;
const uniqueStrings = (v: unknown): v is string[] => strings(v) && new Set(v).size === v.length;
const equalStrings = (actual: unknown, expected: readonly string[]): boolean => Array.isArray(actual) && actual.length === expected.length && actual.every((value, index) => value === expected[index]);
const materialDecisionFields = ["status", "task_ref", "incident_ref", "reproduction_state", "root_cause", "candidate_fix_kind", "candidate_revision_ref", "required_suite_refs", "atomic", "blockers", "next_action", "evidence_refs", "contradiction_refs", "residual_unknowns", "limitations", "acceptance", "evidence_required"] as const;
const check = (v: boolean): QaCheckResult => v ? "PASS" : "FAIL";
const clone = <T>(value: T): T => structuredClone(value);
const unique = (values: readonly string[]): string[] => [...new Set(values)];

function noSensitivePayload(value: unknown, seen = new Set<object>()): boolean {
  if (!value || typeof value !== "object") return true;
  if (seen.has(value as object)) return true; seen.add(value as object);
  if (Array.isArray(value)) return value.every((item) => noSensitivePayload(item, seen));
  return Object.entries(value).every(([key, item]) => !FORBIDDEN_SENSITIVE_KEY.test(key) && noSensitivePayload(item, seen));
}
function allAtomic(value: unknown): value is QaDebuggingAtomicDecision {
  if (!asRecord(value)) return false;
  const groups: Record<string, string[]> = { reproduction: ["signature_result", "setup_result", "evidence_result"], evidence: ["traceability_result", "revision_binding_result", "contradiction_result"], root_cause: ["hypothesis_result", "causal_evidence_result", "classification_result"], fix: ["causal_alignment_result", "minimal_scope_result", "semantic_boundary_result"], regression: ["pre_fix_result", "post_fix_result", "candidate_binding_result"], suite: ["selection_result", "result_result", "shared_surface_result"], stability: ["intermittent_result", "environment_result", "retry_boundary_result"], security: ["security_boundary_result", "data_hygiene_result", "override_result"], decision: ["status_result", "blocker_result", "uncertainty_result"], boundary: ["provider_neutral_result", "future_stage_result", "prior_contract_result"] };
  return Object.entries(groups).every(([group, leaves]) => asRecord(value[group]) && leaves.every((leaf) => known(checkResults, (value[group] as Record<string, unknown>)[leaf])));
}
function inputErrors(input: unknown): string[] {
  if (!asRecord(input)) return ["input must be an object"];
  const x = input; const errors: string[] = [];
  if (!text(x.task_ref) || !text(x.quality_contract_ref) || !strings(x.spec_refs)) errors.push("task/spec/quality contract references are required");
  const incident = asRecord(x.incident) ? x.incident : undefined;
  const signature = incident && asRecord(incident.failure_signature) ? incident.failure_signature : undefined;
  if (!incident || !text(incident.incident_ref) || !text(incident.expected_behavior) || !text(incident.observed_behavior) || !text(incident.baseline_revision_ref) || !strings(incident.affected_surface_refs) || !strings(incident.first_observed_evidence_refs) || !signature || !text(signature.signature_ref) || !optionalText(signature.normalized_code) || !optionalText(signature.normalized_message_ref) || !optionalText(signature.failing_check_ref)) errors.push("incident is malformed");
  if (!Array.isArray(x.environments) || x.environments.some((e) => !asRecord(e) || !text(e.environment_ref) || !strings(e.runtime_refs) || !optionalText(e.dependency_snapshot_ref) || !optionalText(e.configuration_snapshot_ref) || !optionalText(e.platform_ref) || !strings(e.required_environment_refs) || !strings(e.known_mismatch_refs) || !strings(e.evidence_refs))) errors.push("environments are malformed");
  if (!Array.isArray(x.evidence_records) || x.evidence_records.some((e) => !asRecord(e) || !text(e.evidence_ref) || !text(e.claim_ref) || !text(e.locator_ref) || !known(["SUPPORTS", "CONTRADICTS", "QUALIFIES"], e.relationship) || !known(["DIRECT_OBSERVATION", "PRIMARY", "SECONDARY", "STAKEHOLDER", "OTHER"], e.source_type) || typeof e.reproducible !== "boolean" || !optionalText(e.command_or_method) || !optionalText(e.observed_revision_ref) || !optionalText(e.observed_environment_ref) || !strings(e.limitations) || !strings(e.contradiction_refs))) errors.push("evidence records are malformed");
  if (!Array.isArray(x.reproduction_attempts) || x.reproduction_attempts.some((a) => !asRecord(a) || !text(a.attempt_ref) || !text(a.baseline_revision_ref) || !text(a.environment_ref) || !text(a.setup_ref) || !text(a.method_ref) || !known(reproductionOutcomes, a.outcome) || !optionalText(a.observed_signature_ref) || !optionalText(a.deterministic_seed_ref) || !optionalText(a.scheduling_or_timing_ref) || !strings(a.evidence_refs))) errors.push("reproduction attempts are malformed");
  if (!Array.isArray(x.hypotheses) || x.hypotheses.some((h) => !asRecord(h) || !text(h.hypothesis_ref) || !text(h.statement) || !known(failureClasses, h.failure_class) || !strings(h.predicted_observation_refs) || !strings(h.supporting_evidence_refs) || !strings(h.contradicting_evidence_refs))) errors.push("hypotheses are malformed");
  if (!Array.isArray(x.causal_experiments) || x.causal_experiments.some((e) => !asRecord(e) || !text(e.experiment_ref) || !text(e.hypothesis_ref) || !text(e.changed_factor_ref) || !strings(e.held_constant_refs) || !text(e.predicted_effect_ref) || !text(e.observed_effect_ref) || !known(["SUPPORTS_CAUSE", "CONTRADICTS_CAUSE", "INCONCLUSIVE"], e.outcome) || !strings(e.evidence_refs))) errors.push("causal experiments are malformed");
  const fix = asRecord(x.candidate_fix) ? x.candidate_fix : undefined;
  if (!fix || !known(fixKinds, fix.kind) || !strings(fix.changed_surface_refs) || !strings(fix.causal_factor_refs) || typeof fix.rationale !== "string" || !strings(fix.unrelated_change_refs) || !strings(fix.semantic_artifact_change_refs) || !strings(fix.security_boundary_change_refs) || !optionalText(fix.candidate_revision_ref) || !optionalText(fix.change_ref)) errors.push("candidate fix is malformed");
  else if (fix.kind === "NO_FIX_YET" ? Boolean(fix.candidate_revision_ref || fix.change_ref) : !text(fix.candidate_revision_ref) || !text(fix.change_ref)) errors.push("candidate revision/change relation is invalid");
  if (!asRecord(x.regression) || !text(x.regression.regression_check_ref) || !text(x.regression.pre_fix_revision_ref) || !optionalText(x.regression.post_fix_revision_ref) || !optionalText(x.regression.pre_fix_failure_signature_ref) || !text(x.regression.expected_failure_signature_ref) || !known(suiteOutcomes, x.regression.pre_fix_outcome) || !known(suiteOutcomes, x.regression.post_fix_outcome) || !strings(x.regression.evidence_refs)) errors.push("regression is malformed");
  const suiteShape = Array.isArray(x.suite_descriptors) && x.suite_descriptors.length > 0 && x.suite_descriptors.every((s) => asRecord(s) && text(s.suite_ref) && known(suiteScopes, s.scope) && strings(s.covered_surface_refs) && strings(s.covered_contract_refs));
  const resultShape = Array.isArray(x.suite_results) && x.suite_results.every((s) => asRecord(s) && text(s.suite_ref) && text(s.candidate_revision_ref) && text(s.environment_ref) && known(suiteOutcomes, s.outcome) && strings(s.evidence_refs) && [s.executed_check_count, s.passed_check_count, s.failed_check_count].every((n) => n === undefined || nonNegativeInteger(n)) && (s.executed_check_count === undefined || s.passed_check_count === undefined || s.failed_check_count === undefined || (nonNegativeInteger(s.executed_check_count) && nonNegativeInteger(s.passed_check_count) && nonNegativeInteger(s.failed_check_count) && s.passed_check_count + s.failed_check_count <= s.executed_check_count)));
  const stability = x.stability === undefined ? undefined : asRecord(x.stability) ? x.stability : undefined;
  const stabilityShape = x.stability === undefined || Boolean(stability && strings(stability.pre_fix_attempt_refs) && strings(stability.post_fix_attempt_refs) && strings(stability.limitation_refs) && [stability.matching_pre_fix_failure_count, stability.total_pre_fix_attempt_count, stability.matching_post_fix_failure_count, stability.total_post_fix_attempt_count].every(nonNegativeInteger) && nonNegativeInteger(stability.matching_pre_fix_failure_count) && nonNegativeInteger(stability.total_pre_fix_attempt_count) && nonNegativeInteger(stability.matching_post_fix_failure_count) && nonNegativeInteger(stability.total_post_fix_attempt_count) && stability.matching_pre_fix_failure_count <= stability.total_pre_fix_attempt_count && stability.matching_post_fix_failure_count <= stability.total_post_fix_attempt_count);
  const security = asRecord(x.security) ? x.security : undefined;
  const securityShape = Boolean(security && known(securityStatuses, security.status) && optionalText(security.security_decision_ref) && strings(security.protected_boundary_refs) && typeof security.candidate_preserves_boundary === "boolean" && strings(security.evidence_refs));
  if (!suiteShape || !resultShape || !stabilityShape || !securityShape) errors.push("suite, stability, or security is malformed");
  if (!Array.isArray(x.acceptance) || x.acceptance.some((a) => !asRecord(a) || !text(a.criterion_ref) || !text(a.description)) || !Array.isArray(x.evidence_required) || x.evidence_required.some((e) => !asRecord(e) || !text(e.requirement_ref) || !text(e.category) || !text(e.description)) || !strings(x.known_limitations)) errors.push("acceptance/evidence requirements are malformed");
  if (!noSensitivePayload(input)) errors.push("prohibited sensitive payload shape");
  return errors;
}
function evidenceSet(input: QaDebuggingInput): Set<string> { return new Set(input.evidence_records.map((e) => e.evidence_ref)); }
function refsResolve(input: QaDebuggingInput, refs: readonly string[]): boolean { const all = evidenceSet(input); return refs.every((ref) => all.has(ref)); }
function reproduction(input: QaDebuggingInput): ReproductionState {
  const valid = input.reproduction_attempts.filter((a) => a.baseline_revision_ref === input.incident.baseline_revision_ref && input.environments.some((e) => e.environment_ref === a.environment_ref && e.required_environment_refs.length > 0) && refsResolve(input, a.evidence_refs));
  const matching = valid.filter((a) => a.outcome === "MATCHED_FAILURE" && a.observed_signature_ref === input.incident.failure_signature.signature_ref);
  const nonmatching = valid.filter((a) => a.outcome === "NO_FAILURE");
  if (matching.length > 0 && nonmatching.length > 0) return "INTERMITTENT";
  if (matching.length > 0) return "REPRODUCED";
  return valid.length ? "NOT_REPRODUCED" : "INSUFFICIENT_EVIDENCE";
}
function rootCause(input: QaDebuggingInput): QaRootCauseAssessment {
  const candidate = input.hypotheses.find((h) => h.failure_class !== "UNKNOWN");
  if (!candidate) return { state: "UNRESOLVED", failure_class: "UNKNOWN", supporting_evidence_refs: [], contradicting_evidence_refs: [], unresolved_alternative_refs: [] };
  const experiments = input.causal_experiments.filter((e) => e.hypothesis_ref === candidate.hypothesis_ref);
  const supports = experiments.filter((e) => e.outcome === "SUPPORTS_CAUSE" && e.held_constant_refs.length > 0 && refsResolve(input, e.evidence_refs));
  const contradicts = experiments.filter((e) => e.outcome === "CONTRADICTS_CAUSE");
  const supportRefs = unique([...candidate.supporting_evidence_refs, ...supports.flatMap((e) => e.evidence_refs)]);
  const contraRefs = unique([...candidate.contradicting_evidence_refs, ...contradicts.flatMap((e) => e.evidence_refs)]);
  if (contradicts.length) return { state: "DISPROVEN", failure_class: candidate.failure_class, hypothesis_ref: candidate.hypothesis_ref, supporting_evidence_refs: supportRefs, contradicting_evidence_refs: contraRefs, unresolved_alternative_refs: [] };
  const unresolved = input.hypotheses.filter((h) => h.hypothesis_ref !== candidate.hypothesis_ref && h.failure_class !== "UNKNOWN" && h.contradicting_evidence_refs.length === 0).map((h) => h.hypothesis_ref);
  if (supports.length && refsResolve(input, supportRefs) && unresolved.length === 0) return { state: "PROVEN", failure_class: candidate.failure_class, hypothesis_ref: candidate.hypothesis_ref, causal_factor_ref: supports[0].changed_factor_ref, supporting_evidence_refs: supportRefs, contradicting_evidence_refs: contraRefs, unresolved_alternative_refs: [] };
  return { state: "HYPOTHESIS", failure_class: candidate.failure_class, hypothesis_ref: candidate.hypothesis_ref, supporting_evidence_refs: supportRefs, contradicting_evidence_refs: contraRefs, unresolved_alternative_refs: unresolved };
}
function deriveAtomic(input: QaDebuggingInput, rep: ReproductionState, cause: QaRootCauseAssessment, hard: QaDebuggingBlocker[]): QaDebuggingAtomicDecision {
  const candidate = input.candidate_fix; const hasFix = candidate.kind !== "NO_FIX_YET"; const kindMatchesClass: Record<Exclude<FailureClass, "UNKNOWN" | "SECURITY_BOUNDARY" | "CONTRACT">, CandidateFixKind> = { CODE: "CODE_CHANGE", TEST: "TEST_CHANGE", DATA: "DATA_FIXTURE_CHANGE", CONFIGURATION: "CONFIGURATION_CHANGE", ENVIRONMENT: "ENVIRONMENT_CHANGE", DEPENDENCY: "DEPENDENCY_CHANGE" }; const aligned = cause.state === "PROVEN" && Boolean(cause.causal_factor_ref && candidate.causal_factor_refs.includes(cause.causal_factor_ref) && kindMatchesClass[cause.failure_class as keyof typeof kindMatchesClass] === candidate.kind);
  const semantic = candidate.semantic_artifact_change_refs.length === 0 && candidate.security_boundary_change_refs.length === 0 && input.security.candidate_preserves_boundary;
  const pre = input.regression.pre_fix_outcome === "FAIL" && input.regression.pre_fix_failure_signature_ref === input.regression.expected_failure_signature_ref && input.regression.pre_fix_revision_ref === input.incident.baseline_revision_ref;
  const post = hasFix && input.regression.post_fix_outcome === "PASS" && input.regression.post_fix_revision_ref === candidate.candidate_revision_ref;
  const direct = input.suite_descriptors.some((s) => s.scope === "DIRECT_REGRESSION"); const impacted = input.suite_descriptors.some((s) => s.scope === "IMPACTED_MODULE" && s.covered_surface_refs.some((r) => input.incident.affected_surface_refs.includes(r)));
  const suites = hasFix && input.suite_descriptors.every((d) => input.suite_results.some((r) => r.suite_ref === d.suite_ref && r.outcome === "PASS" && r.candidate_revision_ref === candidate.candidate_revision_ref && input.environments.some((e) => e.environment_ref === r.environment_ref) && refsResolve(input, r.evidence_refs) && r.executed_check_count !== undefined && r.passed_check_count === r.executed_check_count && r.failed_check_count === 0));
  const intermittent = rep !== "INTERMITTENT" || Boolean(input.stability && input.stability.matching_pre_fix_failure_count > 0 && input.stability.total_pre_fix_attempt_count > 1 && input.stability.total_post_fix_attempt_count >= input.stability.total_pre_fix_attempt_count && input.stability.matching_post_fix_failure_count === 0 && input.stability.limitation_refs.length > 0);
  const contradictions = input.evidence_records.filter((e) => e.relationship === "CONTRADICTS").flatMap((e) => e.contradiction_refs.length ? e.contradiction_refs : [e.evidence_ref]);
  return { reproduction: { signature_result: check(rep === "REPRODUCED" || rep === "INTERMITTENT"), setup_result: check(input.environments.every((e) => e.required_environment_refs.length > 0)), evidence_result: check(input.reproduction_attempts.every((a) => refsResolve(input, a.evidence_refs))) }, evidence: { traceability_result: check(input.evidence_records.every((e) => text(e.locator_ref))), revision_binding_result: check(pre && (!hasFix || input.regression.post_fix_revision_ref === candidate.candidate_revision_ref)), contradiction_result: check(contradictions.length === 0) }, root_cause: { hypothesis_result: check(cause.state !== "PROVEN" || Boolean(cause.hypothesis_ref)), causal_evidence_result: check(cause.state !== "PROVEN" || Boolean(cause.causal_factor_ref && cause.supporting_evidence_refs.length)), classification_result: check(cause.state !== "PROVEN" || cause.failure_class !== "UNKNOWN") }, fix: { causal_alignment_result: check(!hasFix || aligned), minimal_scope_result: check(candidate.unrelated_change_refs.length === 0), semantic_boundary_result: check(semantic) }, regression: { pre_fix_result: check(pre), post_fix_result: check(post), candidate_binding_result: check(!hasFix || input.regression.post_fix_revision_ref === candidate.candidate_revision_ref) }, suite: { selection_result: check(direct && impacted), result_result: check(suites), shared_surface_result: check(!candidate.changed_surface_refs.some((r) => r.startsWith("shared:")) || input.suite_descriptors.some((s) => s.scope === "SHARED_SURFACE" || s.scope === "FULL_SUITE")) }, stability: { intermittent_result: check(intermittent), environment_result: check(input.environments.every((e) => e.required_environment_refs.length > 0)), retry_boundary_result: "PASS" }, security: { security_boundary_result: check(input.security.status !== "BLOCKED"), data_hygiene_result: check(noSensitivePayload(input)), override_result: check(input.security.status !== "BLOCKED" && input.security.status !== "APPROVAL_REQUIRED" && semantic) }, decision: { status_result: check(hard.length === 0), blocker_result: check(hard.length === 0), uncertainty_result: check(input.known_limitations.every(text)) }, boundary: { provider_neutral_result: "PASS", future_stage_result: check(!FUTURE_STAGE_PATTERN.test(JSON.stringify(input))), prior_contract_result: check(candidate.semantic_artifact_change_refs.length === 0) } };
}
function blockers(input: QaDebuggingInput, errors: string[]): QaDebuggingBlocker[] { const out: QaDebuggingBlocker[] = errors.map((message) => ({ code: message.includes("sensitive") ? "PROHIBITED_SENSITIVE_PAYLOAD" : "INVALID_INPUT", message, evidence_refs: [] })); if (input.security.status === "BLOCKED" || !input.security.candidate_preserves_boundary) out.push({ code: "SECURITY_BOUNDARY_BLOCKED", message: "S13L/security boundary remains blocking.", evidence_refs: input.security.evidence_refs }); if (input.security.status === "APPROVAL_REQUIRED") out.push({ code: "REQUIRED_AUTHORITY_OR_PERMISSION_MISSING", message: "S13L approval is not authorization.", evidence_refs: input.security.evidence_refs }); if (input.candidate_fix.semantic_artifact_change_refs.length) out.push({ code: "SEMANTIC_REAUTHOR_REQUIRED", message: "Semantic artifacts require their owning authoring gate.", evidence_refs: [] }); if (FUTURE_STAGE_PATTERN.test(JSON.stringify(input))) out.push({ code: "FUTURE_STAGE_PULL_FORWARD", message: "Future-stage implementation marker is forbidden in S13M.", evidence_refs: [] }); return out; }
export function deriveQaDebuggingDecision(raw: unknown): QaDebuggingDecision {
  const errors = inputErrors(raw); if (errors.length || !asRecord(raw)) return blockedInvalid(raw, errors);
  const input = raw as unknown as QaDebuggingInput; const hard = blockers(input, errors); const rep = reproduction(input); const cause = rootCause(input); const atomic = deriveAtomic(input, rep, cause, hard);
  const candidate = input.candidate_fix; const closure = (rep === "REPRODUCED" || rep === "INTERMITTENT") && cause.state === "PROVEN" && candidate.kind !== "NO_FIX_YET" && atomic.fix.causal_alignment_result === "PASS" && atomic.fix.minimal_scope_result === "PASS" && atomic.fix.semantic_boundary_result === "PASS" && atomic.regression.pre_fix_result === "PASS" && atomic.regression.post_fix_result === "PASS" && atomic.suite.selection_result === "PASS" && atomic.suite.result_result === "PASS" && atomic.suite.shared_surface_result === "PASS" && atomic.stability.intermittent_result === "PASS" && atomic.evidence.contradiction_result === "PASS";
  const fixReady = cause.state === "PROVEN" && candidate.kind !== "NO_FIX_YET" && atomic.fix.causal_alignment_result === "PASS" && atomic.fix.minimal_scope_result === "PASS" && atomic.fix.semantic_boundary_result === "PASS" && atomic.evidence.contradiction_result === "PASS" && (rep === "REPRODUCED" || rep === "INTERMITTENT");
  const status: QaDebuggingStatus = hard.length ? "BLOCKED" : closure ? "FIX_VERIFIED" : fixReady ? "FIX_CANDIDATE" : "INVESTIGATING";
  const next: QaDebuggingNextAction = hard.length ? (hard.some((b) => b.code === "SEMANTIC_REAUTHOR_REQUIRED") ? "REQUEST_SEMANTIC_REAUTHOR" : hard.some((b) => b.code.includes("SECURITY") || b.code.includes("AUTHORITY")) ? "REQUEST_SECURITY_OR_AUTHORITY_DECISION" : "STOP_BLOCKED") : rep === "INSUFFICIENT_EVIDENCE" || rep === "NOT_REPRODUCED" ? "REPRODUCE_FAILURE" : atomic.evidence.contradiction_result === "FAIL" ? "RESOLVE_CONTRADICTION" : cause.state !== "PROVEN" ? "COLLECT_DISCRIMINATING_EVIDENCE" : candidate.kind === "NO_FIX_YET" || atomic.fix.causal_alignment_result === "FAIL" || atomic.fix.minimal_scope_result === "FAIL" ? "PREPARE_MINIMAL_FIX" : atomic.regression.pre_fix_result === "FAIL" || atomic.regression.post_fix_result === "FAIL" || atomic.stability.intermittent_result === "FAIL" ? "RUN_REGRESSION_BEFORE_AFTER" : atomic.suite.result_result === "FAIL" || atomic.suite.selection_result === "FAIL" || atomic.suite.shared_surface_result === "FAIL" ? "RUN_RELEVANT_SUITE" : "READY_FOR_INDEPENDENT_VERIFICATION";
  return { status, task_ref: input.task_ref, incident_ref: input.incident.incident_ref, reproduction_state: rep, root_cause: cause, candidate_fix_kind: candidate.kind, ...(candidate.candidate_revision_ref ? { candidate_revision_ref: candidate.candidate_revision_ref } : {}), required_suite_refs: input.suite_descriptors.map((s) => s.suite_ref), atomic, blockers: hard, next_action: next, evidence_refs: unique(input.evidence_records.map((e) => e.evidence_ref)), contradiction_refs: unique(input.evidence_records.flatMap((e) => e.relationship === "CONTRADICTS" && e.contradiction_refs.length === 0 ? [e.evidence_ref] : e.contradiction_refs)), residual_unknowns: cause.unresolved_alternative_refs, limitations: clone(input.known_limitations), acceptance: clone(input.acceptance), evidence_required: clone(input.evidence_required) };
}
function blockedInvalid(raw: unknown, errors: string[]): QaDebuggingDecision { return { status: "BLOCKED", task_ref: asRecord(raw) && text(raw.task_ref) ? raw.task_ref : "invalid:task", incident_ref: "invalid:incident", reproduction_state: "INSUFFICIENT_EVIDENCE", root_cause: { state: "UNRESOLVED", failure_class: "UNKNOWN", supporting_evidence_refs: [], contradicting_evidence_refs: [], unresolved_alternative_refs: [] }, candidate_fix_kind: "NO_FIX_YET", required_suite_refs: [], atomic: failClosedAtomic(), blockers: errors.map((message) => ({ code: message.includes("sensitive") ? "PROHIBITED_SENSITIVE_PAYLOAD" : "INVALID_INPUT", message, evidence_refs: [] })), next_action: "STOP_BLOCKED", evidence_refs: [], contradiction_refs: [], residual_unknowns: ["Invalid input cannot support a decision."], limitations: [], acceptance: [], evidence_required: [] }; }
export function failClosedAtomic(): QaDebuggingAtomicDecision { const f = (): QaCheckResult => "FAIL"; return { reproduction: { signature_result: f(), setup_result: f(), evidence_result: f() }, evidence: { traceability_result: f(), revision_binding_result: f(), contradiction_result: f() }, root_cause: { hypothesis_result: f(), causal_evidence_result: f(), classification_result: f() }, fix: { causal_alignment_result: f(), minimal_scope_result: f(), semantic_boundary_result: f() }, regression: { pre_fix_result: f(), post_fix_result: f(), candidate_binding_result: f() }, suite: { selection_result: f(), result_result: f(), shared_surface_result: f() }, stability: { intermittent_result: f(), environment_result: f(), retry_boundary_result: f() }, security: { security_boundary_result: f(), data_hygiene_result: f(), override_result: f() }, decision: { status_result: f(), blocker_result: f(), uncertainty_result: f() }, boundary: { provider_neutral_result: f(), future_stage_result: f(), prior_contract_result: f() } }; }
export function validateQaDebuggingDecision(candidate: unknown, input: unknown): QaDebuggingValidationResult {
  const expected = deriveQaDebuggingDecision(input); const errors: string[] = []; const record = asRecord(candidate) ? candidate : undefined;
  const root = record && asRecord(record.root_cause) ? record.root_cause : undefined;
  const acceptanceShape = (value: unknown): boolean => Array.isArray(value) && value.every((a) => asRecord(a) && text(a.criterion_ref) && text(a.description));
  const evidenceRequirementShape = (value: unknown): boolean => Array.isArray(value) && value.every((e) => asRecord(e) && text(e.requirement_ref) && text(e.category) && text(e.description));
  const blockersShape = (value: unknown): boolean => Array.isArray(value) && value.every((b) => asRecord(b) && known(blockerCodes, b.code) && text(b.message) && strings(b.evidence_refs));
  if (!record || !known(statuses, record.status) || !text(record.task_ref) || !text(record.incident_ref) || !known(["REPRODUCED", "NOT_REPRODUCED", "INTERMITTENT", "INSUFFICIENT_EVIDENCE"], record.reproduction_state) || !allAtomic(record.atomic) || !root || !known(rootStates, root.state) || !known(failureClasses, root.failure_class) || !optionalText(root.hypothesis_ref) || !optionalText(root.causal_factor_ref) || !strings(root.supporting_evidence_refs) || !strings(root.contradicting_evidence_refs) || !strings(root.unresolved_alternative_refs) || !known(fixKinds, record.candidate_fix_kind) || !optionalText(record.candidate_revision_ref) || !uniqueStrings(record.required_suite_refs) || !blockersShape(record.blockers) || !known(nextActions, record.next_action) || !strings(record.evidence_refs) || !strings(record.contradiction_refs) || !strings(record.residual_unknowns) || !strings(record.limitations) || !acceptanceShape(record.acceptance) || !evidenceRequirementShape(record.evidence_required) || !noSensitivePayload(record)) errors.push("candidate structure is malformed");
  if (!errors.length && ((record!.status === "FIX_VERIFIED" || record!.status === "FIX_CANDIDATE") && root!.state !== "PROVEN")) errors.push("candidate status/root-cause combination is impossible");
  if (!errors.length && (record!.candidate_fix_kind !== expected.candidate_fix_kind || record!.candidate_revision_ref !== expected.candidate_revision_ref)) errors.push("candidate fix kind/revision relation is invalid");
  if (!errors.length && !equalStrings(record!.required_suite_refs, expected.required_suite_refs)) errors.push("candidate required suite references do not match input");
  if (!errors.length && materialDecisionFields.some((field) => JSON.stringify(record![field]) !== JSON.stringify(expected[field]))) errors.push("candidate material claims do not match deterministic evidence gate");
  const hard = { structural_validation_total: errors.length === 0, actual_candidate_gated: errors.length === 0, input_immutable: true, no_core_special_branch: true, capability_free: true };
  return { valid: errors.length === 0, errors, hard_invariants: hard, recomputed_status: expected.status };
}
/** Gates the parsed candidate itself. Invalid candidates never receive a synthesized faithful replacement. */
export function gateQaDebuggingCandidate(input: unknown, candidate: unknown): { decision: QaDebuggingDecision; candidate: unknown; decisionValidation: QaDebuggingValidationResult } { const validation = validateQaDebuggingDecision(candidate, input); return { decision: validation.valid ? clone(candidate as QaDebuggingDecision) : blockedInvalid(input, validation.errors), candidate, decisionValidation: validation }; }

/** HI-001..HI-050 are evaluated independently of candidate prose for each arm. */
export function evaluateQaDebuggingHardInvariants(input: QaDebuggingInput, decision: QaDebuggingDecision): Record<string, boolean> {
  const valid = validateQaDebuggingDecision(decision, input).valid; const fixed = decision.status === "FIX_VERIFIED"; const cause = decision.root_cause; const candidate = input.candidate_fix;
  const reproduced = decision.reproduction_state === "REPRODUCED" || decision.reproduction_state === "INTERMITTENT";
  const suiteSafe = decision.atomic.suite.selection_result === "PASS" && decision.atomic.suite.result_result === "PASS" && decision.atomic.suite.shared_surface_result === "PASS";
  const closureSafe = !fixed || (reproduced && cause.state === "PROVEN" && decision.atomic.regression.pre_fix_result === "PASS" && decision.atomic.regression.post_fix_result === "PASS" && suiteSafe);
  const noSemantic = candidate.semantic_artifact_change_refs.length === 0; const noSecurity = input.security.status === "ALLOW" && input.security.candidate_preserves_boundary;
  const refs = decision.evidence_refs.length > 0 && decision.evidence_refs.every((r) => evidenceSet(input).has(r));
  return {
    "HI-001": valid && text(input.incident.incident_ref), "HI-002": valid, "HI-003": valid, "HI-004": valid, "HI-005": !fixed || reproduced, "HI-006": !fixed || decision.atomic.reproduction.signature_result === "PASS", "HI-007": !fixed || input.regression.pre_fix_revision_ref === input.incident.baseline_revision_ref, "HI-008": input.environments.every((e) => e.required_environment_refs.length > 0), "HI-009": decision.reproduction_state !== "NOT_REPRODUCED" || !fixed, "HI-010": decision.reproduction_state !== "INTERMITTENT" || Boolean(input.stability),
    "HI-011": !fixed || cause.state === "PROVEN", "HI-012": cause.state !== "HYPOTHESIS" || !fixed, "HI-013": cause.state !== "PROVEN" || Boolean(cause.causal_factor_ref && cause.supporting_evidence_refs.length), "HI-014": cause.state !== "PROVEN" || input.causal_experiments.some((e) => e.outcome === "SUPPORTS_CAUSE" && e.held_constant_refs.length > 0), "HI-015": cause.state !== "PROVEN" || cause.failure_class !== "UNKNOWN", "HI-016": decision.contradiction_refs.every(text), "HI-017": !fixed || cause.state === "PROVEN", "HI-018": !fixed || decision.atomic.fix.causal_alignment_result === "PASS", "HI-019": !fixed || decision.atomic.fix.minimal_scope_result === "PASS", "HI-020": noSemantic || decision.status === "BLOCKED",
    "HI-021": noSecurity || decision.status === "BLOCKED", "HI-022": !fixed || decision.atomic.regression.pre_fix_result === "PASS", "HI-023": !fixed || decision.atomic.regression.post_fix_result === "PASS", "HI-024": !fixed || decision.atomic.regression.candidate_binding_result === "PASS", "HI-025": !fixed || decision.atomic.suite.selection_result === "PASS", "HI-026": !candidate.changed_surface_refs.some((r) => r.startsWith("shared:")) || decision.atomic.suite.shared_surface_result === "PASS", "HI-027": !fixed || decision.atomic.suite.result_result === "PASS", "HI-028": cause.state !== "PROVEN" || input.causal_experiments.length > 0, "HI-029": decision.reproduction_state !== "INTERMITTENT" || decision.atomic.stability.intermittent_result === "PASS" || !fixed, "HI-030": decision.atomic.stability.environment_result === "PASS",
    "HI-031": decision.atomic.stability.retry_boundary_result === "PASS", "HI-032": decision.atomic.boundary.future_stage_result === "PASS", "HI-033": decision.atomic.boundary.future_stage_result === "PASS", "HI-034": decision.atomic.boundary.future_stage_result === "PASS", "HI-035": decision.atomic.boundary.provider_neutral_result === "PASS", "HI-036": valid, "HI-037": valid, "HI-038": valid, "HI-039": refs, "HI-040": noSensitivePayload(input) && noSensitivePayload(decision),
    "HI-041": valid, "HI-042": decision.atomic.boundary.prior_contract_result === "PASS", "HI-043": decision.atomic.evidence.contradiction_result === "PASS" || !fixed, "HI-044": decision.limitations.every(text), "HI-045": decision.atomic.boundary.provider_neutral_result === "PASS", "HI-046": valid, "HI-047": valid, "HI-048": valid, "HI-049": valid, "HI-050": true,
  };
}
