export type QaDebuggingStatus = "INVESTIGATING" | "FIX_CANDIDATE" | "FIX_VERIFIED" | "BLOCKED";
export type QaCheckResult = "PASS" | "FAIL" | "NOT_APPLICABLE";
export type ReproductionState = "REPRODUCED" | "NOT_REPRODUCED" | "INTERMITTENT" | "INSUFFICIENT_EVIDENCE";
export type FailureClass = "CODE" | "TEST" | "DATA" | "CONFIGURATION" | "ENVIRONMENT" | "DEPENDENCY" | "CONTRACT" | "SECURITY_BOUNDARY" | "UNKNOWN";
export type RootCauseState = "HYPOTHESIS" | "PROVEN" | "DISPROVEN" | "UNRESOLVED";
export type SuiteCheckOutcome = "PASS" | "FAIL" | "NOT_RUN" | "NOT_APPLICABLE";
export type SecurityBoundaryStatus = "ALLOW" | "APPROVAL_REQUIRED" | "BLOCKED" | "NOT_APPLICABLE";
export type CandidateFixKind = "CODE_CHANGE" | "TEST_CHANGE" | "DATA_FIXTURE_CHANGE" | "CONFIGURATION_CHANGE" | "DEPENDENCY_CHANGE" | "ENVIRONMENT_CHANGE" | "NO_FIX_YET";
export type QaEvidenceRelationship = "SUPPORTS" | "CONTRADICTS" | "QUALIFIES";
export type QaEvidenceSourceType = "DIRECT_OBSERVATION" | "PRIMARY" | "SECONDARY" | "STAKEHOLDER" | "OTHER";
export type ReproductionAttemptOutcome = "MATCHED_FAILURE" | "NO_FAILURE" | "DIFFERENT_FAILURE" | "BLOCKED";
export type CausalExperimentOutcome = "SUPPORTS_CAUSE" | "CONTRADICTS_CAUSE" | "INCONCLUSIVE";
export type QaSuiteScope = "DIRECT_REGRESSION" | "IMPACTED_MODULE" | "CONTRACT_BOUNDARY" | "SHARED_SURFACE" | "FULL_SUITE";
export type QaDebuggingBlockerCode = "INVALID_INPUT" | "REQUIRED_EVIDENCE_UNAVAILABLE" | "SECURITY_BOUNDARY_BLOCKED" | "SEMANTIC_REAUTHOR_REQUIRED" | "REQUIRED_AUTHORITY_OR_PERMISSION_MISSING" | "FUTURE_STAGE_PULL_FORWARD" | "PROHIBITED_SENSITIVE_PAYLOAD";
export type QaDebuggingNextAction = "REPRODUCE_FAILURE" | "COLLECT_DISCRIMINATING_EVIDENCE" | "RESOLVE_CONTRADICTION" | "PREPARE_MINIMAL_FIX" | "RUN_REGRESSION_BEFORE_AFTER" | "RUN_RELEVANT_SUITE" | "REQUEST_SEMANTIC_REAUTHOR" | "REQUEST_SECURITY_OR_AUTHORITY_DECISION" | "READY_FOR_INDEPENDENT_VERIFICATION" | "STOP_BLOCKED";
export interface QaEvidenceRecordInput { evidence_ref: string; claim_ref: string; relationship: QaEvidenceRelationship; source_type: QaEvidenceSourceType; locator_ref: string; command_or_method?: string; observed_revision_ref?: string; observed_environment_ref?: string; reproducible: boolean; limitations: string[]; contradiction_refs: string[]; }
export interface QaIncidentInput { incident_ref: string; expected_behavior: string; observed_behavior: string; failure_signature: { signature_ref: string; normalized_code?: string; normalized_message_ref?: string; failing_check_ref?: string }; baseline_revision_ref: string; affected_surface_refs: string[]; first_observed_evidence_refs: string[]; }
export interface QaEnvironmentSnapshot { environment_ref: string; runtime_refs: string[]; dependency_snapshot_ref?: string; configuration_snapshot_ref?: string; platform_ref?: string; required_environment_refs: string[]; known_mismatch_refs: string[]; evidence_refs: string[]; }
export interface ReproductionAttempt { attempt_ref: string; baseline_revision_ref: string; environment_ref: string; setup_ref: string; method_ref: string; outcome: ReproductionAttemptOutcome; observed_signature_ref?: string; deterministic_seed_ref?: string; scheduling_or_timing_ref?: string; evidence_refs: string[]; }
export interface QaHypothesisInput { hypothesis_ref: string; statement: string; failure_class: FailureClass; predicted_observation_refs: string[]; supporting_evidence_refs: string[]; contradicting_evidence_refs: string[]; }
export interface QaCausalExperimentInput { experiment_ref: string; hypothesis_ref: string; changed_factor_ref: string; held_constant_refs: string[]; predicted_effect_ref: string; observed_effect_ref: string; outcome: CausalExperimentOutcome; evidence_refs: string[]; }
export interface QaRootCauseAssessment { state: RootCauseState; failure_class: FailureClass; hypothesis_ref?: string; causal_factor_ref?: string; supporting_evidence_refs: string[]; contradicting_evidence_refs: string[]; unresolved_alternative_refs: string[]; }
export interface QaCandidateFixInput { kind: CandidateFixKind; candidate_revision_ref?: string; change_ref?: string; changed_surface_refs: string[]; causal_factor_refs: string[]; rationale: string; unrelated_change_refs: string[]; semantic_artifact_change_refs: string[]; security_boundary_change_refs: string[]; }
export interface QaRegressionEvidenceInput { regression_check_ref: string; pre_fix_revision_ref: string; post_fix_revision_ref?: string; pre_fix_outcome: SuiteCheckOutcome; post_fix_outcome: SuiteCheckOutcome; pre_fix_failure_signature_ref?: string; expected_failure_signature_ref: string; evidence_refs: string[]; }
export interface QaSuiteDescriptorInput { suite_ref: string; scope: QaSuiteScope; covered_surface_refs: string[]; covered_contract_refs: string[]; }
export interface QaSuiteResultInput { suite_ref: string; candidate_revision_ref: string; environment_ref: string; outcome: SuiteCheckOutcome; executed_check_count?: number; passed_check_count?: number; failed_check_count?: number; evidence_refs: string[]; }
export interface QaStabilityEvidenceInput { pre_fix_attempt_refs: string[]; post_fix_attempt_refs: string[]; matching_pre_fix_failure_count: number; total_pre_fix_attempt_count: number; matching_post_fix_failure_count: number; total_post_fix_attempt_count: number; limitation_refs: string[]; }
export interface QaSecurityBoundaryInput { status: SecurityBoundaryStatus; security_decision_ref?: string; protected_boundary_refs: string[]; candidate_preserves_boundary: boolean; evidence_refs: string[]; }
export interface QaAcceptanceCriterionRef { criterion_ref: string; description: string; }
export interface QaEvidenceRequirementRef { requirement_ref: string; category: string; description: string; }
export interface QaDebuggingInput { task_ref: string; spec_refs: string[]; quality_contract_ref: string; incident: QaIncidentInput; environments: QaEnvironmentSnapshot[]; reproduction_attempts: ReproductionAttempt[]; evidence_records: QaEvidenceRecordInput[]; hypotheses: QaHypothesisInput[]; causal_experiments: QaCausalExperimentInput[]; candidate_fix: QaCandidateFixInput; regression: QaRegressionEvidenceInput; suite_descriptors: QaSuiteDescriptorInput[]; suite_results: QaSuiteResultInput[]; stability?: QaStabilityEvidenceInput; security: QaSecurityBoundaryInput; acceptance: QaAcceptanceCriterionRef[]; evidence_required: QaEvidenceRequirementRef[]; known_limitations: string[]; }
export interface QaDebuggingBlocker { code: QaDebuggingBlockerCode; message: string; evidence_refs: string[]; }
export interface QaDebuggingAtomicDecision { reproduction: { signature_result: QaCheckResult; setup_result: QaCheckResult; evidence_result: QaCheckResult }; evidence: { traceability_result: QaCheckResult; revision_binding_result: QaCheckResult; contradiction_result: QaCheckResult }; root_cause: { hypothesis_result: QaCheckResult; causal_evidence_result: QaCheckResult; classification_result: QaCheckResult }; fix: { causal_alignment_result: QaCheckResult; minimal_scope_result: QaCheckResult; semantic_boundary_result: QaCheckResult }; regression: { pre_fix_result: QaCheckResult; post_fix_result: QaCheckResult; candidate_binding_result: QaCheckResult }; suite: { selection_result: QaCheckResult; result_result: QaCheckResult; shared_surface_result: QaCheckResult }; stability: { intermittent_result: QaCheckResult; environment_result: QaCheckResult; retry_boundary_result: QaCheckResult }; security: { security_boundary_result: QaCheckResult; data_hygiene_result: QaCheckResult; override_result: QaCheckResult }; decision: { status_result: QaCheckResult; blocker_result: QaCheckResult; uncertainty_result: QaCheckResult }; boundary: { provider_neutral_result: QaCheckResult; future_stage_result: QaCheckResult; prior_contract_result: QaCheckResult }; }
export interface QaDebuggingDecision { status: QaDebuggingStatus; task_ref: string; incident_ref: string; reproduction_state: ReproductionState; root_cause: QaRootCauseAssessment; candidate_fix_kind: CandidateFixKind; candidate_revision_ref?: string; required_suite_refs: string[]; atomic: QaDebuggingAtomicDecision; blockers: QaDebuggingBlocker[]; next_action: QaDebuggingNextAction; evidence_refs: string[]; contradiction_refs: string[]; residual_unknowns: string[]; limitations: string[]; acceptance: QaAcceptanceCriterionRef[]; evidence_required: QaEvidenceRequirementRef[]; }
export interface QaDebuggingValidationResult { valid: boolean; errors: string[]; hard_invariants: Record<string, boolean>; recomputed_status: QaDebuggingStatus; }
export type QaDebuggingDimensionId = `SD-${string}`;
export interface QaDebuggingAssertionResult { id: string; category: QaDebuggingDimensionId | "REGRESSION_CROSS_CUTTING"; correct: boolean; hard_invariant: boolean; fixture_ref: string; }
export interface QaDebuggingUnsafeCounters { false_reproduction_claim: number; hypothesis_promoted_without_causal_evidence: number; uncausal_or_overbroad_fix_recommended: number; regression_before_after_missing: number; under_scoped_or_wrong_candidate_suite_pass: number; flaky_or_environmental_overclaim: number; security_or_semantic_boundary_override: number; provider_or_future_stage_binding: number; }
export interface QaDebuggingArmScore { total_assertions: number; correct: number; by_dimension: Record<QaDebuggingDimensionId, { assertion_ids: string[]; total: number; correct: number }>; cross_cutting: { assertion_ids: string[]; total: number; correct: number }; hard_invariant_total: number; hard_invariant_correct: number; unsafe_counters: QaDebuggingUnsafeCounters; assertions: QaDebuggingAssertionResult[]; }
export interface QaDebuggingComparison { baseline: QaDebuggingArmScore; skill: QaDebuggingArmScore; dimension_specific_total_delta: number; improved_dimensions: QaDebuggingDimensionId[]; dimension_improvements: Record<QaDebuggingDimensionId, { delta: number; scored_assertions: number; single_assertion_contributions: Record<string, number>; max_single_assertion_share: number; qualified: boolean }>; hard_invariant_regressed: boolean; meets_threshold: boolean; }
export interface FrozenQaDebuggingFixtureTruth { task_ref: string; expected_assertions: Record<string, unknown>; }
