import { FORBIDDEN_BINDING_PATTERN } from "./constants.js";
import { validateFrontendProductSurfaceDecision } from "./modeling.js";
import type { FrontendProductSurfaceDecision, FrontendProductSurfaceInput, FrontendSurfaceArmScore, FrontendSurfaceAssertionResult, FrontendSurfaceComparison, FrontendSurfaceDimensionId, FrontendSurfaceScoreCategory, FrozenFrontendSurfaceFixtureTruth } from "./types.js";

export interface FrontendSurfaceScoredRun { input: FrontendProductSurfaceInput; candidateDecision: FrontendProductSurfaceDecision; }
export const FRONTEND_SURFACE_COMPARISON_ASSERTIONS: Array<{ id: string; category: FrontendSurfaceScoreCategory }> = [...[...Array(10)].flatMap((_, dimensionIndex) => [...Array(3)].map((__, assertionIndex) => ({ id: `SD${dimensionIndex + 1}-${String.fromCharCode(65 + assertionIndex)}`, category: `SD-${String(dimensionIndex + 1).padStart(3, "0")}` as FrontendSurfaceDimensionId }))), { id: "XC-A", category: "REGRESSION_CROSS_CUTTING" }];
const dimensions = [...Array(10)].map((_, index) => `SD-${String(index + 1).padStart(3, "0")}` as FrontendSurfaceDimensionId);
const sorted = <T>(items: T[], key: (item: T) => string): T[] => [...items].sort((a, b) => key(a).localeCompare(key(b)));

/** Exactly thirty dimension-specific observations. Each ID observes a different field/property family. */
export function extractFrontendSurfaceAssertionObservations(decision: FrontendProductSurfaceDecision): Record<string, unknown> {
  const nodes = sorted(decision.flow_graph.nodes, (item) => item.id), edges = sorted(decision.flow_graph.edges, (item) => item.id), surfaces = sorted(decision.surfaces, (item) => item.surface_ref), states = sorted(decision.state_matrix, (item) => `${item.surface_ref}:${item.state}:${item.upstream_variant_refs.join(",")}`), forms = sorted(decision.forms, (item) => item.form_ref), retries = sorted(decision.retries, (item) => item.source_variant_ref), approvals = sorted(decision.approvals, (item) => item.approval_ref), responsive = sorted(decision.responsive, (item) => `${item.surface_ref}:${item.viewport}`);
  const reachable = new Set<string>(); const queue = [...decision.flow_graph.entry_node_ids]; while (queue.length) { const id = queue.shift()!; if (reachable.has(id)) continue; reachable.add(id); for (const edge of edges.filter((item) => item.from === id)) queue.push(edge.to); }
  return {
    "SD1-A": decision.flow_graph.goal_node_ids.map((id) => ({ id, reachable: reachable.has(id) })),
    "SD1-B": nodes.filter((node) => !node.terminal && !edges.some((edge) => edge.from === node.id)).map((node) => node.id),
    "SD1-C": { entries: decision.flow_graph.entry_node_ids, exits: decision.flow_graph.interruptible_exit_policy_refs, recovery_edges: edges.filter((edge) => edge.recovery).map((edge) => edge.id) },
    "SD2-A": surfaces.map((item) => ({ ref: item.surface_ref, kind: item.kind })),
    "SD2-B": surfaces.map((item) => ({ ref: item.surface_ref, priority: item.priority })),
    "SD2-C": surfaces.map((item) => ({ ref: item.surface_ref, goals: item.goal_refs })),
    "SD3-A": states.map((item) => ({ state: item.state, applicable: item.applicable })),
    "SD3-B": states.map((item) => ({ state: item.state, variants: item.upstream_variant_refs })),
    "SD3-C": states.filter((item) => ["ERROR", "UNAVAILABLE", "VALIDATION_ERROR", "REJECTED"].includes(item.state)).map((item) => ({ state: item.state, recovery: item.recovery_action_refs, announce: item.announcement_required })),
    "SD4-A": forms.map((item) => ({ ref: item.form_ref, fields: item.field_refs })),
    "SD4-B": forms.map((item) => ({ ref: item.form_ref, lifecycle: item.submit_lifecycle, duplicate_disabled: item.duplicate_submit_disabled_while_pending })),
    "SD4-C": forms.map((item) => ({ ref: item.form_ref, preserve: item.preserve_input_on_recoverable_error, cancel: item.cancel_exit_policy })),
    "SD5-A": retries.map((item) => ({ variant: item.source_variant_ref, allowed: item.allowed, authorization: item.authorization_ref ?? null })),
    "SD5-B": approvals.map((item) => ({ ref: item.approval_ref, pending: item.pending_state_ref, approved: item.approved_state_ref, rejected: item.rejected_state_ref })),
    "SD5-C": { guardrails: forms.map((item) => item.destructive_guardrail_ref ?? null), self_approval_count: approvals.filter((item) => item.frontend_can_self_approve !== false).length },
    "SD6-A": { semantic: decision.accessibility.semantic_structure_required, keyboard: decision.accessibility.keyboard_required_action_refs, visible_focus: decision.accessibility.visible_focus_required },
    "SD6-B": { names: decision.accessibility.accessible_name_control_refs, descriptions: decision.accessibility.description_association_refs, errors: decision.accessibility.error_association_refs },
    "SD6-C": { focus_order: decision.accessibility.focus_order_refs, restore: decision.accessibility.focus_restore_transition_refs, announcements: decision.accessibility.announcement_state_refs, conformance: decision.accessibility.browser_conformance_claimed },
    "SD7-A": responsive.map((item) => ({ ref: item.surface_ref, viewport: item.viewport })),
    "SD7-B": responsive.map((item) => ({ ref: item.surface_ref, viewport: item.viewport, content: item.primary_content_refs, actions: item.primary_action_refs })),
    "SD7-C": responsive.map((item) => ({ ref: item.surface_ref, viewport: item.viewport, overflow: item.overflow_strategy, semantic: item.semantic_order_preserved, focus: item.focus_order_preserved })),
    "SD8-A": states.flatMap((item) => item.upstream_variant_refs.map((ref) => ({ ref, state: item.state }))),
    "SD8-B": { retry_variant_refs: retries.map((item) => item.source_variant_ref), approval_refs: approvals.map((item) => item.approval_ref) },
    "SD8-C": { state_source_refs: states.filter((item) => item.upstream_variant_refs.length).map((item) => ({ variants: item.upstream_variant_refs, sources: item.source_refs })), client_authority_claimed: /client[_ -]?(?:tenant|user).{0,30}(?:authority|enforce)/i.test(JSON.stringify(decision)) },
    "SD9-A": { task: decision.task_ref, specs: decision.spec_refs }, "SD9-B": decision.acceptance, "SD9-C": decision.evidence_required,
    "SD10-A": { s13l: decision.deferred_to_s13l, s13o: decision.deferred_to_s13o, s13p: decision.deferred_to_s13p },
    "SD10-B": { s13q: decision.deferred_to_s13q, s13r: decision.deferred_to_s13r, s14: decision.deferred_to_s14 },
    "SD10-C": { forbidden_binding: FORBIDDEN_BINDING_PATTERN.test(JSON.stringify(decision)), status: decision.status, blockers: decision.blockers },
    "XC-A": decision.task_ref.length > 0,
  };
}

function score(runs: readonly FrontendSurfaceScoredRun[], frozenTruth: ReadonlyMap<string, FrozenFrontendSurfaceFixtureTruth>): FrontendSurfaceArmScore {
  const assertions: FrontendSurfaceAssertionResult[] = []; let deadEnds = 0, missingStates = 0, unsafe = 0, fabricated = 0, bindings = 0, hardTotal = 0, hardCorrect = 0;
  for (const run of runs) { const truth = frozenTruth.get(run.input.task_ref); if (!truth) throw new Error(`Missing frozen truth for ${run.input.task_ref}`); const actual = extractFrontendSurfaceAssertionObservations(run.candidateDecision); for (const assertion of FRONTEND_SURFACE_COMPARISON_ASSERTIONS) assertions.push({ ...assertion, correct: JSON.stringify(actual[assertion.id]) === JSON.stringify(truth.expected_assertions[assertion.id]), hard_invariant: assertion.category !== "REGRESSION_CROSS_CUTTING", fixture_ref: run.input.task_ref }); const validation = validateFrontendProductSurfaceDecision(run.candidateDecision, run.input); hardTotal += 36; hardCorrect += Object.values(validation.hard_invariants).filter(Boolean).length; deadEnds += run.candidateDecision.flow_graph.nodes.filter((node) => !node.terminal && !run.candidateDecision.flow_graph.edges.some((edge) => edge.from === node.id)).length; const mapped = run.candidateDecision.state_matrix.flatMap((item) => item.upstream_variant_refs); missingStates += run.input.upstream_variants.filter((item) => !mapped.includes(item.variant_ref)).length; const variants = new Map(run.input.upstream_variants.map((item) => [item.variant_ref, item])); unsafe += run.candidateDecision.retries.filter((item) => item.allowed && variants.get(item.source_variant_ref)?.retryability === "NOT_RETRYABLE").length + run.input.form_intents.filter((form) => form.duplicate_submit_policy === "DISABLE_WHILE_PENDING" && !run.candidateDecision.forms.find((item) => item.form_ref === form.form_ref)?.duplicate_submit_disabled_while_pending).length + run.input.form_intents.filter((form) => form.source_refs.includes("intent:destructive") && !run.candidateDecision.forms.find((item) => item.form_ref === form.form_ref)?.destructive_guardrail_ref).length; fabricated += mapped.filter((ref) => !variants.has(ref)).length; bindings += FORBIDDEN_BINDING_PATTERN.test(JSON.stringify(run.candidateDecision)) ? 1 : 0; }
  const by_dimension = Object.fromEntries(dimensions.map((dimension) => { const selected = assertions.filter((item) => item.category === dimension); return [dimension, { assertion_ids: [...new Set(selected.map((item) => item.id))], total: selected.length, correct: selected.filter((item) => item.correct).length }]; })) as FrontendSurfaceArmScore["by_dimension"]; const cross = assertions.filter((item) => item.category === "REGRESSION_CROSS_CUTTING"); return { total_assertions: assertions.length, correct: assertions.filter((item) => item.correct).length, by_dimension, cross_cutting: { assertion_ids: [...new Set(cross.map((item) => item.id))], total: cross.length, correct: cross.filter((item) => item.correct).length }, hard_invariant_total: hardTotal, hard_invariant_correct: hardCorrect, dead_end_required_flows: deadEnds, missing_required_state_mappings: missingStates, unsafe_retry_duplicate_destructive_recommendations: unsafe, fabricated_api_auth_policy_states: fabricated, framework_browser_provider_future_stage_bindings: bindings, assertions };
}

export function compareFrontendProductSurfaceRuns(baselineRuns: readonly FrontendSurfaceScoredRun[], skillRuns: readonly FrontendSurfaceScoredRun[], frozenTruthEntries: readonly FrozenFrontendSurfaceFixtureTruth[]): FrontendSurfaceComparison {
  if (baselineRuns.length !== skillRuns.length || baselineRuns.length < 6 || frozenTruthEntries.length !== skillRuns.length) throw new Error("S13K comparison requires matching six-plus arms and frozen truth."); const truth = new Map(frozenTruthEntries.map((entry) => [entry.task_ref, entry])); const baseline = score(baselineRuns, truth), skill = score(skillRuns, truth);
  const dimension_improvements = Object.fromEntries(dimensions.map((dimension) => { const delta = skill.by_dimension[dimension].correct - baseline.by_dimension[dimension].correct; const contributions: Record<string, number> = {}; for (const id of skill.by_dimension[dimension].assertion_ids) { const skillItems = skill.assertions.filter((item) => item.category === dimension && item.id === id); const baselineItems = baseline.assertions.filter((item) => item.category === dimension && item.id === id); contributions[id] = skillItems.reduce((sum, item, index) => sum + (item.correct && !baselineItems[index]?.correct ? 1 : 0), 0); } const max = Math.max(0, ...Object.values(contributions)); return [dimension, { delta, scored_assertions: skill.by_dimension[dimension].assertion_ids.length, single_assertion_contributions: contributions, max_single_assertion_share: delta > 0 ? max / delta : 0 }]; })) as FrontendSurfaceComparison["dimension_improvements"];
  const improved_dimensions = dimensions.filter((dimension) => { const evidence = dimension_improvements[dimension]; return evidence.scored_assertions >= 3 && evidence.delta >= 2 && evidence.max_single_assertion_share <= 0.5; }); const dimension_specific_total_delta = dimensions.reduce((sum, dimension) => sum + dimension_improvements[dimension].delta, 0); const hard_invariant_regressed = skill.hard_invariant_correct < baseline.hard_invariant_correct; const meets_threshold = skill.hard_invariant_correct === skill.hard_invariant_total && skill.dead_end_required_flows === 0 && skill.missing_required_state_mappings === 0 && skill.unsafe_retry_duplicate_destructive_recommendations === 0 && skill.fabricated_api_auth_policy_states === 0 && skill.framework_browser_provider_future_stage_bindings === 0 && dimension_specific_total_delta >= 14 && improved_dimensions.length >= 5 && !hard_invariant_regressed; return { baseline, skill, dimension_specific_total_delta, improved_dimensions, dimension_improvements, hard_invariant_regressed, meets_threshold };
}
