import { FABRICATED_COPY_PATTERN, FORBIDDEN_BINDING_PATTERN, UNSAFE_COPY_PATTERN, VIEWPORT_CLASSES } from "./constants.js";
import type { AccessibilityIntent, ApprovalPresentationContract, FormInteractionContract, FrontendProductSurfaceDecision, FrontendProductSurfaceInput, FrontendSurfaceSynthesisProfile, FrontendSurfaceValidationResult, ResponsiveSurfaceIntent, RetryAffordanceContract, SurfaceFlowEdge, SurfaceFlowNode, SurfaceInventoryItem, SurfaceStateContract, SurfaceStateKind, SurfaceTraceabilityEntry } from "./types.js";

const clone = <T>(value: T): T => structuredClone(value);
const unique = <T>(items: T[]): T[] => [...new Set(items)];
const same = (a: unknown, b: unknown): boolean => JSON.stringify(a) === JSON.stringify(b);
const variantState = (kind: FrontendProductSurfaceInput["upstream_variants"][number]["semantic_kind"]): SurfaceStateKind => kind;
const artifactKey = (state: SurfaceStateContract): string => `state:${state.surface_ref}:${state.state}:${state.upstream_variant_refs.join(",")}`;
const forbiddenText = (value: unknown, pattern: RegExp): boolean => pattern.test(JSON.stringify(value));

export function deriveFrontendSurfaceProfileFromRules(ruleTexts: readonly string[]): FrontendSurfaceSynthesisProfile {
  const text = ruleTexts.join("\n");
  return {
    complete_states: /upstream.*state|state.*upstream/i.test(text),
    complete_forms: /duplicate submit|accessible name|validation errors/i.test(text),
    safe_boundaries: /retry affordance|destructive action|self-approv/i.test(text),
    complete_accessibility: /keyboard-operable|focus placement|announcement intent/i.test(text),
    complete_responsive: /NARROW\/MEDIUM\/WIDE|narrow-viewport/i.test(text),
    complete_traceability: /Acceptance\/evidence.*traceable|source traceability/i.test(text),
    explicit_deferrals: /S13P\/Q\/R\/S14|S13O retry mechanics/i.test(text),
  };
}

function buildFlow(input: FrontendProductSurfaceInput): { nodes: SurfaceFlowNode[]; edges: SurfaceFlowEdge[]; entryIds: string[]; goalIds: string[] } {
  const entryIds = input.entry_intent_refs.map((ref, index) => `entry:${index + 1}:${ref}`);
  const goalRefs = unique(input.actors_goals.map((item) => item.goal_ref));
  const goalIds = goalRefs.map((ref, index) => `goal:${index + 1}:${ref}`);
  const requiredSteps: SurfaceFlowNode[] = [
    ...input.form_intents.map((form, index) => ({ id: `form-step:${index + 1}:${form.form_ref}`, kind: "COMPONENT" as const, purpose: `Validate and submit ${form.form_ref}`, source_refs: unique([form.form_ref, ...form.source_refs]), terminal: false })),
    ...input.policy_refs.approval_refs.map((ref, index) => ({ id: `approval-step:${index + 1}:${ref}`, kind: "DIALOG" as const, purpose: `Await human/policy authority ${ref}`, source_refs: [ref], terminal: false })),
  ];
  const nodes: SurfaceFlowNode[] = [
    ...entryIds.map((id, index) => ({ id, kind: "PAGE" as const, purpose: `Entry intent ${input.entry_intent_refs[index]}`, source_refs: [input.entry_intent_refs[index], ...input.spec_refs], terminal: false })),
    ...requiredSteps,
    ...goalIds.map((id, index) => ({ id, kind: "TERMINAL" as const, purpose: `Required outcome ${goalRefs[index]}`, source_refs: unique([...input.spec_refs, ...input.actors_goals.filter((item) => item.goal_ref === goalRefs[index]).flatMap((item) => item.source_refs)]), terminal: true })),
  ];
  const edges: SurfaceFlowEdge[] = goalIds.flatMap((goal, goalIndex) => { const chain = [entryIds[goalIndex % Math.max(1, entryIds.length)] ?? "missing-entry", ...requiredSteps.map((step) => step.id), goal]; return chain.slice(0, -1).map((from, edgeIndex) => ({ id: `edge:${goalIndex + 1}:${edgeIndex + 1}`, from, to: chain[edgeIndex + 1], trigger: edgeIndex === chain.length - 2 ? `Complete ${goalRefs[goalIndex]}` : `Continue required step ${edgeIndex + 1}`, condition_source_refs: unique([...input.spec_refs, ...(requiredSteps[edgeIndex]?.source_refs ?? [])]), recovery: false })); });
  return { nodes, edges, entryIds, goalIds };
}

function makeStates(input: FrontendProductSurfaceInput, surfaceRef: string, profile: FrontendSurfaceSynthesisProfile): SurfaceStateContract[] {
  const sourceRefs = [...input.spec_refs];
  if (!profile.complete_states) return [{ surface_ref: surfaceRef, state: "SUCCESS", applicable: true, upstream_variant_refs: input.upstream_variants.filter((item) => item.semantic_kind === "SUCCESS").map((item) => item.variant_ref), copy_intent: "Present the completed outcome.", available_action_refs: [], recovery_action_refs: [], announcement_required: false, source_refs: sourceRefs }];
  const states: SurfaceStateContract[] = [{ surface_ref: surfaceRef, state: "INITIAL", applicable: true, upstream_variant_refs: [], copy_intent: "Orient the user to the task.", available_action_refs: [], recovery_action_refs: [], announcement_required: false, source_refs: sourceRefs }];
  if (input.upstream_variants.length) states.push({ surface_ref: surfaceRef, state: "LOADING", applicable: true, upstream_variant_refs: [], copy_intent: "Explain that current data is loading without presenting stale success.", available_action_refs: [], recovery_action_refs: [], announcement_required: true, source_refs: unique(input.upstream_variants.flatMap((item) => item.source_refs)) });
  for (const variant of input.upstream_variants) {
    const recoverable = (variant.semantic_kind === "ERROR" || variant.semantic_kind === "UNAVAILABLE") && variant.retryability !== "NOT_RETRYABLE";
    states.push({ surface_ref: surfaceRef, state: variantState(variant.semantic_kind), applicable: true, upstream_variant_refs: [variant.variant_ref], copy_intent: `Explain the ${variant.semantic_kind.toLowerCase().replace("_", " ")} outcome and next safe action.`, available_action_refs: variant.semantic_kind === "SUCCESS" ? input.required_outcome_refs.map((ref) => `action:${ref}`) : [], recovery_action_refs: recoverable ? [`retry:${variant.variant_ref}`, "exit:safe"] : variant.semantic_kind === "VALIDATION_ERROR" ? ["return:form"] : ["ERROR", "UNAVAILABLE"].includes(variant.semantic_kind) ? ["exit:safe"] : [], announcement_required: !["SUCCESS", "EMPTY"].includes(variant.semantic_kind), source_refs: [...variant.source_refs] });
    if (recoverable) states.push({ surface_ref: surfaceRef, state: "RETRY_AVAILABLE", applicable: true, upstream_variant_refs: [variant.variant_ref], copy_intent: "Offer a source-authorized retry or safe exit.", available_action_refs: [`retry:${variant.variant_ref}`], recovery_action_refs: ["exit:safe"], announcement_required: false, source_refs: [...variant.source_refs] });
  }
  for (const approvalRef of input.policy_refs.approval_refs) for (const state of ["APPROVAL_PENDING", "APPROVED", "REJECTED"] as const) states.push({ surface_ref: surfaceRef, state, applicable: true, upstream_variant_refs: [], copy_intent: `Represent ${state.toLowerCase().replace("_", " ")} without changing authority.`, available_action_refs: state === "REJECTED" ? ["exit:safe"] : [], recovery_action_refs: state === "REJECTED" ? ["exit:safe"] : [], announcement_required: true, source_refs: [approvalRef] });
  return states;
}

export function synthesizeFrontendProductSurfaceDecision(input: FrontendProductSurfaceInput, profile: FrontendSurfaceSynthesisProfile = deriveFrontendSurfaceProfileFromRules([])): FrontendProductSurfaceDecision {
  const flow = buildFlow(input); const primarySurface = flow.entryIds[0] ?? `entry:1:${input.task_ref}`;
  const surfaces: SurfaceInventoryItem[] = flow.nodes.map((node) => ({ surface_ref: node.id, kind: node.kind, priority: node.terminal ? "PRIMARY" : "SECONDARY", goal_refs: node.terminal ? [node.id.split(":").slice(2).join(":")] : unique(input.actors_goals.map((item) => item.goal_ref)), source_refs: [...node.source_refs] }));
  const state_matrix = makeStates(input, primarySurface, profile);
  const forms: FormInteractionContract[] = input.form_intents.map((form) => ({ form_ref: form.form_ref, field_refs: form.field_intents.map((field) => field.field_ref), submit_lifecycle: ["IDLE", "SUBMITTING", "SUCCESS_OR_ERROR"], duplicate_submit_disabled_while_pending: profile.complete_forms ? form.duplicate_submit_policy === "DISABLE_WHILE_PENDING" : false, preserve_input_on_recoverable_error: profile.complete_forms ? form.field_intents.every((field) => field.preserve_on_recoverable_error) : false, cancel_exit_policy: profile.complete_forms ? form.cancel_exit_policy : "", destructive_guardrail_ref: profile.safe_boundaries ? form.destructive_guardrail_ref : undefined }));
  const retries: RetryAffordanceContract[] = input.upstream_variants.filter((item) => item.semantic_kind === "ERROR" || item.semantic_kind === "UNAVAILABLE").map((item) => ({ source_variant_ref: item.variant_ref, allowed: profile.safe_boundaries && (item.retryability === "SAFE_RETRY" || (item.retryability === "POLICY_REQUIRED" && input.policy_refs.retry_refs.length > 0)), authorization_ref: item.retryability === "POLICY_REQUIRED" && profile.safe_boundaries ? input.policy_refs.retry_refs[0] : undefined }));
  const approvals: ApprovalPresentationContract[] = profile.safe_boundaries ? input.policy_refs.approval_refs.map((ref) => ({ approval_ref: ref, pending_state_ref: `${primarySurface}:APPROVAL_PENDING`, approved_state_ref: `${primarySurface}:APPROVED`, rejected_state_ref: `${primarySurface}:REJECTED`, frontend_can_self_approve: false })) : [];
  const primaryActions = input.required_outcome_refs.map((ref) => `action:${ref}`);
  const accessibility: AccessibilityIntent = { semantic_structure_required: profile.complete_accessibility, keyboard_required_action_refs: profile.complete_accessibility ? primaryActions : [], focus_order_refs: profile.complete_accessibility ? surfaces.map((item) => item.surface_ref) : [], focus_restore_transition_refs: profile.complete_accessibility ? flow.edges.map((edge) => edge.id) : [], visible_focus_required: profile.complete_accessibility, accessible_name_control_refs: profile.complete_accessibility ? input.form_intents.flatMap((form) => form.field_intents.map((field) => field.field_ref)) : [], description_association_refs: profile.complete_accessibility ? input.form_intents.flatMap((form) => form.field_intents.filter((field) => field.description_intent).map((field) => field.field_ref)) : [], error_association_refs: profile.complete_accessibility ? input.form_intents.flatMap((form) => form.field_intents.filter((field) => field.error_association_required).map((field) => field.field_ref)) : [], announcement_state_refs: profile.complete_accessibility ? state_matrix.filter((state) => state.announcement_required).map(artifactKey) : [], contrast_policy_ref: input.policy_refs.accessibility_refs[0], reduced_motion_policy_ref: input.policy_refs.accessibility_refs[1], touch_target_policy_ref: input.policy_refs.accessibility_refs[2], exception_refs: [], browser_conformance_claimed: false };
  const responsive: ResponsiveSurfaceIntent[] = (profile.complete_responsive ? surfaces.flatMap((surface) => VIEWPORT_CLASSES.map((viewport) => ({ surface_ref: surface.surface_ref, viewport, primary_content_refs: [surface.surface_ref], primary_action_refs: primaryActions, overflow_strategy: input.spec_refs.some((ref) => ref.includes("collection:dense")) ? "Reflow each dense item into a labelled stacked record with bounded horizontal overflow as fallback." : "Reflow without losing essential content.", semantic_order_preserved: true, focus_order_preserved: true }))) : surfaces.map((surface) => ({ surface_ref: surface.surface_ref, viewport: "WIDE" as const, primary_content_refs: [surface.surface_ref], primary_action_refs: [], overflow_strategy: "Use available width.", semantic_order_preserved: true, focus_order_preserved: true })));
  const retriesAndApprovals = [...retries.map((item) => ({ artifact_ref: `retry:${item.source_variant_ref}`, source_refs: input.upstream_variants.find((variant) => variant.variant_ref === item.source_variant_ref)?.source_refs ?? [] })), ...approvals.map((item) => ({ artifact_ref: `approval:${item.approval_ref}`, source_refs: [item.approval_ref] }))];
  const traceability: SurfaceTraceabilityEntry[] = profile.complete_traceability ? [
    ...flow.nodes.map((item) => ({ artifact_ref: item.id, source_refs: item.source_refs })), ...flow.edges.map((item) => ({ artifact_ref: item.id, source_refs: item.condition_source_refs })), ...surfaces.map((item) => ({ artifact_ref: `surface:${item.surface_ref}`, source_refs: item.source_refs })), ...state_matrix.map((item) => ({ artifact_ref: artifactKey(item), source_refs: item.source_refs })), ...forms.map((item) => ({ artifact_ref: `form:${item.form_ref}`, source_refs: input.form_intents.find((form) => form.form_ref === item.form_ref)?.source_refs ?? [] })), ...retriesAndApprovals, { artifact_ref: "accessibility", source_refs: unique([...input.policy_refs.accessibility_refs, ...input.spec_refs]) }, ...responsive.map((item) => ({ artifact_ref: `responsive:${item.surface_ref}:${item.viewport}`, source_refs: unique([...input.policy_refs.responsive_refs, ...input.spec_refs]) })),
  ] : [{ artifact_ref: input.task_ref, source_refs: [...input.spec_refs] }];
  const decision: FrontendProductSurfaceDecision = { status: "READY", blockers: [], task_ref: input.task_ref, spec_refs: [...input.spec_refs], flow_graph: { entry_node_ids: flow.entryIds, goal_node_ids: flow.goalIds, nodes: flow.nodes, edges: flow.edges, interruptible_exit_policy_refs: flow.nodes.length > 2 ? [...input.spec_refs] : [] }, surfaces, state_matrix, forms, retries, approvals, accessibility, responsive, traceability, acceptance: clone(input.acceptance), evidence_required: clone(input.evidence_required), deferred_to_s13l: profile.explicit_deferrals ? ["security and authorization enforcement"] : [], deferred_to_s13o: profile.explicit_deferrals ? ["retry mechanics and reliability"] : [], deferred_to_s13p: profile.explicit_deferrals ? ["AI-system observability"] : [], deferred_to_s13q: profile.explicit_deferrals ? ["delivery copy and demo"] : [], deferred_to_s13r: profile.explicit_deferrals ? ["deployment"] : [], deferred_to_s14: profile.explicit_deferrals ? ["browser/runtime capability binding"] : [] };
  return decision;
}

function structuralErrors(candidate: FrontendProductSurfaceDecision, input: FrontendProductSurfaceInput): { errors: string[]; hard: Record<string, boolean> } {
  const failures = new Map<string, string[]>(); const fail = (id: string, message: string) => failures.set(id, [...(failures.get(id) ?? []), message]);
  if (!input.task_ref || candidate.task_ref !== input.task_ref) fail("HI-001", "Decision must represent exactly the bounded input task.");
  if (forbiddenText(candidate, FORBIDDEN_BINDING_PATTERN)) fail("HI-004", "Concrete framework/browser/provider/future runtime binding is forbidden.");
  const nodes = new Map(candidate.flow_graph.nodes.map((node) => [node.id, node])); const outgoing = new Map<string, SurfaceFlowEdge[]>(); for (const edge of candidate.flow_graph.edges) outgoing.set(edge.from, [...(outgoing.get(edge.from) ?? []), edge]);
  const reachable = new Set<string>(); const queue = candidate.flow_graph.entry_node_ids.filter((id) => nodes.has(id)); while (queue.length) { const id = queue.shift()!; if (reachable.has(id)) continue; reachable.add(id); for (const edge of outgoing.get(id) ?? []) if (nodes.has(edge.to)) queue.push(edge.to); }
  if (!candidate.flow_graph.goal_node_ids.every((id) => reachable.has(id))) fail("HI-005", "Every required goal must be reachable.");
  const requiredSurfaceRefs = new Set(candidate.surfaces.map((item) => item.surface_ref)); if (candidate.flow_graph.nodes.some((node) => !node.terminal && (!reachable.has(node.id) || !requiredSurfaceRefs.has(node.id)))) fail("HI-006", "Every required nonterminal surface must be reachable.");
  if (candidate.flow_graph.nodes.some((node) => !node.terminal && !(outgoing.get(node.id)?.length))) fail("HI-007", "Nonterminal dead end detected.");
  if (candidate.state_matrix.some((state) => ["ERROR", "UNAVAILABLE", "RETRY_AVAILABLE", "REJECTED"].includes(state.state) && state.applicable && state.recovery_action_refs.length === 0)) fail("HI-008", "Recoverable/interruption state lacks recovery or safe exit.");
  if (candidate.flow_graph.nodes.length > 2 && !candidate.flow_graph.interruptible_exit_policy_refs.length) fail("HI-009", "Interruptible multi-step flow lacks exit policy.");
  if (candidate.flow_graph.edges.some((edge) => !edge.condition_source_refs.length || !nodes.has(edge.from) || !nodes.has(edge.to))) fail("HI-010", "Flow transition lacks valid source-backed endpoints.");
  const inputVariants = new Map(input.upstream_variants.map((item) => [item.variant_ref, item])); const mapped = candidate.state_matrix.flatMap((state) => state.upstream_variant_refs); if (input.upstream_variants.some((item) => !mapped.includes(item.variant_ref))) fail("HI-010", "Applicable upstream variant is not mapped.");
  if (mapped.some((ref) => !inputVariants.has(ref))) fail("HI-011", "Candidate fabricates an upstream API/auth/policy state.");
  if (input.upstream_variants.length && !candidate.state_matrix.some((state) => state.state === "LOADING" && state.applicable)) fail("HI-012", "Async transition lacks loading semantics.");
  if (input.upstream_variants.some((item) => item.semantic_kind === "EMPTY") && !candidate.state_matrix.some((state) => state.state === "EMPTY" && state.upstream_variant_refs.some((ref) => inputVariants.get(ref)?.semantic_kind === "EMPTY"))) fail("HI-013", "Applicable empty-success state is missing.");
  for (const variant of input.upstream_variants) if (!candidate.state_matrix.some((state) => state.upstream_variant_refs.includes(variant.variant_ref) && state.state === variantState(variant.semantic_kind))) fail("HI-014", `Variant ${variant.variant_ref} maps to the wrong semantic state.`);
  for (const retry of candidate.retries) { const variant = inputVariants.get(retry.source_variant_ref); if (!variant || (retry.allowed && !(variant.retryability === "SAFE_RETRY" || (variant.retryability === "POLICY_REQUIRED" && retry.authorization_ref && input.policy_refs.retry_refs.includes(retry.authorization_ref))))) fail("HI-015", "Retry affordance lacks source-backed safety."); }
  for (const form of input.form_intents) { const actual = candidate.forms.find((item) => item.form_ref === form.form_ref); if (!actual || (form.duplicate_submit_policy === "DISABLE_WHILE_PENDING" && !actual.duplicate_submit_disabled_while_pending)) fail("HI-016", "Duplicate submit is not prevented while pending."); if (form.source_refs.includes("intent:destructive") && (!actual?.destructive_guardrail_ref || !input.policy_refs.security_refs.includes(actual.destructive_guardrail_ref))) fail("HI-017", "Destructive intent lacks approved guardrail ref."); }
  if (candidate.approvals.some((item) => item.frontend_can_self_approve !== false)) fail("HI-018", "Frontend self-approval is forbidden.");
  const goalReachableWithout = (sourceRef: string): boolean => { const removed = new Set(candidate.flow_graph.nodes.filter((node) => node.source_refs.includes(sourceRef)).map((node) => node.id)); const seen = new Set<string>(); const pending = candidate.flow_graph.entry_node_ids.filter((id) => !removed.has(id)); while (pending.length) { const id = pending.shift()!; if (seen.has(id)) continue; seen.add(id); for (const edge of candidate.flow_graph.edges.filter((item) => item.from === id && !removed.has(item.to))) pending.push(edge.to); } return candidate.flow_graph.goal_node_ids.some((id) => seen.has(id)); };
  if (input.policy_refs.approval_refs.some(goalReachableWithout)) fail("HI-018", "Required success path bypasses approval authority.");
  if (forbiddenText(candidate, /client[_ -]?(?:tenant|user).{0,30}(?:authority|authoritative|enforce)/i)) fail("HI-019", "Client state cannot be authorization authority.");
  const fields = input.form_intents.flatMap((form) => form.field_intents); if (fields.some((field) => !field.accessible_name_intent.trim()) || fields.some((field) => !candidate.accessibility.accessible_name_control_refs.includes(field.field_ref))) fail("HI-020", "Form control accessible-name intent is missing.");
  if (fields.some((field) => field.error_association_required && !candidate.accessibility.error_association_refs.includes(field.field_ref))) fail("HI-021", "Validation error association is missing.");
  if (input.form_intents.some((form) => goalReachableWithout(form.form_ref))) fail("HI-021", "Required success path bypasses form validation/submission.");
  for (const form of input.form_intents) { const actual = candidate.forms.find((item) => item.form_ref === form.form_ref); if (form.field_intents.some((field) => field.preserve_on_recoverable_error) && !actual?.preserve_input_on_recoverable_error) fail("HI-022", "Recoverable form failure does not preserve input."); }
  const primaryActions = input.required_outcome_refs.map((ref) => `action:${ref}`); if (primaryActions.some((ref) => !candidate.accessibility.keyboard_required_action_refs.includes(ref))) fail("HI-023", "Required action lacks keyboard operability intent.");
  if (candidate.flow_graph.edges.length && (!candidate.accessibility.focus_order_refs.length || !candidate.accessibility.focus_restore_transition_refs.length)) fail("HI-024", "Focus placement/restoration intent is missing.");
  const announce = candidate.state_matrix.filter((state) => state.announcement_required).map(artifactKey); if (announce.some((ref) => !candidate.accessibility.announcement_state_refs.includes(ref))) fail("HI-025", "Async/status/error announcement intent is missing.");
  if (candidate.accessibility.browser_conformance_claimed !== false) fail("HI-026", "Render-neutral decision cannot claim browser/AT conformance.");
  for (const surface of candidate.surfaces) { const rows = candidate.responsive.filter((item) => item.surface_ref === surface.surface_ref); if (VIEWPORT_CLASSES.some((viewport) => !rows.some((item) => item.viewport === viewport && item.primary_content_refs.length && item.primary_action_refs.length === primaryActions.length))) fail("HI-027", "PRIMARY content/actions are not reachable in every viewport."); if (rows.some((item) => !item.semantic_order_preserved || !item.focus_order_preserved)) fail("HI-028", "Responsive semantic/focus order is not preserved."); if (input.spec_refs.some((ref) => ref.includes("collection:dense")) && rows.some((item) => item.viewport === "NARROW" && !/stack|overflow|scroll|reflow/i.test(item.overflow_strategy))) fail("HI-029", "Dense collection lacks narrow strategy."); if (rows.some((item) => /hide|drop|discard|loss/i.test(item.overflow_strategy))) fail("HI-027", "Essential responsive content is lost."); }
  if (candidate.state_matrix.some((state) => state.copy_intent && UNSAFE_COPY_PATTERN.test(state.copy_intent))) fail("HI-030", "Raw internal/secret detail appears in product copy.");
  if (!input.policy_refs.copy_brand_refs.length && candidate.state_matrix.some((state) => state.copy_intent && FABRICATED_COPY_PATTERN.test(state.copy_intent))) fail("HI-031", "Brand/legal/localization copy was fabricated.");
  if (candidate.spec_refs.some((ref) => !input.spec_refs.includes(ref)) || candidate.state_matrix.some((state) => state.upstream_variant_refs.some((ref) => !inputVariants.has(ref)))) fail("HI-032", "Upstream API semantics were changed.");
  if ([candidate.deferred_to_s13l, candidate.deferred_to_s13o, candidate.deferred_to_s13p, candidate.deferred_to_s13q, candidate.deferred_to_s13r, candidate.deferred_to_s14].some((items) => !items.length) || forbiddenText(candidate, /\b(?:implemented|executed|running)\s+(?:auth|retry|telemetry|deployment|browser)/i)) fail("HI-033", "Adjacent stage is not explicitly deferred or was pulled forward.");
  if (!same(candidate.acceptance, input.acceptance) || !same(candidate.evidence_required, input.evidence_required)) fail("HI-034", "Acceptance/evidence was dropped, weakened or invented.");
  const requiredTrace = [...candidate.flow_graph.nodes.map((item) => item.id), ...candidate.flow_graph.edges.map((item) => item.id), ...candidate.surfaces.map((item) => `surface:${item.surface_ref}`), ...candidate.state_matrix.map(artifactKey), ...candidate.forms.map((item) => `form:${item.form_ref}`), ...candidate.retries.map((item) => `retry:${item.source_variant_ref}`), ...candidate.approvals.map((item) => `approval:${item.approval_ref}`), "accessibility", ...candidate.responsive.map((item) => `responsive:${item.surface_ref}:${item.viewport}`)]; if (requiredTrace.some((ref) => !candidate.traceability.some((item) => item.artifact_ref === ref && item.source_refs.length))) fail("HI-034", "Artifact traceability is incomplete.");
  const hard = Object.fromEntries([...Array(36)].map((_, index) => { const id = `HI-${String(index + 1).padStart(3, "0")}`; return [id, !failures.has(id)]; }));
  return { errors: [...failures].flatMap(([id, messages]) => messages.map((message) => `${id}: ${message}`)), hard };
}

export function validateFrontendProductSurfaceInput(input: FrontendProductSurfaceInput): FrontendSurfaceValidationResult {
  const errors: string[] = []; if (!input.task_ref.trim()) errors.push("HI-001: task_ref is required."); if (!input.spec_refs.length || !input.actors_goals.length || !input.entry_intent_refs.length || !input.required_outcome_refs.length) errors.push("HI-001: bounded task/spec/goal/entry/outcome facts are required."); if (input.actors_goals.some((item) => !item.actor_ref || !item.goal_ref || !item.source_refs.length)) errors.push("HI-005: actor goals require source refs."); if (input.upstream_variants.some((item) => !item.operation_ref || !item.variant_ref || !item.source_refs.length)) errors.push("HI-010: upstream variants require identity and source refs."); for (const form of input.form_intents) { if (!form.cancel_exit_policy.trim() || !form.source_refs.length) errors.push("HI-009: form cancel/exit policy and sources are required."); for (const field of form.field_intents) { if (!field.accessible_name_intent.trim()) errors.push("HI-020: accessible name intent is required."); if (!field.validation_timings.length) errors.push("HI-021: validation timing is required."); } if (form.duplicate_submit_policy === "EXPLICITLY_SAFE_MULTI_SUBMIT" && !form.source_refs.includes("proof:safe-multi-submit")) errors.push("HI-016: safe multi-submit requires source proof."); if (form.source_refs.includes("intent:destructive") && (!form.destructive_guardrail_ref || !input.policy_refs.security_refs.includes(form.destructive_guardrail_ref))) errors.push("HI-017: destructive intent requires approved guardrail ref."); }
  const hard = Object.fromEntries([...Array(36)].map((_, index) => [`HI-${String(index + 1).padStart(3, "0")}`, !errors.some((error) => error.startsWith(`HI-${String(index + 1).padStart(3, "0")}`))])); return { valid: errors.length === 0, errors, hard_invariants: hard };
}

export function validateFrontendProductSurfaceDecision(candidate: FrontendProductSurfaceDecision, input: FrontendProductSurfaceInput): FrontendSurfaceValidationResult {
  const inputValidation = validateFrontendProductSurfaceInput(input); const structural = structuralErrors(candidate, input); const structuralValid = structural.errors.length === 0 && inputValidation.valid; const expectedStatus = structuralValid ? "READY" : "BLOCKED"; const statusErrors = candidate.status === expectedStatus ? [] : [`HI-035: candidate status '${candidate.status}' does not match recomputed '${expectedStatus}'.`]; const errors = [...inputValidation.errors, ...structural.errors, ...statusErrors]; const hard = Object.fromEntries([...Array(36)].map((_, index) => { const id = `HI-${String(index + 1).padStart(3, "0")}`; return [id, (structural.hard[id] ?? true) && (inputValidation.hard_invariants[id] ?? true)]; })); hard["HI-035"] = statusErrors.length === 0; hard["HI-036"] = true; return { valid: errors.length === 0, errors, hard_invariants: hard };
}

export function gateFrontendProductSurface(input: FrontendProductSurfaceInput, candidate: FrontendProductSurfaceDecision): { decision: FrontendProductSurfaceDecision; decisionValidation: FrontendSurfaceValidationResult } {
  const inputValidation = validateFrontendProductSurfaceInput(input); const structural = structuralErrors(candidate, input); const decision = clone(candidate); const errors = [...inputValidation.errors, ...structural.errors]; decision.status = errors.length ? "BLOCKED" : "READY"; decision.blockers = [...errors]; const decisionValidation = validateFrontendProductSurfaceDecision(decision, input); return { decision, decisionValidation };
}
