export type FrontendSurfaceStatus = "READY" | "BLOCKED";
export type SurfaceKind = "PAGE" | "REGION" | "COMPONENT" | "DIALOG" | "NOTIFICATION" | "NONVISUAL_INTERACTION" | "TERMINAL";
export type SurfaceStateKind = "INITIAL" | "LOADING" | "PROGRESSIVE" | "EMPTY" | "SUCCESS" | "VALIDATION_ERROR" | "ERROR" | "UNAVAILABLE" | "RETRY_AVAILABLE" | "DISABLED" | "APPROVAL_PENDING" | "APPROVED" | "REJECTED" | "PERMISSION_DENIED";
export type ContentPriority = "PRIMARY" | "SECONDARY" | "SUPPORTING" | "OPTIONAL";
export type ViewportClass = "NARROW" | "MEDIUM" | "WIDE";
export type ValidationTiming = "ON_SUBMIT" | "ON_BLUR" | "ON_CHANGE";
export interface SurfaceActorGoal { actor_ref: string; goal_ref: string; source_refs: string[]; }
export interface UpstreamSurfaceVariant { operation_ref: string; variant_ref: string; semantic_kind: "SUCCESS" | "EMPTY" | "VALIDATION_ERROR" | "ERROR" | "UNAVAILABLE" | "PERMISSION_DENIED"; retryability: "NOT_RETRYABLE" | "SAFE_RETRY" | "POLICY_REQUIRED"; source_refs: string[]; }
export interface SurfaceFormFieldIntent { field_ref: string; required: boolean; accessible_name_intent: string; description_intent?: string; validation_timings: ValidationTiming[]; error_association_required: boolean; preserve_on_recoverable_error: boolean; source_refs: string[]; }
export interface SurfaceFormIntent { form_ref: string; field_intents: SurfaceFormFieldIntent[]; duplicate_submit_policy: "DISABLE_WHILE_PENDING" | "EXPLICITLY_SAFE_MULTI_SUBMIT"; cancel_exit_policy: string; destructive_guardrail_ref?: string; source_refs: string[]; }
export interface SurfacePolicyRefs { security_refs: string[]; approval_refs: string[]; retry_refs: string[]; copy_brand_refs: string[]; accessibility_refs: string[]; responsive_refs: string[]; }
export interface FrontendProductSurfaceInput { task_ref: string; spec_refs: string[]; actors_goals: SurfaceActorGoal[]; entry_intent_refs: string[]; required_outcome_refs: string[]; upstream_variants: UpstreamSurfaceVariant[]; form_intents: SurfaceFormIntent[]; policy_refs: SurfacePolicyRefs; acceptance: readonly unknown[]; evidence_required: readonly unknown[]; }
export interface SurfaceFlowNode { id: string; kind: SurfaceKind; purpose: string; source_refs: string[]; terminal: boolean; }
export interface SurfaceFlowEdge { id: string; from: string; to: string; trigger: string; condition_source_refs: string[]; recovery: boolean; }
export interface UserFlowGraph { entry_node_ids: string[]; goal_node_ids: string[]; nodes: SurfaceFlowNode[]; edges: SurfaceFlowEdge[]; interruptible_exit_policy_refs: string[]; }
export interface SurfaceInventoryItem { surface_ref: string; kind: SurfaceKind; priority: ContentPriority; goal_refs: string[]; source_refs: string[]; }
export interface SurfaceStateContract { surface_ref: string; state: SurfaceStateKind; applicable: boolean; upstream_variant_refs: string[]; copy_intent?: string; available_action_refs: string[]; recovery_action_refs: string[]; announcement_required: boolean; source_refs: string[]; }
export interface FormInteractionContract { form_ref: string; field_refs: string[]; submit_lifecycle: readonly ["IDLE", "SUBMITTING", "SUCCESS_OR_ERROR"]; duplicate_submit_disabled_while_pending: boolean; preserve_input_on_recoverable_error: boolean; cancel_exit_policy: string; destructive_guardrail_ref?: string; }
export interface RetryAffordanceContract { source_variant_ref: string; allowed: boolean; authorization_ref?: string; }
export interface ApprovalPresentationContract { approval_ref: string; pending_state_ref: string; approved_state_ref: string; rejected_state_ref: string; frontend_can_self_approve: false; }
export interface AccessibilityIntent { semantic_structure_required: boolean; keyboard_required_action_refs: string[]; focus_order_refs: string[]; focus_restore_transition_refs: string[]; visible_focus_required: boolean; accessible_name_control_refs: string[]; description_association_refs: string[]; error_association_refs: string[]; announcement_state_refs: string[]; contrast_policy_ref?: string; reduced_motion_policy_ref?: string; touch_target_policy_ref?: string; exception_refs: string[]; browser_conformance_claimed: false; }
export interface ResponsiveSurfaceIntent { surface_ref: string; viewport: ViewportClass; primary_content_refs: string[]; primary_action_refs: string[]; overflow_strategy: string; semantic_order_preserved: boolean; focus_order_preserved: boolean; }
export interface SurfaceTraceabilityEntry { artifact_ref: string; source_refs: string[]; }
export interface FrontendProductSurfaceDecision { status: FrontendSurfaceStatus; blockers: string[]; task_ref: string; spec_refs: string[]; flow_graph: UserFlowGraph; surfaces: SurfaceInventoryItem[]; state_matrix: SurfaceStateContract[]; forms: FormInteractionContract[]; retries: RetryAffordanceContract[]; approvals: ApprovalPresentationContract[]; accessibility: AccessibilityIntent; responsive: ResponsiveSurfaceIntent[]; traceability: SurfaceTraceabilityEntry[]; acceptance: readonly unknown[]; evidence_required: readonly unknown[]; deferred_to_s13l: string[]; deferred_to_s13o: string[]; deferred_to_s13p: string[]; deferred_to_s13q: string[]; deferred_to_s13r: string[]; deferred_to_s14: string[]; }
export interface FrontendSurfaceValidationResult { valid: boolean; errors: string[]; hard_invariants: Record<string, boolean>; }
export interface FrontendSurfaceSynthesisProfile { complete_states: boolean; complete_forms: boolean; safe_boundaries: boolean; complete_accessibility: boolean; complete_responsive: boolean; complete_traceability: boolean; explicit_deferrals: boolean; }
export type FrontendSurfaceDimensionId = "SD-001" | "SD-002" | "SD-003" | "SD-004" | "SD-005" | "SD-006" | "SD-007" | "SD-008" | "SD-009" | "SD-010";
export type FrontendSurfaceScoreCategory = FrontendSurfaceDimensionId | "REGRESSION_CROSS_CUTTING";
export interface FrontendSurfaceAssertionResult { id: string; category: FrontendSurfaceScoreCategory; correct: boolean; hard_invariant: boolean; fixture_ref: string; }
export interface FrontendSurfaceArmScore { total_assertions: number; correct: number; by_dimension: Record<FrontendSurfaceDimensionId, { assertion_ids: string[]; total: number; correct: number }>; cross_cutting: { assertion_ids: string[]; total: number; correct: number }; hard_invariant_total: number; hard_invariant_correct: number; dead_end_required_flows: number; missing_required_state_mappings: number; unsafe_retry_duplicate_destructive_recommendations: number; fabricated_api_auth_policy_states: number; framework_browser_provider_future_stage_bindings: number; assertions: FrontendSurfaceAssertionResult[]; }
export interface FrontendSurfaceComparison { baseline: FrontendSurfaceArmScore; skill: FrontendSurfaceArmScore; dimension_specific_total_delta: number; improved_dimensions: FrontendSurfaceDimensionId[]; dimension_improvements: Record<FrontendSurfaceDimensionId, { delta: number; scored_assertions: number; single_assertion_contributions: Record<string, number>; max_single_assertion_share: number }>; hard_invariant_regressed: boolean; meets_threshold: boolean; }
export interface FrozenFrontendSurfaceFixtureTruth { task_ref: string; expected_assertions: Record<string, unknown>; }
